// Version is the ledger API/semantic contract, not the shell or Backup schema version.
export const CLOUD_CONTRACT_VERSION=3;
export const DOMAIN_VERSIONS={income_sources:3,work_sessions:3,paychecks:3,financial_goals:3,coverage_settings:3,recurring_charge_revisions:3,transactions:1,transaction_items:1,recurring_charges:1,water_events:1,user_settings:1,benchmark_adjustments:1,property_condition:1,attachments:1,vehicles:2,fuel_events:2};
export const REQUIRED_FEATURES=['tax_bucket','multi_property_photos','automotive_transaction_link','housing_coverage_v1'];
export const CURRENT_CONTRACT={contract_version:CLOUD_CONTRACT_VERSION,domains:Object.keys(DOMAIN_VERSIONS),features:REQUIRED_FEATURES,read_versions:[1,2,3]};
export const contractKey=(project,owner)=>`50a-capabilities:${encodeURIComponent(project)}:${owner}`;
export const MESSAGE='Cloud update required. This version of 50A needs verified cloud support before these changes can be saved. Your form has been preserved. Connect and choose Check again.';
export function classify(error){const c=error?.code||'';if(c==='BACKEND_INCOMPATIBLE'||['42P01','42883','42703','PGRST202','PGRST204','PGRST205'].includes(c)||c==='P0001'&&/unsupported domain|update.*50a|client.*version/i.test(error.message||''))return 'BACKEND_INCOMPATIBLE';if(c==='40001'||c==='REVISION_CONFLICT')return 'REVISION_CONFLICT';if(c==='AUTH_ERROR'||c==='42501'||/^PGRST30/.test(c)||error?.status===401)return 'AUTH_ERROR';if(/^22|^23/.test(c)||c==='VALIDATION_ERROR'||c==='P0001')return 'VALIDATION_ERROR';if(!c||c==='PGRST000'||c==='OFFLINE')return 'OFFLINE';return 'SERVER_ERROR';}
export function friendly(error){const kind=classify(error);return {BACKEND_INCOMPATIBLE:MESSAGE,REVISION_CONFLICT:'Cloud changed on another device. Pending intent is preserved; review the conflict.',AUTH_ERROR:'Sign in again as this ledger owner. Pending intent is preserved.',VALIDATION_ERROR:'Cloud validation rejected this change. Pending intent is preserved for review.',SERVER_ERROR:'Cloud request failed. Pending intent is preserved; check again later.',OFFLINE:'Offline — showing cached ledger'}[kind];}
export function incompatible(){return Object.assign(Error(MESSAGE),{code:'BACKEND_INCOMPATIBLE'});}
export function validContract(c){return c&&Number.isInteger(c.contract_version)&&c.contract_version>0&&['domains','features','read_versions'].every(k=>Array.isArray(c[k]))&&c.domains.every(x=>typeof x==='string')&&c.features.every(x=>typeof x==='string')&&c.read_versions.every(Number.isInteger);}
export function missing(c,required=CURRENT_CONTRACT){return !validContract(c)?['capability contract']:['contract_version',...required.domains.filter(d=>!c.domains.includes(d)).map(d=>'domain:'+d),...required.features.filter(f=>!c.features.includes(f)).map(f=>'feature:'+f),...required.read_versions.filter(v=>!c.read_versions.includes(v)).map(v=>'read:'+v)].filter(x=>x!=='contract_version'||c.contract_version<required.contract_version);}
export class Compatibility {
 constructor({project,owner,storage,probe}){Object.assign(this,{project,owner,storage,probe});this.state='unknown';this.contract=null;try{const saved=JSON.parse(storage.getItem(contractKey(project,owner))||'null');if(saved?.project===project&&saved.owner===owner&&Number.isInteger(saved.applicationContract)&&saved.applicationContract>0&&saved.applicationContract<=CLOUD_CONTRACT_VERSION&&validContract(saved.contract)){this.contract=saved.contract;this.verifiedAt=saved.verifiedAt;this.state=saved.state==='incompatible'?'incompatible':'unknown';}}catch{}}
 async check(){try{const c=await this.probe();if(!validContract(c))throw incompatible();this.contract=c;this.verifiedAt=new Date().toISOString();this.state=missing(c).length?'incompatible':'compatible';this.persist();}catch(e){if(classify(e)==='BACKEND_INCOMPATIBLE'){this.contract=null;this.state='incompatible';this.storage.setItem(contractKey(this.project,this.owner),JSON.stringify({project:this.project,owner:this.owner,applicationContract:CLOUD_CONTRACT_VERSION,state:'incompatible',contract:null}));}else if(classify(e)==='AUTH_ERROR'){this.state='auth';}else this.state='unknown';}return this.state;}
 persist(){this.storage.setItem(contractKey(this.project,this.owner),JSON.stringify({project:this.project,owner:this.owner,applicationContract:CLOUD_CONTRACT_VERSION,contract:this.contract,verifiedAt:this.verifiedAt,state:this.state}));}
 invalidate(){this.contract=null;this.state='incompatible';this.storage.removeItem(contractKey(this.project,this.owner));}
 assert(changes){if(!Object.keys(changes).length)return;const c=this.contract;if(this.state==='auth')throw Object.assign(Error(friendly({code:'AUTH_ERROR'})),{code:'AUTH_ERROR'});if(!c)throw incompatible();for(const [domain,change]of Object.entries(changes)){if(!DOMAIN_VERSIONS[domain]||c.contract_version<DOMAIN_VERSIONS[domain]||!c.domains.includes(domain))throw incompatible();if(DOMAIN_VERSIONS[domain]===3&&!c.features.includes('housing_coverage_v1'))throw incompatible();for(const row of change.put||[]){const features=[];if(domain==='transaction_items'&&row.bucket==='tax')features.push('tax_bucket');if(domain==='transaction_items'&&row.bucket==='automotive'||domain==='fuel_events')features.push('automotive_transaction_link');if(domain==='attachments'&&row.property_condition_id)features.push('multi_property_photos');if(features.some(f=>!c.features.includes(f)))throw incompatible();}}}
}
