import {repository} from './repository.mjs';
import {DeviceLedger,MODE} from './device.mjs';
import {metrics} from './ledger-model.mjs';
const mode=()=>JSON.parse(localStorage.getItem(MODE)||'{"mode":"local"}');
export async function cutoverUI(client){
 if(!window.LedgerApp)await new Promise(r=>window.addEventListener('ledger-ready',r,{once:true}));
 const app=window.LedgerApp,root=document.getElementById('cloudLedgerControls');let device=null,user=null,ready=null,lease=false,settingsDirty=false;
 const controls=document.createElement('div');root.append(controls);
 const summary=document.createElement('p');summary.setAttribute('role','status');controls.append(summary);
 const button=(text,work)=>{const b=document.createElement('button');b.type='button';b.className='ghost';b.textContent=text;b.onclick=()=>work().catch(e=>{summary.textContent=e.message});controls.append(b);return b;};
 const active=()=>mode().mode==='cloud';
 document.getElementById('settings').addEventListener('input',e=>{if(active()&&!e.target.closest('#cloudFoundation'))settingsDirty=true});
 const editing=()=>!!document.querySelector('dialog[open]')||settingsDirty;
 function render(){document.querySelector('main').inert=!!device?.busy;document.querySelectorAll('dialog').forEach(d=>d.inert=!!device?.busy);const m=mode(),locked=active()&&(!device?.unlocked||user?.id!==m.owner);document.body.classList.toggle('cloud-locked',locked);
  activate.hidden=active()||!user;activate.disabled=!ready;check.hidden=active()||!user;
  refresh.hidden=rollback.hidden=recovery.hidden=pending.hidden=resolveConflict.hidden=!active();resolveConflict.disabled=locked||!device?.data?.queue.some(o=>o.error);resolveConflict.hidden=!active()||!device?.data?.queue.some(o=>o.error);pending.hidden=!active()||(!device?.data?.queue.length&&!device?.data?.archivedIntents?.length);rollback.disabled=locked||!!device?.data?.queue.length;recovery.disabled=locked;pending.disabled=locked||(!device?.data?.queue.length&&!device?.data?.archivedIntents?.length);
  summary.textContent=active()?`Data mode: Cloud · ${device?.status??'Locked'} · Last refresh: ${device?.data?.lastRefresh??'never'} · Pending offline changes: ${device?.data?.queue.length??0} · Conflicts/errors: ${device?.data?.queue.filter(o=>o.error).length??0}${lease?'':' · Another tab owns cloud editing; close it and reload.'}`:ready?`Data mode: Local · Cloud ledger ready · Transactions: ${ready.transactions} · Line items: ${ready.items} · Monthly bills: ${ready.bills} · Water events: ${ready.water} · Cloud reconciliation: PASS`:'Data mode: Local · Check cloud ledger before activation.';
  if(active()){
   for(const id of ['seedBtn','clearBtn','importInput','addConditionBtn','connectGoogleBtn','syncNowBtn','restoreGoogleBtn','disconnectGoogleBtn','googleClientIdInput','waterdropGallonsInput'])document.getElementById(id).disabled=true;
   document.querySelectorAll('input[type="file"]').forEach(e=>e.disabled=true);
   document.getElementById('recoveryExportBtn').hidden=true;
   document.getElementById('syncStatus').textContent='Legacy Google sync is disabled while using the Supabase cloud ledger.';
   document.getElementById('addConditionBtn').title='New evidence capture is unavailable until cloud photos are enabled.';
   document.getElementById('screenshotInput').nextElementSibling.textContent='Photo uploads aren’t available yet in cloud mode.';
   if(!document.getElementById('cloudPhotoNotice')){const note=document.createElement('p');note.id='cloudPhotoNotice';note.textContent='Photo uploads aren’t available yet in cloud mode.';document.getElementById('addConditionBtn').parentElement.append(note)}
   if(locked){document.querySelectorAll('dialog[open]').forEach(d=>d.close());app.set(app.empty());}
  }
 }
 const activate=button('Use cloud ledger on this device',async()=>{if(!ready||!user)throw Error('Check cloud ledger first');if(!lease)throw Error('Close other cloud tabs and reload before activation');if(!confirm('Use the verified cloud ledger on this device? A verified local recovery backup will be retained. Existing local storage will remain untouched.'))return;document.body.inert=true;try{device=new DeviceLedger({storage:localStorage,repo:repository(client,user.id),owner:user.id});device.unlock(user.id);await device.activate(app.get(),app.attachmentGet,async(id,backup)=>{await BackupStorage.write([{store:'recovery',value:{id,backup}}]);const saved=await BackupStorage.get('recovery',id);await BackupUtils.validate(saved.backup)},candidate=>{const prior=app.get();try{app.set(candidate);const expected=metrics(candidate);for(const [id,value] of [['recurringHousing',expected.runRate],['monthlySavings',expected.monthly],['annualSavings',expected.annual],['paybackGallons',expected.water]]){if(Number(document.getElementById(id).textContent.replace(/[^0-9.-]/g,''))!==value)throw Error('Cloud display verification failed')}}finally{app.set(prior)}});location.reload()}finally{document.body.inert=false}});
 const refresh=button('Refresh cloud ledger',async()=>{if(!device?.unlocked)throw Error('Sign in as the activated ledger owner');if(!lease)throw Error('Close the other cloud tab and reload');if(editing())throw Error('Finish or close the current edit before refreshing');await device.refresh();if(device.view())app.set(device.view());render()});
 const rollback=button('Return to local ledger',async()=>{if(!confirm('Return to the preserved local ledger? Cloud data and recovery material will remain intact.'))return;device.rollback();location.reload()});
 const recovery=button('Export pre-cutover recovery backup',async()=>{if(!device?.unlocked)throw Error('Sign in first');const r=await BackupStorage.get('recovery',device.data.recoveryId);await BackupUtils.validate(r.backup);app.downloadBackup(r.backup,'50a-pre-cutover-v3.json')});
 const pending=button('Export pending changes for review',async()=>{if(!device?.unlocked)throw Error('Sign in first');app.downloadBackup({format:'50a-pending-intent',version:1,owner:device.owner,operations:device.data.queue,archivedIntents:device.data.archivedIntents||[]},'50a-pending-intent.json');summary.textContent='Pending intent exported for review. This is not a Backup v3. Nothing was discarded.'});
 const resolveConflict=button('Use cloud version; archive pending intent',async()=>{if(!confirm('Keep the current cloud version? Pending local changes will be archived on this device for export/review, not uploaded.'))return;await device.useRemote();app.set(device.view());render()});
 const check=button('Check cloud ledger',async()=>{if(!user)throw Error('Sign in first');const snapshot=await repository(client,user.id).loadLedger(true);ready=metrics(snapshot.state);render()});
 const deleteTx=document.createElement('button');deleteTx.type='button';deleteTx.className='danger';deleteTx.textContent='Delete transaction';document.getElementById('transactionForm').append(deleteTx);const updateDelete=()=>{deleteTx.hidden=!active();deleteTx.disabled=!app.editing()||!device?.unlocked};new MutationObserver(updateDelete).observe(document.getElementById('transactionDialog'),{attributes:true,attributeFilter:['open']});updateDelete();deleteTx.onclick=()=>{try{const id=app.editing();if(!id||!device?.unlocked||!lease)return;if(!confirm('Delete this transaction and its line items from the cloud ledger?'))return;const next=app.get();next.transactions=next.transactions.filter(t=>t.id!==id);device.capture(next);app.set(device.view());document.getElementById('transactionDialog').close();device.refresh().then(()=>{if(device.view())app.set(device.view());render()})}catch(e){summary.textContent=e.message}};
 window.CloudLedger={active,view:()=>device?.view(),capture:state=>{if(!lease)throw Error('Another tab owns cloud editing');device.capture(state);settingsDirty=false;render();queueMicrotask(()=>device.refresh().then(()=>{if(device.view())app.set(device.view());render()}))},exportBackup:async()=>{try{const {backup,cached,lastRefresh}=await device.backup();if(cached&&!confirm(`Offline: export confirmed cached ledger from ${lastRefresh}?`))return;app.downloadBackup(backup);document.getElementById('backupStatus').textContent=cached?`Verified cached backup; last confirmed ${lastRefresh}.`:'Verified latest confirmed cloud backup.'}catch(e){document.getElementById('backupStatus').textContent=e.message}}};
 if(navigator.locks)navigator.locks.request('50a-cloud-editor',{ifAvailable:true},async lock=>{lease=!!lock;render();if(lock&&device?.unlocked){await device.refresh();if(device.view())app.set(device.view());render()}if(lock)await new Promise(resolve=>window.addEventListener('pagehide',resolve,{once:true}))});
 async function identity(next){user=next;ready=null;const m=mode();if(active()){
  if(device&&device.owner!==next?.id)device.lock();
  if(next?.id===m.owner){device??=new DeviceLedger({storage:localStorage,repo:repository(client,next.id),owner:next.id,onChange:()=>render()});device.unlock(next.id);if(device.view()&&!editing())app.set(device.view());if(lease&&!editing()){await device.refresh();if(device.view())app.set(device.view());}}
  else {device?.lock();app.set(app.empty());}
 }render();}
 client.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>identity(session?.user??null),0)});
 const {data,error}=await client.auth.getUser();const cached=error&&(!navigator.onLine||error.name==='AuthRetryableFetchError')?(await client.auth.getSession()).data?.session:null;await identity(data?.user??cached?.user??null);
 window.addEventListener('focus',()=>{if(active()&&device?.unlocked&&lease&&!editing())refresh.click()});window.addEventListener('online',()=>{if(active()&&device?.unlocked&&lease&&!editing())refresh.click()});
 window.addEventListener('storage',e=>{if(e.key===MODE)location.reload()});render();return {identity};
}
