import {Evidence} from './evidence.mjs';
import {EvidenceView} from './evidence-view.mjs';
import {repository} from './repository.mjs';
import {DeviceLedger,MODE} from './device.mjs';
import {metrics} from './ledger-model.mjs';
const mode=()=>JSON.parse(localStorage.getItem(MODE)||'{"mode":"local"}');
export async function cutoverUI(client){
 if(!window.LedgerApp)await new Promise(r=>window.addEventListener('ledger-ready',r,{once:true}));
 const app=window.LedgerApp,root=document.getElementById('cloudLedgerControls');let device=null,user=null,ready=null,lease=false,settingsDirty=false,evidence=null;
 const views=new EvidenceView(id=>getEvidence(id));
 const getEvidence=id=>{if(!device?.unlocked||!evidence)throw Error("Sign in to view evidence");return evidence.get(device.data.confirmed.rows.attachments.find(a=>a.id===id))};
 const controls=document.createElement('div');root.append(controls);
 const summary=document.createElement('p');summary.setAttribute('role','status');controls.append(summary);
 const button=(text,work)=>{const b=document.createElement('button');b.type='button';b.className='ghost';b.textContent=text;b.onclick=()=>work().catch(e=>{summary.textContent=e.message});controls.append(b);return b;};
 const active=()=>mode().mode==='cloud';
 document.getElementById('settings').addEventListener('input',e=>{if(active()&&!e.target.closest('#cloudFoundation'))settingsDirty=true});
 const editing=()=>!!document.querySelector('dialog[open]')||settingsDirty;
 function render(){document.querySelector('main').inert=!!device?.busy;document.querySelectorAll('dialog').forEach(d=>d.inert=!!device?.busy);const m=mode(),locked=active()&&(!device?.unlocked||user?.id!==m.owner);document.body.classList.toggle('cloud-locked',locked);
  activate.hidden=active()||!user;activate.disabled=!ready;check.hidden=active()||!user;
  refresh.hidden=rollback.hidden=recovery.hidden=pending.hidden=resolveConflict.hidden=!active();resolveConflict.disabled=locked||!device?.data?.queue.some(o=>o.error);resolveConflict.hidden=!active()||!device?.data?.queue.some(o=>o.error);pending.hidden=!active()||(!device?.data?.queue.length&&!device?.data?.archivedIntents?.length);rollback.disabled=locked||!!device?.data?.queue.length;recovery.disabled=locked;pending.disabled=locked||(!device?.data?.queue.length&&!device?.data?.archivedIntents?.length);
  resolvePhotos.hidden=!active()||!evidence?.pending();resolvePhotos.disabled=locked||device?.busy;
  summary.textContent=active()?`Data mode: Cloud · ${device?.status??'Locked'} · Last refresh: ${device?.data?.lastRefresh??'never'} · Pending offline changes: ${device?.data?.queue.length??0} · Conflicts/errors: ${device?.data?.queue.filter(o=>o.error).length??0}${evidence?.pending()?' · Photo operation pending':''}${lease?'':' · Another tab owns cloud editing; close it and reload.'}`:ready?`Data mode: Local · Cloud ledger ready · Transactions: ${ready.transactions} · Line items: ${ready.items} · Monthly bills: ${ready.bills} · Water events: ${ready.water} · Cloud reconciliation: PASS`:'Data mode: Local · Check cloud ledger before activation.';
  if(active()){
   for(const id of ['seedBtn','clearBtn','importInput','connectGoogleBtn','syncNowBtn','restoreGoogleBtn','disconnectGoogleBtn','googleClientIdInput','waterdropGallonsInput'])document.getElementById(id).disabled=true;
   document.getElementById('screenshotInput').disabled=locked;document.querySelector('#conditionForm input[type=file]').disabled=locked;document.getElementById('addConditionBtn').disabled=locked;
   document.getElementById('recoveryExportBtn').hidden=true;
   document.getElementById('syncStatus').textContent='Legacy Google sync is disabled while using the Supabase cloud ledger.';
   document.getElementById('screenshotInput').nextElementSibling.textContent='Add/take photos · uploads require a connection';
   if(locked){views.clear();app.closeEvidence?.();document.querySelectorAll('dialog[open]').forEach(d=>d.close());app.set(app.empty());}
  }
 }
 const activate=button('Use cloud ledger on this device',async()=>{if(!ready||!user)throw Error('Check cloud ledger first');if(!lease)throw Error('Close other cloud tabs and reload before activation');if(!confirm('Use the verified cloud ledger on this device? A verified local recovery backup will be retained. Existing local storage will remain untouched.'))return;document.body.inert=true;try{device=new DeviceLedger({storage:localStorage,repo:repository(client,user.id),owner:user.id});device.unlock(user.id);await device.activate(app.get(),app.attachmentGet,async(id,backup)=>{await BackupStorage.write([{store:'recovery',value:{id,backup}}]);const saved=await BackupStorage.get('recovery',id);await BackupUtils.validate(saved.backup)},candidate=>{const prior=app.get();try{app.set(candidate);const expected=metrics(candidate);for(const [id,value] of [['recurringHousing',expected.runRate],['monthlySavings',expected.monthly],['annualSavings',expected.annual],['paybackGallons',expected.water]]){if(Number(document.getElementById(id).textContent.replace(/[^0-9.-]/g,''))!==value)throw Error('Cloud display verification failed')}}finally{app.set(prior)}});location.reload()}finally{document.body.inert=false}});
 const refresh=button('Refresh cloud ledger',async()=>{if(!device?.unlocked)throw Error('Sign in as the activated ledger owner');if(evidence?.pending())throw Error('Resolve photo operation first.');if(!lease)throw Error('Close the other cloud tab and reload');if(editing())throw Error('Finish or close the current edit before refreshing');await device.refresh();if(device.view())app.set(device.view());render()});
 const rollback=button('Return to local ledger',async()=>{if(evidence?.pending())throw Error('Resolve photo operation before rollback.');if(!confirm('Return to the preserved local ledger? Cloud data and recovery material will remain intact.'))return;device.rollback();location.reload()});
 const recovery=button('Export pre-cutover recovery backup',async()=>{if(!device?.unlocked)throw Error('Sign in first');const r=await BackupStorage.get('recovery',device.data.recoveryId);await BackupUtils.validate(r.backup);app.downloadBackup(r.backup,'50a-pre-cutover-v3.json')});
 const pending=button('Export pending changes for review',async()=>{if(!device?.unlocked)throw Error('Sign in first');app.downloadBackup({format:'50a-pending-intent',version:1,owner:device.owner,operations:device.data.queue,archivedIntents:device.data.archivedIntents||[]},'50a-pending-intent.json');summary.textContent='Pending intent exported for review. This is not a Backup v3. Nothing was discarded.'});
 const resolveConflict=button('Use cloud version; archive pending intent',async()=>{if(!confirm('Keep the current cloud version? Pending local changes will be archived on this device for export/review, not uploaded.'))return;await device.useRemote();app.set(device.view());render()});
 const resolvePhotos=button('Resolve photo operation',async()=>{if(!evidence||!device?.unlocked||!lease)throw Error('Sign in as the ledger owner');device.busy=true;render();try{const cloud=await evidence.resolve();acceptCloud(cloud);summary.textContent='Photo operation resolved.';}finally{device.busy=false;render()}});
 const check=button('Check cloud ledger',async()=>{if(!user)throw Error('Sign in first');const snapshot=await repository(client,user.id).loadLedger(true);ready=metrics(snapshot.state);render()});
 const deleteTx=document.createElement('button');deleteTx.type='button';deleteTx.className='danger';deleteTx.textContent='Delete transaction';document.getElementById('transactionForm').append(deleteTx);const updateDelete=()=>{deleteTx.hidden=!active();deleteTx.disabled=!app.editing()||!device?.unlocked};new MutationObserver(updateDelete).observe(document.getElementById('transactionDialog'),{attributes:true,attributeFilter:['open']});updateDelete();deleteTx.onclick=()=>{try{const id=app.editing();if(!id||!device?.unlocked||!lease)return;if(!confirm('Delete this transaction and its line items from the cloud ledger?'))return;const next=app.get();const hasEvidence=next.transactions.find(t=>t.id===id)?.attachmentIds?.length;next.transactions=next.transactions.filter(t=>t.id!==id);if(hasEvidence){saveEvidence(next,[]).then(()=>document.getElementById('transactionDialog').close()).catch(e=>{summary.textContent=e.message;alert(e.message)});return;}device.capture(next);app.set(device.view());document.getElementById('transactionDialog').close();device.refresh().then(()=>{if(device.view())app.set(device.view());render()})}catch(e){summary.textContent=e.message}};
 function acceptCloud(cloud){if(!device.unlocked)throw Error('Signed out');device.persist({...device.data,confirmed:cloud,draft:cloud.state,draftRows:cloud.rows,lastRefresh:new Date().toISOString()});device.status='Cloud connected';app.set(device.view());}
 async function saveEvidence(next,files){if(!device?.unlocked||!lease||device.busy)throw Error('Cloud ledger is busy or locked.');if(device.data.queue.length)throw Error('Refresh and resolve pending ledger changes before uploading photos.');device.busy=true;render();try{const result=await evidence.save(device.data.confirmed,next,files);acceptCloud(result.snapshot);if(result.warning)alert(result.warning);}finally{device.busy=false;render()}}
 window.CloudLedger={active,saveEvidence,getAttachment:getEvidence,mountImage:(...args)=>views.mount(...args),clearImages:()=>views.clear(),view:()=>device?.view(),capture:state=>{if(evidence?.pending())throw Error('Resolve photo operation first.');if(!lease)throw Error('Another tab owns cloud editing');device.capture(state);settingsDirty=false;render();queueMicrotask(()=>device.refresh().then(()=>{if(device.view())app.set(device.view());render()}))},exportBackup:async()=>{try{if(evidence?.pending())throw Error('Resolve photo operation before backup.');const {backup,cached,lastRefresh}=await device.backup();if(cached&&!confirm(`Offline: export confirmed cached ledger from ${lastRefresh}?`))return;app.downloadBackup(backup);document.getElementById('backupStatus').textContent=cached?`Verified cached backup; last confirmed ${lastRefresh}.`:'Verified latest confirmed cloud backup.'}catch(e){document.getElementById('backupStatus').textContent=e.message}}};
 if(navigator.locks)navigator.locks.request('50a-cloud-editor',{ifAvailable:true},async lock=>{lease=!!lock;render();if(lock&&device?.unlocked&&!evidence?.pending()){await device.refresh();if(device.view())app.set(device.view());render()}if(lock)await new Promise(resolve=>window.addEventListener('pagehide',resolve,{once:true}))});
 async function identity(next){user=next;ready=null;const m=mode();if(active()){
  if(device&&device.owner!==next?.id){device.lock();views.clear();}
  if(next?.id===m.owner){device??=new DeviceLedger({storage:localStorage,repo:repository(client,next.id),owner:next.id,onChange:()=>render()});device.unlock(next.id);evidence??=new Evidence({client,repo:device.repo,owner:next.id,storage:localStorage,allowed:()=>device?.unlocked&&user?.id===next.id});device.repo.getAttachment=(id,snap)=>evidence.get(snap.rows.attachments.find(a=>a.id===id));if(device.view()&&!editing())app.set(device.view());if(lease&&!editing()&&!evidence.pending()){await device.refresh();if(device.view())app.set(device.view());}}
  else {device?.lock();app.set(app.empty());}
 }render();}
 let identityVersion=0;
 async function restoreIdentity(){const version=++identityVersion;const {data,error}=await client.auth.getUser();if(version===identityVersion)await identity(error?null:data?.user??null);}
 client.auth.onAuthStateChange((_event,session)=>{if(!session){identityVersion++;void identity(null);}else setTimeout(()=>restoreIdentity(),0)});
 await restoreIdentity();
 window.addEventListener('focus',()=>{if(active()&&device?.unlocked&&lease&&!editing())refresh.click()});window.addEventListener('online',()=>{if(active()&&device?.unlocked&&lease&&!editing())refresh.click()});
 window.addEventListener('storage',e=>{if(e.key===MODE)location.reload()});render();return {identity};
}
