import {classify,friendly,incompatible} from './contract.mjs';
import Backup from '../backup-utils.js';
import {toCloud,diff} from './ledger-model.mjs';
export const MODE='50a-data-mode';
export const cacheKey=owner=>'50a-cloud:'+owner;
export class DeviceLedger {
 constructor({storage,repo,owner,onChange=()=>{},uuid=()=>crypto.randomUUID()}){Object.assign(this,{storage,repo,owner,onChange,uuid});this.data=JSON.parse(storage.getItem(cacheKey(owner))??'null')??{owner,queue:[],recoveryId:JSON.parse(storage.getItem(MODE)||'null')?.recoveryId};this.unlocked=false;this.busy=false;this.status='Locked';}
 persist(next){this.storage.setItem(cacheKey(this.owner),JSON.stringify(next));this.data=next;this.onChange();}
 unlock(owner){if(owner!==this.owner){this.lock();throw Error('Account mismatch; previous cache remains locked');}this.unlocked=true;this.status='Offline — showing cached ledger';this.onChange();}
 lock(){this.unlocked=false;this.status='Locked — sign in as this device’s ledger owner';this.onChange();}
 view(){return this.unlocked?this.data?.draft:null;}
 async activate(local,getAttachment,storeRecovery,verifyRender=()=>{}){if(!this.unlocked)throw Error('Sign in first');const before=this.storage.getItem('fiftyA-ledger-v1');const cloud=await this.repo.loadLedger(true);const backup=await Backup.create(local,getAttachment);await Backup.validate(backup);const recoveryId='cloud-before:'+this.uuid();await storeRecovery(recoveryId,backup);await verifyRender(cloud.state);const next={owner:this.owner,confirmed:cloud,draft:cloud.state,draftRows:cloud.rows,queue:[],recoveryId,lastRefresh:new Date().toISOString()};if(this.storage.getItem('fiftyA-ledger-v1')!==before)throw Error('Local ledger changed during activation; retry');this.persist(next);this.storage.setItem(MODE,JSON.stringify({mode:'cloud',owner:this.owner,recoveryId}));this.status='Cloud connected';this.onChange();}
 capture(state){if(this.busy)throw Error('Cloud refresh in progress; retry save');if(!this.unlocked)throw Error('Cloud ledger is locked');const blocked=this.data.queue.find(o=>o.error);if(blocked)throw Error(blocked.error==='conflict'?'Resolve pending conflict before more changes':friendly({code:blocked.error==='rejected'?'VALIDATION_ERROR':blocked.error}));const rows=toCloud(state,this.owner,this.data.draftRows),changes=diff(this.data.draftRows,rows);if(!Object.keys(changes).length)return;if(!this.repo.assertCompatible)throw incompatible();this.repo.assertCompatible(changes);const queue=[...this.data.queue,{id:this.uuid(),revision:this.data.queue.length?null:this.data.confirmed.revision,changes}];this.persist({...this.data,draft:structuredClone(state),draftRows:rows,queue});this.status='Pending changes';}
 async checkCompatibility(){if(!this.unlocked||this.busy)throw Error('Finish cloud requests and sign in before checking again.');this.busy=true;this.onChange();try{const state=await this.repo.checkCompatibility();if(!this.unlocked)throw Error('Signed out');if(state==='compatible'&&this.data.queue.length)return 'pending';if(state==='compatible'){const remote=await this.repo.loadLedger();if(!this.unlocked)throw Error('Signed out');const normalized=Object.fromEntries(Object.keys(toCloud(this.data.draft,this.owner,this.data.draftRows)).map(k=>[k,remote.rows[k]||[]]));if(Object.keys(diff(this.data.confirmed.rows,normalized)).length)throw Error('Ledger changed on another device. Your form is preserved; cancel and reopen it after refreshing.');this.persist({...this.data,confirmed:remote,draftRows:normalized});}return state;}finally{this.busy=false;this.onChange();}}
 async refresh(){if(!this.unlocked||this.busy)return;this.busy=true;this.onChange();try{
  await this.repo.checkCompatibility?.();
  while(this.data?.queue.length){const op=this.data.queue[0];if(op.error){const remote=await this.repo.loadLedger();this.persist({...this.data,confirmed:remote});this.status=friendly({code:op.error==='conflict'?'40001':op.error==='rejected'?'VALIDATION_ERROR':op.error});return;}
   try{const ack=await this.repo.apply(op);if(!this.unlocked)return;const queue=this.data.queue.slice(1).map((o,i)=>i?o:{...o,revision:ack.revision});this.persist({...this.data,queue});}
   catch(e){if(classify(e)!=='OFFLINE'){this.persist({...this.data,queue:this.data.queue.map((o,i)=>i?o:{...o,error:classify(e)==='REVISION_CONFLICT'?'conflict':classify(e)})});this.status=friendly(e);try{const remote=await this.repo.loadLedger();this.persist({...this.data,confirmed:remote})}catch{}return;}throw e;}
  }
  const cloud=await this.repo.loadLedger();if(!this.unlocked)return;this.persist({...this.data,confirmed:cloud,draft:cloud.state,draftRows:cloud.rows,lastRefresh:new Date().toISOString()});this.status='Cloud connected';
 }catch(e){this.status=friendly(e);}finally{this.busy=false;this.onChange();}}
 async useRemote(){if(!this.unlocked||this.busy)throw Error('Unlock and finish cloud requests first');const cloud=await this.repo.loadLedger();if(!this.unlocked)throw Error('Signed out');this.persist({...this.data,archivedIntents:[...(this.data.archivedIntents||[]),{archivedAt:new Date().toISOString(),operations:this.data.queue}],queue:[],confirmed:cloud,draft:cloud.state,draftRows:cloud.rows,lastRefresh:new Date().toISOString()});this.status='Cloud connected';this.onChange();}
 rollback(){if(!this.unlocked)throw Error('Sign in before rollback');if(this.data.queue.length)throw Error('Pending changes retained; export pending intent and resolve it before rollback');this.storage.setItem(MODE,JSON.stringify({mode:'local'}));}
 async backup(){if(!this.unlocked)throw Error('Sign in before export');if(this.data.queue.length)throw Error('Reconcile pending changes before exporting a cloud backup');await this.refresh();if(this.data.queue.length)throw Error('Pending changes remain');const snapshot=this.data.confirmed;const b=await Backup.create(snapshot.state,id=>this.repo.getAttachment(id,snapshot));return {backup:b,cached:this.status!=='Cloud connected',lastRefresh:this.data.lastRefresh};}
}
