import Backup from '../backup-utils.js';
import {toCloud,diff} from './ledger-model.mjs';
export const MODE='50a-data-mode';
export const cacheKey=owner=>'50a-cloud:'+owner;
export class DeviceLedger {
 constructor({storage,repo,owner,onChange=()=>{},uuid=()=>crypto.randomUUID()}){Object.assign(this,{storage,repo,owner,onChange,uuid});this.data=JSON.parse(storage.getItem(cacheKey(owner))??'null')??{owner,queue:[],recoveryId:JSON.parse(storage.getItem(MODE)||'null')?.recoveryId};this.unlocked=false;this.busy=false;this.status='Locked';}
 persist(next){this.storage.setItem(cacheKey(this.owner),JSON.stringify(next));this.data=next;this.onChange();}
 unlock(owner){if(owner!==this.owner){this.lock();throw Error('Account mismatch; previous cache remains locked');}this.unlocked=true;this.status='Offline — showing cached ledger';this.onChange();}
 lock(){this.unlocked=false;this.status='Locked — sign in as this device’s ledger owner';this.onChange();}
 view(){return this.unlocked?this.data?.draft:null;}
 async activate(local,getAttachment,storeRecovery,verifyRender=()=>{}){if(!this.unlocked)throw Error('Sign in first');const before=this.storage.getItem('fiftyA-ledger-v1');const cloud=await this.repo.loadLedger(true);const backup=await Backup.create(local,getAttachment);await Backup.validate(backup);const recoveryId='cloud-before:'+this.uuid();await storeRecovery(recoveryId,backup);await verifyRender(cloud.state);const next={owner:this.owner,confirmed:cloud,draft:cloud.state,draftRows:cloud.rows,queue:[],recoveryId,lastRefresh:new Date().toISOString()};if(this.storage.getItem('fiftyA-ledger-v1')!==before)throw Error('Local ledger changed during activation; retry');this.persist(next);this.storage.setItem(MODE,JSON.stringify({mode:'cloud',owner:this.owner,recoveryId}));this.status='Cloud connected';this.onChange();}
 capture(state){if(this.busy)throw Error('Cloud refresh in progress; retry save');if(!this.unlocked)throw Error('Cloud ledger is locked');if(this.data.queue.some(o=>o.error))throw Error('Resolve pending conflict before more changes');const rows=toCloud(state,this.owner,this.data.draftRows),changes=diff(this.data.draftRows,rows);if(!Object.keys(changes).length)return;const queue=[...this.data.queue,{id:this.uuid(),revision:this.data.queue.length?null:this.data.confirmed.revision,changes}];this.persist({...this.data,draft:structuredClone(state),draftRows:rows,queue});this.status='Pending changes';}
 async refresh(){if(!this.unlocked||this.busy)return;this.busy=true;this.onChange();try{
  while(this.data?.queue.length){const op=this.data.queue[0];if(op.error){const remote=await this.repo.loadLedger();this.persist({...this.data,confirmed:remote});this.status='Conflict — pending intent preserved';return;}
   try{const ack=await this.repo.apply(op);if(!this.unlocked)return;const queue=this.data.queue.slice(1).map((o,i)=>i?o:{...o,revision:ack.revision});this.persist({...this.data,queue});}
   catch(e){if(e.code==='40001'||(e.code&&e.code!=='PGRST000')){this.persist({...this.data,queue:this.data.queue.map((o,i)=>i?o:{...o,error:e.code==='40001'?'conflict':'rejected'})});this.status='Conflict/error — pending intent preserved';try{const remote=await this.repo.loadLedger();this.persist({...this.data,confirmed:remote})}catch{}return;}throw e;}
  }
  const cloud=await this.repo.loadLedger();if(!this.unlocked)return;this.persist({...this.data,confirmed:cloud,draft:cloud.state,draftRows:cloud.rows,lastRefresh:new Date().toISOString()});this.status='Cloud connected';
 }catch{this.status='Offline/error — showing cached ledger';}finally{this.busy=false;this.onChange();}}
 async useRemote(){if(!this.unlocked||this.busy)throw Error('Unlock and finish cloud requests first');const cloud=await this.repo.loadLedger();if(!this.unlocked)throw Error('Signed out');this.persist({...this.data,archivedIntents:[...(this.data.archivedIntents||[]),{archivedAt:new Date().toISOString(),operations:this.data.queue}],queue:[],confirmed:cloud,draft:cloud.state,draftRows:cloud.rows,lastRefresh:new Date().toISOString()});this.status='Cloud connected';this.onChange();}
 rollback(){if(!this.unlocked)throw Error('Sign in before rollback');if(this.data.queue.length)throw Error('Pending changes retained; export pending intent and resolve it before rollback');this.storage.setItem(MODE,JSON.stringify({mode:'local'}));}
 async backup(){if(!this.unlocked)throw Error('Sign in before export');if(this.data.queue.length)throw Error('Reconcile pending changes before exporting a cloud backup');await this.refresh();if(this.data.queue.length)throw Error('Pending changes remain');const b=await Backup.create(this.data.confirmed.state,()=>null);return {backup:b,cached:this.status!=='Cloud connected',lastRefresh:this.data.lastRefresh};}
}
