import Backup from '../backup-utils.js';
import Finance from '../finance-utils.js';
export const domains=['recurring_charges','transactions','transaction_items','water_events','user_settings','benchmark_adjustments'];
const clean=r=>Object.fromEntries(Object.entries(r).filter(([k])=>!['created_at','updated_at'].includes(k)));
const numeric=(v,scale=2)=>{const n=Number(v??0),factor=10**scale;if(!Number.isFinite(n)||n<0||n>=10**(12-scale)||Math.abs(n*factor-Math.round(n*factor))>1e-6)throw Error('Amount cannot be stored without rounding');return n;};
export function fromCloud(snapshot,owner){
 const r=snapshot.rows;
 for(const t of [...domains,'property_condition','attachments']){if(!Array.isArray(r[t])||r[t].some(x=>x.owner_id!==owner))throw Error('Invalid cloud owner or records');}
 if(r.user_settings.length!==1||r.property_condition.length||r.attachments.length)throw Error('Cloud settings/evidence require review');
 const st=r.user_settings[0],events=[...r.water_events].sort((a,b)=>(a.completed_at??'').localeCompare(b.completed_at??'')||a.id.localeCompare(b.id));
 if(events.some(e=>e.gallons!==1))throw Error('Unexpected water-event size');
 const item=i=>({name:i.description,amount:i.amount,category:i.category,bucket:i.bucket,setupClass:i.setup_class,status:i.status,adjustment:i.adjustment,depositStatus:i.deposit_status,depositRefunded:i.deposit_refunded,moveIn:i.move_in,prorated:i.prorated,estimated:i.estimated,recurring:i.recurring,giftCardOffset:i.gift_card_offset});
 for(const t of r.transactions){const items=r.transaction_items.filter(i=>i.transaction_id===t.id).sort((a,b)=>a.position-b.position);if(items.some((item,index)=>item.position!==index))throw Error('Invalid cloud item ordering');}
 const txIds=new Set(r.transactions.map(t=>t.id));if(r.transaction_items.some(i=>!txIds.has(i.transaction_id)))throw Error('Dangling cloud item');
 return {portableSchemaVersion:3,datasetVersion:1,legacyDemoCleanupVersion:2,recurringChargesVersion:1,budget:st.setup_budget,condition:[],transactions:[...r.transactions].sort((a,b)=>a.transaction_date.localeCompare(b.transaction_date)||a.id.localeCompare(b.id)).map(t=>({id:t.id,merchant:t.merchant,date:t.transaction_date,notes:t.notes,receipt:null,attachmentIds:[],items:r.transaction_items.filter(i=>i.transaction_id===t.id).sort((a,b)=>a.position-b.position).map(item),...(t.recurring_charge_id?{recurringChargeId:t.recurring_charge_id,oneTimeAmount:t.one_time_amount}:{}),...(t.system_key?{systemKey:t.system_key}:{}),...(t.sample_key?{sampleKey:t.sample_key}:{})})),recurringCharges:r.recurring_charges.map(b=>({id:b.id,name:b.name,amount:b.amount,category:b.category,kind:b.kind,utilityType:b.utility_type,active:b.active,createdAt:b.created_at,updatedAt:b.updated_at})),settings:{rent50a:r.recurring_charges.find(b=>b.name.toLowerCase()==='rent')?.amount??0,joshRent:st.josh_rent,joshStayDays:st.josh_stay_days,joshAdjustments:[...r.benchmark_adjustments].sort((a,b)=>a.position-b.position).map(a=>({label:a.label,amount:a.amount})),moveInDate:st.move_in_date,proratedRent:st.prorated_rent,adminFee:st.admin_fee,depositAmount:st.deposit_amount,depositStatus:st.deposit_status,depositRefunded:st.deposit_refunded,forgottenEssentialsBudget:st.forgotten_essentials_budget,googleSync:{clientId:'',status:'disabled'},waterdropPayback:{name:st.waterdrop_name,gallonsLogged:events.length,completedDates:[],waterdropCompletions:events.map((e,i)=>({id:e.id,completedAt:e.completed_at,gallon:i+1,legacy:e.legacy})),baselineCostPerGallon:st.waterdrop_baseline_cost_per_gallon,systemCost:st.waterdrop_system_cost,breakEvenGallon:st.waterdrop_break_even_gallon}}};
}
export function toCloud(state,owner,previous,uuid=()=>crypto.randomUUID()){
 Backup.validateState(Backup.portableState(state));
 if(state.condition.length||state.transactions.some(t=>t.attachmentIds.length||t.receipt))throw Error('New evidence is unavailable until cloud photos are enabled');
 const row=(id)=>({id,owner_id:owner}),st=state.settings,w=st.waterdropPayback,r=Object.fromEntries(domains.map(t=>[t,[]]));
 r.recurring_charges=state.recurringCharges.map(b=>({...row(b.id),name:b.name,amount:numeric(b.amount),category:b.category,kind:b.kind,utility_type:b.utilityType,active:b.active}));
 for(const t of state.transactions){r.transactions.push({...row(t.id),merchant:t.merchant,transaction_date:t.date,notes:t.notes,recurring_charge_id:t.recurringChargeId??null,one_time_amount:numeric(t.oneTimeAmount),system_key:t.systemKey??null,sample_key:t.sampleKey??null});t.items.forEach((i,position)=>r.transaction_items.push({...row(previous.transaction_items.find(x=>x.transaction_id===t.id&&x.position===position)?.id??uuid()),transaction_id:t.id,position,description:i.name,amount:numeric(i.amount),category:i.category,bucket:i.bucket,setup_class:i.setupClass??'none',status:i.status,adjustment:numeric(i.adjustment),deposit_status:i.depositStatus??'held',deposit_refunded:numeric(i.depositRefunded),move_in:i.moveIn??false,prorated:i.prorated??false,estimated:i.estimated??false,recurring:i.recurring??false,gift_card_offset:numeric(i.giftCardOffset)}));}
 r.water_events=w.waterdropCompletions.map(e=>({...row(e.id),completed_at:e.completedAt,gallons:1,legacy:e.legacy}));
 r.user_settings=[{owner_id:owner,setup_budget:numeric(state.budget),forgotten_essentials_budget:numeric(st.forgottenEssentialsBudget),josh_rent:numeric(st.joshRent),josh_stay_days:st.joshStayDays,move_in_date:st.moveInDate,prorated_rent:numeric(st.proratedRent),admin_fee:numeric(st.adminFee),deposit_amount:numeric(st.depositAmount),deposit_status:st.depositStatus,deposit_refunded:numeric(st.depositRefunded),waterdrop_name:w.name,waterdrop_baseline_cost_per_gallon:numeric(w.baselineCostPerGallon,4),waterdrop_system_cost:numeric(w.systemCost),waterdrop_break_even_gallon:w.breakEvenGallon}];
 r.benchmark_adjustments=st.joshAdjustments.map((a,position)=>({...row(previous.benchmark_adjustments.find(x=>x.position===position)?.id??uuid()),position,label:a.label,amount:numeric(a.amount)}));return r;
}
export function diff(before,after){const out={};for(const t of domains){const id=r=>r.id??r.owner_id,old=new Map(before[t].map(r=>[id(r),r])),next=new Set(after[t].map(id));const put=after[t].filter(r=>Backup.canonical(clean(old.get(id(r))??{}))!==Backup.canonical(clean(r))).map(clean),remove=[...old.keys()].filter(k=>!next.has(k));if(put.length||remove.length)out[t]={put,remove};}
 // Always touch the parent for an item edit: server-side payment validation must
 // run even when merchant/date/one-time fields have not changed.
 if(out.transaction_items){const ids=new Set([...out.transaction_items.put.map(i=>i.transaction_id),...before.transaction_items.filter(i=>out.transaction_items.remove.includes(i.id)).map(i=>i.transaction_id)]);for(const id of ids){const parent=after.transactions.find(t=>t.id===id);if(parent){out.transactions??={put:[],remove:[]};if(!out.transactions.put.some(t=>t.id===id))out.transactions.put.push(clean(parent));}}}
 return out;}
export function metrics(s){const sept=Finance.expenses(s.transactions.filter(t=>t.date.startsWith('2026-09')).flatMap(t=>t.items));const b=Finance.benchmark(s.settings,s.recurringCharges);return {transactions:s.transactions.length,items:s.transactions.reduce((n,t)=>n+t.items.length,0),bills:s.recurringCharges.length,water:s.settings.waterdropPayback.waterdropCompletions.length,september:Math.round(sept.expenses*100)/100,housing:sept.housing,utilities:sept.utilities,groceries:sept.groceries,runRate:b.recurringRunRate,monthly:b.monthlySavings,annual:b.annual,all:Math.round(Finance.expenses(s.transactions.flatMap(t=>t.items)).expenses*100)/100};}
export const baseline={transactions:9,items:48,bills:4,water:27,september:139.93,housing:123,utilities:123,groceries:16.93,runRate:1119,monthly:652.38,annual:7828.56,all:1524.52};
export async function validateCloud(snapshot,owner,initial=false){const state=fromCloud(snapshot,owner);await Backup.create(state,()=>null);if(initial&&Backup.canonical(metrics(state))!==Backup.canonical(baseline))throw Error('Initial cloud reconciliation differs; activation blocked');return state;}
