import {validateCloud,toCloud,diff} from './ledger-model.mjs';
import Recurring from '../recurring-utils.js';
export function repository(client,owner){
 const check=async()=>{const {data,error}=await client.auth.getUser();if(error||data?.user?.id!==owner)throw Error('Authenticate as this ledger owner before cloud access');};
 async function loadLedger(initial=false){await check();const {data,error}=await client.rpc('ledger_read');if(error)throw error;return {...data,state:await validateCloud(data,owner,initial)};}
 async function apply(op){await check();const {data,error}=await client.rpc('ledger_apply',{operation_id:op.id,expected_revision:op.revision,changes:op.changes});if(error)throw error;return data;}
 const change=(s,update)=>{const next=structuredClone(s.state);update(next);return {id:crypto.randomUUID(),revision:s.revision,changes:diff(s.rows,toCloud(next,owner,s.rows))}};
 return {loadLedger,apply,deleteTransaction:(s,id)=>change(s,n=>{n.transactions=n.transactions.filter(t=>t.id!==id)}),createTransaction:(s,t,options)=>change(s,n=>Object.assign(n,Recurring.saveTransaction(n,t,options))),updateTransaction:(s,t,options)=>change(s,n=>Object.assign(n,Recurring.saveTransaction(n,t,options))),createRecurringCharge:(s,b)=>change(s,n=>{n.recurringCharges=Recurring.upsert(n.recurringCharges,b)}),updateRecurringCharge:(s,b)=>change(s,n=>{n.recurringCharges=Recurring.upsert(n.recurringCharges,b)}),deactivateRecurringCharge:(s,id)=>change(s,n=>{n.recurringCharges=Recurring.deactivate(n.recurringCharges,id)}),recordWaterEvent:(s,event)=>change(s,n=>{const w=n.settings.waterdropPayback;w.waterdropCompletions.push({...event,gallon:w.waterdropCompletions.length+1});w.gallonsLogged=w.waterdropCompletions.length}),undoWaterEvent:(s,id)=>change(s,n=>{const w=n.settings.waterdropPayback;w.waterdropCompletions=w.waterdropCompletions.filter(e=>e.id!==id).map((e,i)=>({...e,gallon:i+1}));w.gallonsLogged=w.waterdropCompletions.length}),updateUserSettings:(s,settings)=>change(s,n=>{Object.assign(n.settings,settings)}),updateBenchmarkAdjustments:(s,adjustments)=>change(s,n=>{n.settings.joshAdjustments=adjustments})};
}
