'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createHandler,waterEvent,postEvent}=require('../alexa/index.js');
const env={ALEXA_SKILL_ID:'test-skill',ALLOWED_ALEXA_USER_ID:'test-user',FIFTY_A_VOICE_ENDPOINT:'https://example.test/api/alexa/water',FIFTY_A_VOICE_TOKEN:'t'.repeat(43)};
const request={type:'IntentRequest',requestId:'amzn1.echo-api.request.test',timestamp:'2026-09-29T12:00:00Z',intent:{name:'AddGallonIntent'}};
const envelope={context:{System:{application:{applicationId:env.ALEXA_SKILL_ID},user:{userId:env.ALLOWED_ALEXA_USER_ID}}},request};
const ok=async()=>({ok:true,json:async()=>({ok:true,request_id:request.requestId,duplicate:false})});
test('valid identity sends only request ID and canonical timestamp',()=>assert.deepEqual(waterEvent(request),{request_id:request.requestId,request_timestamp:'2026-09-29T12:00:00.000Z'}));
test('wrong skill denied before HTTP',async()=>assert.rejects(createHandler({env,fetchImpl:()=>assert.fail()})({...envelope,context:{}})));
test('missing configured skill denied',async()=>assert.rejects(createHandler({env:{...env,ALEXA_SKILL_ID:''},fetchImpl:()=>assert.fail()})(envelope)));
test('wrong user denied before HTTP',async()=>assert.match((await createHandler({env:{...env,ALLOWED_ALEXA_USER_ID:'other'},fetchImpl:()=>assert.fail()})(envelope)).response.outputSpeech.text,/private/));
test('missing allowed user fails closed',async()=>assert.match((await createHandler({env:{...env,ALLOWED_ALEXA_USER_ID:''},fetchImpl:()=>assert.fail()})(envelope)).response.outputSpeech.text,/private/));
test('valid skill and user acknowledge success',async()=>assert.equal((await createHandler({env,fetchImpl:ok})(envelope)).response.outputSpeech.text,'Added one gallon to 50-A.'));
test('duplicate acknowledges naturally',async()=>assert.equal((await createHandler({env,fetchImpl:async()=>({ok:true,json:async()=>({ok:true,request_id:request.requestId,duplicate:true})})})(envelope)).response.outputSpeech.text,'Added one gallon to 50-A.'));
test('transport uses bearer auth, exact body, redirect denial and timeout signal',async()=>{await postEvent(waterEvent(request),{env,fetchImpl:async(url,opts)=>{assert.equal(url,env.FIFTY_A_VOICE_ENDPOINT);assert.equal(opts.headers.Authorization,`Bearer ${env.FIFTY_A_VOICE_TOKEN}`);assert.deepEqual(JSON.parse(opts.body),waterEvent(request));assert.equal(opts.redirect,'error');assert(opts.signal);return ok()}})});
test('transport refuses missing config and unsafe URLs',async()=>{for(const settings of [{FIFTY_A_VOICE_TOKEN:''},{FIFTY_A_VOICE_ENDPOINT:'http://example.test/api/alexa/water'},{FIFTY_A_VOICE_ENDPOINT:'https://example.test/api/other'},{FIFTY_A_VOICE_ENDPOINT:'https://user:pass@example.test/api/alexa/water'}])await assert.rejects(postEvent(waterEvent(request),{env:{...env,...settings},fetchImpl:()=>assert.fail()}))});
test('request ID and timestamp validation retained',()=>{for(const r of [{...request,requestId:'../bad'},{...request,timestamp:'2026-02-30T00:00:00Z'},{...request,timestamp:'bad'}])assert.throws(()=>waterEvent(r))});
test('timeout never claims nothing saved or refers to Sheets',async()=>{const r=await createHandler({env,fetchImpl:async()=>{throw new DOMException('private','TimeoutError')}})(envelope);assert.equal(r.response.outputSpeech.text,"I couldn't confirm the gallon with 50-A.")});
test('unmatched acknowledgement fails honestly',async()=>{const r=await createHandler({env,fetchImpl:async()=>({ok:true,json:async()=>({ok:true,request_id:'other',duplicate:false})})})(envelope);assert.match(r.response.outputSpeech.text,/couldn't confirm/)});
test('launch/help/stop/end produce no writes',async()=>{const handler=createHandler({env,fetchImpl:()=>assert.fail()});for(const r of [{type:'LaunchRequest'},{type:'SessionEndedRequest'},{type:'IntentRequest',intent:{name:'AMAZON.HelpIntent'}},{type:'IntentRequest',intent:{name:'AMAZON.StopIntent'}}])await handler({...envelope,request:r})});
