const DB_KEY='fiftyA-ledger-v1';
let state=load();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(DB_KEY))||{budget:400,transactions:[],condition:[]}}catch{return{budget:400,transactions:[],condition:[]}}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(state));render()}
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
function totals(){let gross=0,refunds=0,avoided=0;for(const t of state.transactions){for(const i of t.items){if(i.status==='avoided'||i.status==='cancelled'){avoided+=Number(i.amount||0);continue}gross+=Number(i.amount||0);refunds+=Number(i.adjustment||0)}}return{gross,refunds,avoided,net:gross-refunds}}
function render(){const t=totals();$('#netSpend').textContent=money(t.net);$('#grossSpend').textContent=money(t.gross);$('#refunds').textContent=money(t.refunds);$('#avoided').textContent=money(t.avoided);$('#budgetCopy').textContent=`of ${money(state.budget)} target`;$('#budgetBar').style.width=Math.min(100,(t.net/state.budget)*100||0)+'%';$('#budgetInput').value=state.budget;renderTransactions();renderCondition()}
function renderTransactions(){const root=$('#transactions');if(!state.transactions.length){root.className='cards empty-state';root.textContent='No transactions yet.';return}root.className='cards';root.innerHTML='';[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).forEach(t=>{const card=document.createElement('article');card.className='transaction-card';const txTotal=t.items.reduce((s,i)=>i.status==='avoided'||i.status==='cancelled'?s:s+Number(i.amount||0)-Number(i.adjustment||0),0);card.innerHTML=`<div class="transaction-top"><div><h3>${esc(t.merchant)}</h3><div class="meta">${esc(t.date)} · net ${money(txTotal)}</div></div>${t.receipt?`<img class="receipt-thumb" src="${t.receipt}" alt="Receipt screenshot">`:''}</div>${t.items.map(i=>`<div class="item-row"><div><strong>${esc(i.name)}</strong><span class="badge ${esc(i.status)}">${esc(i.status)}</span><div class="meta">${esc(i.category)}${i.adjustment?` · refund ${money(i.adjustment)}`:''}</div></div><strong class="money">${i.status==='avoided'||i.status==='cancelled'?'avoided '+money(i.amount):money(Number(i.amount)-Number(i.adjustment||0))}</strong></div>`).join('')}${t.notes?`<div class="meta">${esc(t.notes)}</div>`:''}`;root.append(card)})}
function renderCondition(){for(const phase of ['move-in','move-out']){const root=$(phase==='move-in'?'#moveInGallery':'#moveOutGallery');const pics=state.condition.filter(x=>x.phase===phase);if(!pics.length){root.className='gallery empty-state';root.textContent=`No ${phase} photos yet.`;continue}root.className='gallery';root.innerHTML=pics.map(p=>`<article class="gallery-card"><img src="${p.data}" alt="${esc(p.room)}"><div><strong>${esc(p.room)}</strong><small>${esc(p.date)}</small>${p.notes?`<small>${esc(p.notes)}</small>`:''}</div></article>`).join('')}}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
const txDialog=$('#transactionDialog'), txForm=$('#transactionForm');$('#addTransactionBtn').onclick=()=>{txForm.reset();$('#lineItems').innerHTML='';addLine();txForm.date.value=new Date().toISOString().slice(0,10);txDialog.showModal()};$('#addLineBtn').onclick=addLine;function addLine(){const node=$('#lineItemTemplate').content.cloneNode(true);node.querySelector('.remove-line').onclick=e=>e.target.closest('.line-item').remove();$('#lineItems').append(node)}
txForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(txForm);const receipt=fd.get('receipt');const items=$$('#lineItems .line-item').map(row=>Object.fromEntries($$('[data-field]',row).map(el=>[el.dataset.field,el.value]))).filter(i=>i.name);if(!items.length)return alert('Add at least one line item.');state.transactions.push({id:crypto.randomUUID(),merchant:fd.get('merchant'),date:fd.get('date'),notes:fd.get('notes'),receipt:receipt&&receipt.size?await fileData(receipt):null,items});save();txDialog.close()});
const condDialog=$('#conditionDialog'),condForm=$('#conditionForm');$('#addConditionBtn').onclick=()=>{condForm.reset();condDialog.showModal()};condForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(condForm),files=fd.getAll('photos').filter(f=>f.size);for(const f of files)state.condition.push({id:crypto.randomUUID(),phase:fd.get('phase'),room:fd.get('room'),notes:fd.get('notes'),date:new Date().toISOString().slice(0,10),data:await fileData(f)});save();condDialog.close()});
function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
$('#saveSettingsBtn').onclick=()=>{state.budget=Number($('#budgetInput').value||0);save()};$('#clearBtn').onclick=()=>{if(confirm('Delete all local 50A Ledger data?')){state={budget:400,transactions:[],condition:[]};save()}};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='50a-ledger-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{state=JSON.parse(await f.text());save()}catch{alert('Invalid backup file')}};
$('#seedBtn').onclick=()=>{if(state.transactions.length&&!confirm('Add sample data to your existing ledger?'))return;state.transactions.push({id:crypto.randomUUID(),merchant:'Walmart',date:'2026-08-21',notes:'Initial 50A setup',receipt:null,items:[{name:'Curved shower rod',amount:'37.78',category:'Bathroom',status:'returned',adjustment:'37.78'},{name:'Soft-close toilet seat',amount:'19.94',category:'Bathroom',status:'kept',adjustment:'0'},{name:'Dinnerware + flatware',amount:'26.12',category:'Kitchen',status:'kept',adjustment:'0'}]},{id:crypto.randomUUID(),merchant:'Amazon',date:'2026-08-22',notes:'Purchase Police replacements',receipt:null,items:[{name:'TEECK tension rod',amount:'12.79',category:'Bathroom',status:'kept',adjustment:'0'},{name:'AquaDance handheld shower head',amount:'17.99',category:'Bathroom',status:'kept',adjustment:'0'},{name:'19-piece knife set',amount:'25.84',category:'Kitchen',status:'avoided',adjustment:'0'},{name:'Toaster',amount:'15.00',category:'Kitchen',status:'avoided',adjustment:'0'}]});save()};
render();
