const DB_KEY='fiftyA-ledger-v1';
const DEFAULT_SETTINGS={rent50a:965,joshRent:1450,joshAdjustments:[{label:'Cleaning fee',amount:250},{label:'Final week / Sunday move-out charge',amount:514}],joshStayDays:69,moveInDate:'2026-08-21',proratedRent:321.60,adminFee:150,depositAmount:800,depositStatus:'held',depositRefunded:0,forgottenEssentialsBudget:100,waterdropPayback:{gallonsLogged:1,baselineCostPerGallon:1.25,systemCost:73.35,breakEvenGallon:59}};
const BUCKETS=['housing_recurring','utilities','housing_one_time','groceries','refundable_deposit','excluded'];
const SETUP_CLASSES=['move_in_essential','forgotten_essential','post_move_improvement','lease_service_setup','none'];
const setupClassLabels={move_in_essential:'Move-In Essential',forgotten_essential:'Forgotten Essential',post_move_improvement:'Post-Move Improvement',lease_service_setup:'Lease / Service Setup Charge',none:'Not setup'};
const LEGACY_DEMO_CLEANUP_VERSION=2;
const ATTACHMENT_DB='50a-ledger',ATTACHMENT_STORE='attachments';
let state=load();
state=migrateRecurringSpectrumToUtility(state);
const $=s=>document.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
let editingTransactionId=null,pendingFiles=[],pendingPreviewUrls=[],existingAttachmentIds=[],removedAttachmentIds=[],activePreviewUrl=null,activeAttachmentId=null;
let activeMonth=new Date().toISOString().slice(0,7),activeMonthFilter='all';
function openAttachmentDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(ATTACHMENT_DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(ATTACHMENT_STORE)){const store=db.createObjectStore(ATTACHMENT_STORE,{keyPath:'id'});store.createIndex('transactionId','transactionId')}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function attachmentPut(attachment){const db=await openAttachmentDb();return new Promise((resolve,reject)=>{const tx=db.transaction(ATTACHMENT_STORE,'readwrite');tx.objectStore(ATTACHMENT_STORE).put(attachment);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function attachmentGet(id){const db=await openAttachmentDb();return new Promise((resolve,reject)=>{const tx=db.transaction(ATTACHMENT_STORE,'readonly');const request=tx.objectStore(ATTACHMENT_STORE).get(id);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close()})}
async function attachmentList(ids=[]){return Promise.all(ids.map(attachmentGet))}
async function attachmentDelete(id){const db=await openAttachmentDb();return new Promise((resolve,reject)=>{const tx=db.transaction(ATTACHMENT_STORE,'readwrite');tx.objectStore(ATTACHMENT_STORE).delete(id);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
function normalizeSettings(settings={}){const saved={...settings},payback={...DEFAULT_SETTINGS.waterdropPayback,...(saved.waterdropPayback||{})};if(!Array.isArray(saved.joshAdjustments)){saved.joshAdjustments=[{label:'Cleaning fee',amount:Number(saved.joshCleaning??250)},{label:'Final week / Sunday move-out charge',amount:514}]}return{...DEFAULT_SETTINGS,...saved,waterdropPayback:{gallonsLogged:Number(payback.gallonsLogged??1),baselineCostPerGallon:Number(payback.baselineCostPerGallon??1.25),systemCost:Number(payback.systemCost??73.35),breakEvenGallon:Number(payback.breakEvenGallon??59)},joshAdjustments:saved.joshAdjustments.map((a,index)=>({label:a.label||DEFAULT_SETTINGS.joshAdjustments[index]?.label||`Adjustment ${index+1}`,amount:Number(a.amount||0)})),proratedRent:Number(saved.proratedRent??DEFAULT_SETTINGS.proratedRent),adminFee:Number(saved.adminFee??DEFAULT_SETTINGS.adminFee),depositAmount:Number(saved.depositAmount??DEFAULT_SETTINGS.depositAmount),depositRefunded:Number(saved.depositRefunded??DEFAULT_SETTINGS.depositRefunded)}}
function nextMonthDate(date){if(!date)return date;const value=new Date(`${String(date).slice(0,7)}-01T00:00:00`);if(Number.isNaN(value.getTime()))return date;value.setMonth(value.getMonth()+1);return value.toISOString().slice(0,7)+'-01'}
function inferSetupClass(item){const name=String(item.name||'').toLowerCase();if(['administrative fee','spectrum activation'].includes(name))return'lease_service_setup';if(['queen mattress','shower curtain rod','shower curtain','aquadance shower head','24-piece silverware','knife set','router','dish set'].includes(name))return'move_in_essential';if(['bed/furniture non-slip pads','wet/dry dust-mop combo','dollar tree dish rack','dollar tree toilet brush','dollar tree bathroom trash can','shelf liner ×2','magnetic paper towel holder'].includes(name))return'forgotten_essential';if(['tv','tv stand','waterdrop filtration system','magnetic knife holder','front door mat','blink doorbell hanger','bedroom blackout curtains','soft-wall tension rods','soft-wall curtains'].includes(name))return'post_move_improvement';return'none'}
function normalizeTransactions(transactions=[]){const normalized=transactions.map(t=>({...t,date:t.sampleKey==='sample_50a_monthly_housing'?nextMonthDate(t.date):t.date,receipt:validImageSource(t.receipt)?t.receipt:null,attachmentIds:Array.isArray(t.attachmentIds)?t.attachmentIds.filter(Boolean):[],items:(t.items||[]).map(i=>{const inferred=inferSetupClass(i);return{...i,bucket:i.name==='Router'?'housing_one_time':i.bucket||inferBucket(i),setupClass:inferred!=='none'?inferred:(SETUP_CLASSES.includes(i.setupClass)?i.setupClass:'none'),depositStatus:i.depositStatus||'held',depositRefunded:Number(i.depositRefunded||0),moveIn:Boolean(i.moveIn),prorated:Boolean(i.prorated)}})}));const seen=new Set();return normalized.filter(t=>{if(!t.sampleKey)return true;if(seen.has(t.sampleKey))return false;seen.add(t.sampleKey);return true})}
function isKnownLegacyDemo(t){const totalCents=Math.round(t.items.reduce((sum,item)=>sum+Number(item.amount||0),0)*100),names=t.items.map(item=>String(item.name||'')).sort().join('|'),date=String(t.date||'');if(t.merchant==='Final screenshot test'&&date==='2026-08-24'&&t.items.length===1&&names==='Evidence'&&totalCents===100)return true;if(t.merchant==='Amazon'&&date==='2026-08-23'&&t.notes==='Sample one-time comfort purchase'&&names==='AquaDance handheld shower head|Desk lamp'&&totalCents===5577)return true;if(t.merchant==='50A Monthly Housing'&&date==='2026-08-23'&&t.notes==='Sample recurring housing costs'&&names==='50A rent|Electric'&&totalCents===103750)return true;if(t.merchant==='Grocery store'&&date==='2026-08-23'&&t.notes==='Tracked separately from housing'&&names==='Groceries'&&totalCents===12640)return true;return false}
function migrateLegacyDemoTransactions(saved){if(saved.legacyDemoCleanupVersion>=LEGACY_DEMO_CLEANUP_VERSION)return saved;const before=saved.transactions.length;saved.transactions=saved.transactions.filter(t=>!isKnownLegacyDemo(t));saved.legacyDemoCleanupVersion=LEGACY_DEMO_CLEANUP_VERSION;saved.legacyDemoCleanupRemoved=before-saved.transactions.length;return saved}
function migrateRecurringSpectrumToUtility(saved){saved.transactions=saved.transactions.map(t=>({...t,items:t.items.map(i=>i.name==='Spectrum monthly service'?{...i,bucket:'utilities',recurring:true}:i)}));return saved}
function canonicalTransactions(settings){return migrateRecurringSpectrumToUtility({transactions:normalizeTransactions(reconciledTransactions(settings))}).transactions}
function load(){const fallback={budget:400,settings:normalizeSettings(),transactions:[],condition:[],datasetVersion:1,legacyDemoCleanupVersion:LEGACY_DEMO_CLEANUP_VERSION};try{const saved=JSON.parse(localStorage.getItem(DB_KEY));if(!saved)return{...fallback,transactions:reconciledTransactions(fallback.settings)};saved.settings=normalizeSettings(saved.settings);saved.transactions=normalizeTransactions(saved.transactions);if(saved.datasetVersion!==1){const hadRealTransactions=saved.transactions.some(t=>!t.sampleKey&&t.systemKey!=='50a_lease_move_in');saved.transactions=saved.transactions.filter(t=>!t.sampleKey);if(!hadRealTransactions)saved.transactions.push(...reconciledTransactions(saved.settings));saved.datasetVersion=1}return{...fallback,...migrateLegacyDemoTransactions(saved)}}catch{return{...fallback,transactions:reconciledTransactions(fallback.settings)}}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(state));render()}
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const signedMoney=n=>`${Number(n||0)<0?'-':''}${money(Math.abs(Number(n||0)))}`;
const netItem=i=>i.status==='avoided'||i.status==='cancelled'||i.status==='reused'?0:Number(i.amount||0)-Number(i.adjustment||0);
const depositReturned=i=>Math.min(Number(i.amount||0),Math.max(0,Number(i.depositRefunded||0)));
const depositExpense=i=>{if(i.depositStatus==='forfeited')return Number(i.amount||0);if(i.depositStatus==='partially_refunded')return Number(i.amount||0)-depositReturned(i);return 0};
const depositHeldAmount=i=>i.depositStatus==='held'||i.depositStatus==='partially_refunded'?Number(i.amount||0)-depositReturned(i):0;
const itemHousingCost=i=>i.bucket==='refundable_deposit'?depositExpense(i):netItem(i);
function moveInTotals(){let cash=0,housing=0,held=0;for(const t of state.transactions)for(const i of t.items)if(i.moveIn){if(i.status==='avoided'||i.status==='cancelled')continue;cash+=Number(i.amount||0);housing+=itemHousingCost(i);if(i.bucket==='refundable_deposit')held+=depositHeldAmount(i)}return{cash,housing,held}}
function setupTotals(){const totals={moveInEssentials:0,forgottenEssentials:0,improvements:0,leaseServiceSetup:0,moveInEssentialsGross:0,forgottenEssentialsGross:0,improvementsGross:0,leaseServiceSetupGross:0,moveInEssentialsRefunds:0,forgottenEssentialsRefunds:0,improvementsRefunds:0,leaseServiceSetupRefunds:0};for(const t of state.transactions){for(const i of t.items){const setupClass=i.setupClass||inferSetupClass(i);if(i.status==='avoided'||i.status==='cancelled'||i.status==='reused'||!['move_in_essential','forgotten_essential','post_move_improvement','lease_service_setup'].includes(setupClass))continue;const gross=Number(i.amount||0),refund=Number(i.adjustment||0),net=Math.max(0,gross-refund);if(setupClass==='move_in_essential'){totals.moveInEssentialsGross+=gross;totals.moveInEssentialsRefunds+=refund;totals.moveInEssentials+=net}else if(setupClass==='forgotten_essential'){totals.forgottenEssentialsGross+=gross;totals.forgottenEssentialsRefunds+=refund;totals.forgottenEssentials+=net}else if(setupClass==='post_move_improvement'){totals.improvementsGross+=gross;totals.improvementsRefunds+=refund;totals.improvements+=net}else{totals.leaseServiceSetupGross+=gross;totals.leaseServiceSetupRefunds+=refund;totals.leaseServiceSetup+=net}}}if($('#forgottenEssentialsSpend')){$('#forgottenEssentialsSpend').textContent=money(totals.forgottenEssentials);$('#improvementsSpend').textContent=money(totals.improvements);$('#leaseServiceSetupSpend').textContent=money(totals.leaseServiceSetup);$('#oneTimeSetupTotal').textContent=money(totals.moveInEssentials+totals.forgottenEssentials+totals.improvements+totals.leaseServiceSetup)}return{...totals,gross:totals.moveInEssentialsGross,refunds:totals.moveInEssentialsRefunds,net:totals.moveInEssentials}}
function leaseTransaction(){return{id:crypto.randomUUID(),systemKey:'50a_lease_move_in',merchant:'50A Lease Move-In',date:state.settings.moveInDate,notes:'Lease move-in charges managed from Settings.',receipt:null,attachmentIds:[],items:[{name:'Pro-rated first rent',amount:String(state.settings.proratedRent),category:'Other',bucket:'housing_recurring',prorated:true,moveIn:true,status:'kept',adjustment:'0'},{name:'Administrative fee',amount:String(state.settings.adminFee),category:'Other',bucket:'housing_one_time',moveIn:true,status:'kept',adjustment:'0'},{name:'Security deposit',amount:String(state.settings.depositAmount),category:'Other',bucket:'refundable_deposit',depositStatus:state.settings.depositStatus,depositRefunded:String(state.settings.depositRefunded),moveIn:true,status:'kept',adjustment:'0'}]}}
function upsertLeaseTransaction(){const next=leaseTransaction(),existing=state.transactions.find(t=>t.systemKey==='50a_lease_move_in');if(existing){next.id=existing.id;next.attachmentIds=existing.attachmentIds||[];state.transactions=state.transactions.map(t=>t.systemKey==='50a_lease_move_in'?{...t,...next}:t)}else state.transactions.push(next)}
function inferBucket(i){const text=`${i.name||''} ${i.category||''}`.toLowerCase();if(text.includes('grocer')||text.includes('food')||text.includes('drink'))return'groceries';if(text.includes('electric')||text.includes('water')||text.includes('sewer')||text.includes('utility'))return'utilities';if(i.name==='Spectrum monthly service'||i.category==='Internet'&&i.recurring)return'utilities';if(text.includes('rent'))return'housing_recurring';if(i.status==='avoided'||i.status==='cancelled')return'excluded';if(['Kitchen','Bathroom','Furniture','Cleaning','Security'].includes(i.category))return'housing_one_time';return'excluded'}
function monthItems(month){return state.transactions.filter(t=>String(t.date||'').slice(0,7)===month).flatMap(t=>t.items.map(item=>({...item,transactionId:t.id,merchant:t.merchant,date:t.date,transaction:t})))}
function expenseTotalsForMonth(month){const totals={expenses:0,housing_recurring:0,utilities:0,housing_one_time:0,groceries:0,other:0,refunds:0,avoided:0};for(const i of monthItems(month)){const bucket=BUCKETS.includes(i.bucket)?i.bucket:inferBucket(i);if(i.status==='avoided'||i.status==='cancelled'){totals.avoided+=Number(i.amount||0);continue}const net=bucket==='refundable_deposit'?depositExpense(i):netItem(i);totals.refunds+=Number(i.adjustment||0);if(bucket==='housing_recurring')totals.housing_recurring+=net;else if(bucket==='utilities')totals.utilities+=net;else if(bucket==='housing_one_time'||bucket==='refundable_deposit'&&net>0)totals.housing_one_time+=net;else if(bucket==='groceries')totals.groceries+=net;else totals.other+=net;totals.expenses+=net}return{...totals,housing:totals.housing_recurring+totals.utilities+totals.housing_one_time}}
const categoryLabels={all:'All expenses',housing:'Housing',utilities:'Utilities',setup:'Household/setup',groceries:'Groceries',other:'Excluded/other'};
function categoryMatches(bucket,category){return category==='all'?['housing_recurring','utilities','housing_one_time','groceries','excluded'].includes(bucket):category==='housing'?bucket==='housing_recurring':category==='utilities'?bucket==='utilities':category==='setup'?bucket==='housing_one_time':category==='groceries'?bucket==='groceries':category==='other'?bucket==='excluded':false}
function getCategoryTotals(category='all',options={}){const transactions=options.month?state.transactions.filter(t=>String(t.date||'').slice(0,7)===options.month):state.transactions;const totals={gross:0,refunds:0,net:0,transactionCount:0};for(const t of transactions){let matched=false;for(const raw of t.items){const bucket=BUCKETS.includes(raw.bucket)?raw.bucket:inferBucket(raw);if(!categoryMatches(bucket,category)||raw.status==='avoided'||raw.status==='cancelled'||raw.status==='reused')continue;const deposit=bucket==='refundable_deposit';const retained=deposit?depositExpense(raw):null;if(deposit&&!retained)continue;const gross=deposit?retained:Number(raw.amount||0);const refund=deposit?0:Number(raw.adjustment||0);totals.gross+=gross;totals.refunds+=refund;totals.net+=Math.max(0,gross-refund);matched=true}if(matched)totals.transactionCount++}return totals}
function benchmarkTotalsForMonth(month){const sums=expenseTotalsForMonth(month),items=monthItems(month),recurringExtras=items.filter(i=>{const bucket=BUCKETS.includes(i.bucket)?i.bucket:inferBucket(i);return bucket==='housing_recurring'&&!i.prorated&&!String(i.name||'').toLowerCase().includes('rent')}).reduce((sum,i)=>sum+itemHousingCost(i),0);const housing=sums.housing;const recurringRunRate=Number(state.settings.rent50a||0)+recurringExtras+sums.utilities;const adjustmentTotal=state.settings.joshAdjustments.reduce((sum,adjustment)=>sum+Number(adjustment.amount||0),0);const benchmark=Number(state.settings.joshRent||0)+adjustmentTotal/(Math.max(1,Number(state.settings.joshStayDays||1))/30.4375);return{...sums,recurringRunRate,adjustmentTotal,benchmark,difference:benchmark-housing,monthlySavings:benchmark-recurringRunRate}}
function benchmarkTotals(){const b=benchmarkTotalsForMonth(new Date().toISOString().slice(0,7));const months=[...new Set(state.transactions.map(t=>String(t.date||'').slice(0,7)).filter(Boolean))];const cumulative=months.reduce((sum,month)=>sum+benchmarkTotalsForMonth(month).monthlySavings,0);return{...b,cumulative,annual:b.monthlySavings*12}}
function totals(){let gross=0,refunds=0,avoided=0;for(const t of state.transactions){for(const i of t.items){if(i.status==='avoided'||i.status==='cancelled'){avoided+=Number(i.amount||0);continue}if(i.status==='reused')continue;gross+=Number(i.amount||0);refunds+=Number(i.adjustment||0)}}return{gross,refunds,avoided,net:gross-refunds}}
function syncDepositSettingControl(){const status=$('#depositStatusInput').value;const enabled=status==='partially_refunded'||status==='refunded';$('#depositRefundedInput').disabled=!enabled;$('#depositRefundedSettingLabel').classList.toggle('line-field-hidden',!enabled)}
function render(){const t=totals(),setup=setupTotals(),moveIn=moveInTotals(),current=expenseTotalsForMonth(new Date().toISOString().slice(0,7)),payback=state.settings.waterdropPayback;$('#monthlyExpenses').textContent=money(current.expenses);$('#monthlyHousing').textContent=money(current.housing);$('#monthlyGroceries').textContent=money(current.groceries);$('#avoided').textContent=money(t.avoided);$('#netSpend').textContent=money(setup.net);$('#budgetCopy').textContent=`of ${money(state.budget)} setup target`;$('#budgetBar').style.width=Math.min(100,(setup.net/state.budget)*100||0)+'%';$('#moveInCashOutflow').textContent=money(moveIn.cash);$('#moveInHousingCost').textContent=money(moveIn.housing);$('#depositHeld').textContent=money(moveIn.held);$('#budgetInput').value=state.budget;$('#rent50aInput').value=state.settings.rent50a;$('#joshRentInput').value=state.settings.joshRent;$('#joshCleaningInput').value=state.settings.joshAdjustments[0]?.amount||0;$('#joshMoveOutInput').value=state.settings.joshAdjustments[1]?.amount||0;$('#joshDaysInput').value=state.settings.joshStayDays;$('#moveInDateInput').value=state.settings.moveInDate;$('#proratedRentInput').value=state.settings.proratedRent;$('#adminFeeInput').value=state.settings.adminFee;$('#depositAmountInput').value=state.settings.depositAmount;$('#depositStatusInput').value=state.settings.depositStatus;$('#depositRefundedInput').value=state.settings.depositRefunded;$('#waterdropGallonsInput').value=payback.gallonsLogged;$('#waterdropBaselineInput').value=payback.baselineCostPerGallon;$('#waterdropSystemCostInput').value=payback.systemCost;$('#waterdropBreakEvenInput').value=payback.breakEvenGallon;$('#waterdropPaybackSummary').textContent=`${payback.gallonsLogged} gallon logged · ${money(payback.gallonsLogged*payback.baselineCostPerGallon)} avoided · break-even at gallon ${payback.breakEvenGallon}`;syncDepositSettingControl();$('#seedBtn').textContent=state.datasetVersion===1?'Reload reconciled data':'Load reconciled data';renderBenchmark();renderMonthly();renderSetupTransactions();renderCondition()}
function validImageSource(source){return typeof source==='string'&&source.trim()&&/^(data:image\/|blob:|https?:\/\/|\/|\.\.?\/)/i.test(source.trim())}
function renderBenchmark(){const b=benchmarkTotals();$('#housingTotal').textContent=money(b.housing);$('#joshBenchmark').textContent=money(b.benchmark);$('#recurringHousing').textContent=money(b.recurringRunRate);$('#oneTimeHousing').textContent=money(b.housing_one_time);$('#utilities').textContent=money(b.utilities);$('#groceries').textContent=money(b.groceries);$('#benchmarkDifference').textContent=signedMoney(b.difference);$('#benchmarkDifference').className=b.difference>=0?'positive':'negative';$('#benchmarkDifferenceLabel').textContent=b.difference>=0?'saved / headroom this month':'over benchmark this month';$('#benchmarkSummary').textContent=b.difference>=0?`50A is ${money(b.difference)} below Josh's effective monthly cost.`:`50A is ${money(Math.abs(b.difference))} above Josh's effective monthly cost.`;$('#joshFormula').textContent=`${money(state.settings.joshRent)} rent + ${state.settings.joshAdjustments.map(a=>`${money(a.amount)} ${a.label.toLowerCase()}`).join(' + ')} ÷ ${state.settings.joshStayDays} days × 30.4375`;$('#monthlySavings').textContent=signedMoney(b.monthlySavings);$('#cumulativeSavings').textContent=signedMoney(b.cumulative);$('#annualSavings').textContent=signedMoney(b.annual)}
async function renderTransactions(rootSelector='#transactions',transactions=state.transactions){const root=$(rootSelector);if(!root)return;root.querySelectorAll('[data-preview-url]').forEach(image=>URL.revokeObjectURL(image.dataset.previewUrl));if(!transactions.length){root.className='cards empty-state';root.textContent=rootSelector==='#setupTransactions'?'No setup transactions yet.':rootSelector==='#monthlyTransactions'?'No transactions for this month.':'No transactions yet.';return}root.className='cards';root.innerHTML='';[...transactions].sort((a,b)=>b.date.localeCompare(a.date)).forEach(async t=>{const card=document.createElement('article');card.className='transaction-card';const txTotal=t.items.reduce((s,i)=>s+netItem(i),0);const ids=t.attachmentIds||[];const managed=t.systemKey==='50a_lease_move_in';card.innerHTML=`<div class="transaction-top"><div><h3>${esc(t.merchant)}</h3><div class="meta">${esc(t.date)} · net ${money(txTotal)}${ids.length?` · ${ids.length} screenshot${ids.length===1?'':'s'}`:''}</div></div><div class="transaction-actions">${managed?'<small class="managed-note">Managed in Settings</small>':`<button type="button" class="ghost compact" data-edit-id="${esc(t.id)}">Edit</button>`}${validImageSource(t.receipt)?`<img class="receipt-thumb legacy-receipt" src="${t.receipt}" alt="Legacy receipt screenshot">`:''}</div></div>${t.items.map(i=>`<div class="item-row"><div><strong>${esc(i.name)}</strong><span class="badge ${esc(i.status)}">${esc(i.status)}</span><div class="meta">${esc(i.category)} · ${esc(i.bucket||inferBucket(i))}${i.bucket==='refundable_deposit'?` · ${esc(i.depositStatus||'held')}${depositReturned(i)?` · returned ${money(depositReturned(i))}`:''}`:''}${i.prorated?' · prorated / one period':''}${i.moveIn?' · move-in':''}${i.adjustment?` · refund ${money(i.adjustment)}`:''}</div></div><strong class="money">${i.status==='avoided'||i.status==='cancelled'?'avoided '+money(i.amount):money(netItem(i))}</strong></div>`).join('')}${t.notes?`<div class="meta">${esc(t.notes)}</div>`:''}<div class="attachment-gallery" data-attachment-gallery="${esc(t.id)}"></div>`;root.append(card);if(ids.length){const gallery=card.querySelector('[data-attachment-gallery]');const attachments=await attachmentList(ids);attachments.filter(Boolean).forEach(attachment=>{const image=document.createElement('img');image.className='attachment-thumb';image.alt=attachment.fileName;image.title=attachment.fileName;image.src=URL.createObjectURL(attachment.blob);image.dataset.previewUrl=image.src;image.dataset.attachmentId=attachment.id;gallery.append(image)})}})}
function renderSetupTransactions(){const setup=state.transactions.map(t=>({...t,items:t.items.filter(i=>i.moveIn||i.bucket==='housing_one_time')})).filter(t=>t.items.length);renderTransactions('#setupTransactions',setup)}
function filterMonthTransactions(){const monthTx=state.transactions.map(t=>({...t,items:t.items.filter(i=>{const bucket=BUCKETS.includes(i.bucket)?i.bucket:inferBucket(i);return activeMonthFilter==='all'||(activeMonthFilter==='housing'&&bucket==='housing_recurring')||(activeMonthFilter==='utilities'&&bucket==='utilities')||(activeMonthFilter==='setup'&&bucket==='housing_one_time')||(activeMonthFilter==='groceries'&&bucket==='groceries')||(activeMonthFilter==='other'&&(bucket==='excluded'||bucket==='refundable_deposit'))})})).filter(t=>String(t.date||'').slice(0,7)===activeMonth&&t.items.length);renderTransactions('#monthlyTransactions',monthTx)}
function formatMonth(month){return new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date(`${month}-01T00:00:00`))}
function renderCategorySummary(){const totals=getCategoryTotals(activeMonthFilter,{month:activeMonth}),allTime=getCategoryTotals(activeMonthFilter);$('#categorySummaryTitle').textContent=`${categoryLabels[activeMonthFilter]} — ${formatMonth(activeMonth)}`;$('#categorySummaryScope').textContent='Selected month spending';$('#categoryAllTimeContext').textContent=`All-time ${categoryLabels[activeMonthFilter]}: ${money(allTime.net)}`;$('#categoryNetSpent').textContent=money(totals.net);$('#categoryGrossPurchases').textContent=money(totals.gross);$('#categoryRefunds').textContent=money(totals.refunds)}
function renderMonthly(){const b=benchmarkTotalsForMonth(activeMonth),input=$('#monthInput');if(input)input.value=activeMonth;$('#selectedExpenses').textContent=money(b.expenses);$('#selectedHousing').textContent=money(b.housing_recurring);$('#selectedUtilities').textContent=money(b.utilities);$('#selectedOneTime').textContent=money(b.housing_one_time);$('#selectedGroceries').textContent=money(b.groceries);$('#selectedOther').textContent=money(b.other);$('#selectedComparison').textContent=`50A housing cost: ${money(b.housing)} · Josh: ${money(b.benchmark)}`;$('#selectedComparisonDifference').textContent=`${money(Math.abs(b.difference))} ${b.difference>=0?'under':'over'} Josh`;renderCategorySummary();filterMonthTransactions()}
function renderCondition(){for(const phase of ['move-in','move-out']){const root=$(phase==='move-in'?'#moveInGallery':'#moveOutGallery');const pics=state.condition.filter(x=>x.phase===phase);if(!pics.length){root.className='gallery empty-state';root.textContent=`No ${phase} photos yet.`;continue}root.className='gallery';root.innerHTML=pics.map(p=>`<article class="gallery-card"><img src="${p.data}" alt="${esc(p.room)}"><div><strong>${esc(p.room)}</strong><small>${esc(p.date)}</small>${p.notes?`<small>${esc(p.notes)}</small>`:''}</div></article>`).join('')}}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='monthly')renderMonthly()});
$('#monthInput').onchange=e=>{activeMonth=e.target.value||new Date().toISOString().slice(0,7);renderMonthly()};function shiftMonth(delta){const date=new Date(`${activeMonth}-01T00:00:00`);date.setMonth(date.getMonth()+delta);activeMonth=date.toISOString().slice(0,7);renderMonthly()}$('#previousMonthBtn').onclick=()=>shiftMonth(-1);$('#nextMonthBtn').onclick=()=>shiftMonth(1);$$('[data-month-filter]').forEach(button=>button.onclick=()=>{$$('[data-month-filter]').forEach(item=>item.classList.remove('active'));button.classList.add('active');activeMonthFilter=button.dataset.monthFilter;renderMonthly()});
const txDialog=$('#transactionDialog'),txForm=$('#transactionForm'),screenshotInput=$('#screenshotInput');
function clearPreviewUrls(){pendingPreviewUrls.forEach(url=>URL.revokeObjectURL(url));pendingPreviewUrls=[]}
function resetAttachmentDraft(){clearPreviewUrls();pendingFiles=[];existingAttachmentIds=[];removedAttachmentIds=[];$('#attachmentPreview').innerHTML=''}
function dismissTransactionDialog(){resetAttachmentDraft();editingTransactionId=null;txDialog.close()}
function renderAttachmentDraft(){const root=$('#attachmentPreview');root.innerHTML='';pendingFiles.forEach((file,index)=>{const wrapper=document.createElement('div');wrapper.className='draft-attachment';const image=document.createElement('img');image.src=pendingPreviewUrls[index];image.alt=file.name;const remove=document.createElement('button');remove.type='button';remove.className='icon-btn';remove.textContent='×';remove.setAttribute('aria-label',`Remove ${file.name}`);remove.onclick=()=>{pendingFiles.splice(index,1);pendingPreviewUrls.splice(index,1);URL.revokeObjectURL(image.src);renderAttachmentDraft()};wrapper.append(image,remove);root.append(wrapper)});existingAttachmentIds.forEach(id=>{const wrapper=document.createElement('div');wrapper.className='draft-attachment existing-attachment';wrapper.dataset.attachmentId=id;const image=document.createElement('img');image.alt='Existing screenshot';attachmentGet(id).then(attachment=>{if(attachment){image.src=URL.createObjectURL(attachment.blob);image.dataset.previewUrl=image.src}});const remove=document.createElement('button');remove.type='button';remove.className='icon-btn';remove.textContent='×';remove.setAttribute('aria-label','Remove existing screenshot');remove.onclick=()=>{removedAttachmentIds.push(id);existingAttachmentIds=existingAttachmentIds.filter(existingId=>existingId!==id);renderAttachmentDraft()};wrapper.append(image,remove);root.append(wrapper)})}
function openNewTransaction(){editingTransactionId=null;txForm.reset();resetAttachmentDraft();$('#lineItems').innerHTML='';addLine();txForm.date.value=new Date().toISOString().slice(0,10);txDialog.querySelector('.eyebrow').textContent='NEW PURCHASE';txDialog.querySelector('h2').textContent='Add transaction';txDialog.querySelector('[value="default"]').textContent='Save transaction';txDialog.showModal()}
$('#addTransactionBtn').onclick=openNewTransaction;$('#addLineBtn').onclick=()=>addLine();function syncLineItemControls(row){const bucket=row.querySelector('[data-field="bucket"]')?.value;const deposit=bucket==='refundable_deposit';row.querySelector('[data-field="depositStatus"]')?.classList.toggle('line-field-hidden',!deposit);row.querySelector('[data-field="depositRefunded"]')?.classList.toggle('line-field-hidden',!deposit);row.querySelector('[data-field="adjustment"]')?.classList.toggle('line-field-hidden',deposit);row.querySelector('[data-field="period"]')?.classList.toggle('line-field-hidden',bucket!=='housing_recurring');row.querySelector('[data-field="timing"]')?.classList.toggle('line-field-hidden',bucket!=='housing_recurring'&&bucket!=='housing_one_time'&&bucket!=='refundable_deposit'&&bucket!=='utilities');row.querySelector('[data-field="setupClass"]')?.classList.toggle('line-field-hidden',bucket!=='housing_one_time')}
function addLine(item={}){const node=$('#lineItemTemplate').content.cloneNode(true);$$('[data-field]',node).forEach(input=>{const field=input.dataset.field;const value=field==='period'?(item.prorated?'prorated':'monthly'):field==='timing'?(item.moveIn?'move_in':'regular'):item[field]??(field==='status'?'kept':field==='bucket'?'housing_one_time':field==='depositStatus'?'held':field==='depositRefunded'?'0':'');input.value=value});const row=node.querySelector('.line-item');row.querySelector('[data-field="bucket"]').addEventListener('change',()=>syncLineItemControls(row));row.querySelector('.remove-line').onclick=e=>e.target.closest('.line-item').remove();$('#lineItems').append(node);syncLineItemControls($('#lineItems .line-item:last-child'))}
function collectItems(){return $$('#lineItems .line-item').map(row=>{const item=Object.fromEntries($$('[data-field]',row).map(el=>[el.dataset.field,el.value]));item.prorated=item.period==='prorated';item.moveIn=item.timing==='move_in';if(item.setupClass==='none'&&item.bucket==='housing_one_time')item.setupClass=inferSetupClass(item);delete item.period;delete item.timing;return item}).filter(item=>item.name)}
screenshotInput.onchange=()=>{const files=[...screenshotInput.files].filter(file=>/^image\/(jpeg|png|webp)$/.test(file.type));pendingFiles.push(...files);pendingPreviewUrls.push(...files.map(file=>URL.createObjectURL(file)));renderAttachmentDraft();screenshotInput.value=''};
async function openEditTransaction(id){const transaction=state.transactions.find(item=>item.id===id);if(!transaction)return;editingTransactionId=id;txForm.reset();resetAttachmentDraft();txForm.merchant.value=transaction.merchant;txForm.date.value=transaction.date;txForm.notes.value=transaction.notes||'';existingAttachmentIds=[...(transaction.attachmentIds||[])];$('#lineItems').innerHTML='';transaction.items.forEach(item=>addLine(item));renderAttachmentDraft();txDialog.querySelector('.eyebrow').textContent='EDIT TRANSACTION';txDialog.querySelector('h2').textContent='Edit transaction';txDialog.querySelector('[value="default"]').textContent='Save changes';txDialog.showModal()}
txForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(txForm),items=collectItems();if(!items.length)return alert('Add at least one line item.');const id=editingTransactionId||crypto.randomUUID();const previous=state.transactions.find(transaction=>transaction.id===id);const attachmentIds=[...existingAttachmentIds];for(const file of pendingFiles){const attachmentId=crypto.randomUUID();await attachmentPut({id:attachmentId,transactionId:id,fileName:file.name,mimeType:file.type,createdAt:new Date().toISOString(),blob:file});attachmentIds.push(attachmentId)}for(const attachmentId of removedAttachmentIds)await attachmentDelete(attachmentId);const next={id,merchant:fd.get('merchant'),date:fd.get('date'),notes:fd.get('notes'),items,attachmentIds};if(previous){state.transactions=state.transactions.map(transaction=>transaction.id===id?{...transaction,...next}:transaction)}else state.transactions.push(next);save();resetAttachmentDraft();txDialog.close()});
txDialog.addEventListener('close',()=>{resetAttachmentDraft();editingTransactionId=null});
txDialog.addEventListener('cancel',event=>{event.preventDefault();dismissTransactionDialog()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&txDialog.open){event.preventDefault();dismissTransactionDialog()}});
$$('[data-dialog-dismiss="transactionDialog"]').forEach(button=>button.onclick=dismissTransactionDialog);
document.addEventListener('click',async event=>{const settingsButton=event.target.closest('[data-open-settings]');if(settingsButton){$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));$('.tab[data-tab="settings"]').classList.add('active');$('#settings').classList.add('active');return}const edit=event.target.closest('[data-edit-id]');if(edit){openEditTransaction(edit.dataset.editId);return}const image=event.target.closest('.attachment-thumb,.legacy-receipt');if(image){const source=image.dataset.previewUrl||image.src;if(!validImageSource(source))return;const dialog=$('#imagePreviewDialog'),preview=$('#imagePreview');activePreviewUrl=null;activeAttachmentId=image.dataset.attachmentId||null;preview.src=source;dialog.hidden=false;dialog.showModal()}});
function clearImagePreview(){const dialog=$('#imagePreviewDialog'),preview=$('#imagePreview');if(activePreviewUrl&&activePreviewUrl!==preview.src)URL.revokeObjectURL(activePreviewUrl);activePreviewUrl=null;activeAttachmentId=null;preview.removeAttribute('src');dialog.hidden=true}
function closeImagePreview(){const dialog=$('#imagePreviewDialog');clearImagePreview();if(dialog.open)dialog.close()}
$('#closeImagePreviewBtn').onclick=closeImagePreview;$('#imagePreviewDialog').addEventListener('close',clearImagePreview);
$('#imagePreviewDialog').addEventListener('cancel',event=>{event.preventDefault();closeImagePreview()});
const condDialog=$('#conditionDialog'),condForm=$('#conditionForm');$('#addConditionBtn').onclick=()=>{condForm.reset();condDialog.showModal()};$$('[data-dialog-dismiss="conditionDialog"]').forEach(button=>button.onclick=()=>condDialog.close());condDialog.addEventListener('cancel',event=>{event.preventDefault();condDialog.close()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&condDialog.open){event.preventDefault();condDialog.close()}});condForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(condForm),files=fd.getAll('photos').filter(f=>f.size);for(const f of files)state.condition.push({id:crypto.randomUUID(),phase:fd.get('phase'),room:fd.get('room'),notes:fd.get('notes'),date:new Date().toISOString().slice(0,10),data:await fileData(f)});save();condDialog.close()});
function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
const settingInputs={rent50a:$('#rent50aInput'),joshRent:$('#joshRentInput'),joshCleaning:$('#joshCleaningInput'),joshMoveOut:$('#joshMoveOutInput'),joshStayDays:$('#joshDaysInput')},leaseInputs={moveInDate:$('#moveInDateInput'),proratedRent:$('#proratedRentInput'),adminFee:$('#adminFeeInput'),depositAmount:$('#depositAmountInput'),depositStatus:$('#depositStatusInput'),depositRefunded:$('#depositRefundedInput')},paybackInputs={gallonsLogged:$('#waterdropGallonsInput'),baselineCostPerGallon:$('#waterdropBaselineInput'),systemCost:$('#waterdropSystemCostInput'),breakEvenGallon:$('#waterdropBreakEvenInput')};function syncSettingsFromInputs(){state.settings.rent50a=Number(settingInputs.rent50a.value||0);state.settings.joshRent=Number(settingInputs.joshRent.value||0);state.settings.joshAdjustments=[{label:'Cleaning fee',amount:Number(settingInputs.joshCleaning.value||0)},{label:'Final week / Sunday move-out charge',amount:Number(settingInputs.joshMoveOut.value||0)}];state.settings.joshStayDays=Number(settingInputs.joshStayDays.value||0);state.settings.moveInDate=leaseInputs.moveInDate.value||DEFAULT_SETTINGS.moveInDate;state.settings.proratedRent=Number(leaseInputs.proratedRent.value||0);state.settings.adminFee=Number(leaseInputs.adminFee.value||0);state.settings.depositAmount=Number(leaseInputs.depositAmount.value||0);state.settings.depositStatus=leaseInputs.depositStatus.value;state.settings.depositRefunded=Number(leaseInputs.depositRefunded.value||0);state.settings.waterdropPayback={gallonsLogged:Number(paybackInputs.gallonsLogged.value||0),baselineCostPerGallon:Number(paybackInputs.baselineCostPerGallon.value||0),systemCost:Number(paybackInputs.systemCost.value||0),breakEvenGallon:Number(paybackInputs.breakEvenGallon.value||0)}}Object.values(settingInputs).forEach(input=>input.addEventListener('input',()=>{syncSettingsFromInputs();renderBenchmark()}));Object.values(paybackInputs).forEach(input=>input.addEventListener('input',()=>{syncSettingsFromInputs();render()}));leaseInputs.depositStatus.addEventListener('change',syncDepositSettingControl);$('#saveSettingsBtn').onclick=()=>{state.budget=Number($('#budgetInput').value||0);syncSettingsFromInputs();upsertLeaseTransaction();localStorage.setItem(DB_KEY,JSON.stringify(state));render()};$('#clearBtn').onclick=()=>{if(confirm('Delete all local 50A Ledger data?')){state={budget:400,settings:normalizeSettings(),transactions:[],condition:[],datasetVersion:1};save()}};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='50a-ledger-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{state=JSON.parse(await f.text());state.settings=normalizeSettings(state.settings);state.transactions=normalizeTransactions(state.transactions);save()}catch{alert('Invalid backup file')}};
const nextMonthKey=month=>{const date=new Date(`${month}-01T00:00:00`);date.setMonth(date.getMonth()+1);return date.toISOString().slice(0,7)+'-01'};
function reconciledTransactions(settings){const date=settings.moveInDate,groceriesDate='2026-08-26',item=(name,amount,category,extra={})=>({name,amount:String(amount),category,status:extra.status||'kept',adjustment:'0',...extra,bucket:name==='Router'?'housing_one_time':extra.bucket||'housing_one_time'});return[
  {id:crypto.randomUUID(),sampleKey:'reconciled_setup',merchant:'Reconciled 50A setup',date,notes:'Canonical room-by-room sweep of new 50A purchases. Estimated Dollar Tree and router/dish-set amounts are marked on their line items.',receipt:null,items:[
    item('Queen mattress',143.45,'Furniture',{giftCardOffset:53.64}),item('TV',229,'Other'),item('TV stand',40.39,'Furniture'),item('Waterdrop filtration system',73.35,'Kitchen'),item('Magnetic knife holder',17.73,'Kitchen'),item('Shower curtain rod',14,'Bathroom'),item('Shower curtain',18.60,'Bathroom'),item('AquaDance shower head',19.70,'Bathroom'),item('Front door mat',10.28,'Other'),item('Blink doorbell hanger',10.94,'Security'),item('Magnetic paper towel holder',7.65,'Kitchen'),item('24-piece silverware',14.22,'Kitchen'),item('Knife set',10.94,'Kitchen'),item('Bedroom blackout curtains',15.95,'Furniture'),item('Bed/furniture non-slip pads',13.13,'Furniture'),item('Wet/dry dust-mop combo',12.46,'Cleaning'),item('Soft-wall tension rods',9.84,'Other'),item('Soft-wall curtains',15.32,'Other'),item('Dollar Tree dish rack',1.61,'Kitchen',{estimated:true}),item('Dollar Tree toilet brush',1.61,'Bathroom',{estimated:true}),item('Dollar Tree bathroom trash can',1.61,'Bathroom',{estimated:true}),item('Shelf liner ×2',2.68,'Other',{estimated:true}),item('Router',34.22,'Other',{estimated:true,bucket:'housing_one_time'}),item('Dish set',14.85,'Kitchen',{estimated:true}),item('Spectrum activation',20,'Internet',{bucket:'housing_one_time'}),item('Spectrum monthly service',40,'Internet',{bucket:'housing_recurring',recurring:true})]},
  {id:crypto.randomUUID(),sampleKey:'reconciled_groceries_1',merchant:'Groceries',date,notes:'First 50A grocery run; amount reconciled from the physical ledger.',receipt:null,items:[item('Groceries',31.28,'Groceries',{bucket:'groceries'})]},
  {id:crypto.randomUUID(),sampleKey:'reconciled_groceries_2',merchant:'Groceries',date:groceriesDate,notes:'Aug. 26 grocery run.',receipt:null,items:[item('Groceries',39.13,'Groceries',{bucket:'groceries'})]},
  {id:crypto.randomUUID(),sampleKey:'reconciled_zero_dollar',merchant:'Reused / avoided / returned',date,notes:'Tracked for decision history only; all records are net $0 because they were already owned, avoided, or returned.',receipt:null,items:[
    item('Queen box spring and frame',0,'Furniture',{bucket:'excluded',status:'reused'}),item('Cups',0,'Kitchen',{bucket:'excluded',status:'reused'}),item('Broom / dustpan',0,'Cleaning',{bucket:'excluded',status:'avoided'}),item('Blink cameras',0,'Security',{bucket:'excluded',status:'reused'}),item('Household trash can',0,'Other',{bucket:'excluded',status:'avoided'}),item('Bedroom curtain rods',0,'Furniture',{bucket:'excluded',status:'avoided'}),item('Bedside furniture',0,'Furniture',{bucket:'excluded',status:'avoided'}),item('Fire Stick',0,'Other',{bucket:'excluded',status:'reused'}),item('Ethernet adapter',0,'Other',{bucket:'excluded',status:'reused'}),item('Air fryer replacing toaster',0,'Kitchen',{bucket:'excluded',status:'avoided'}),item('Cot / totes as furniture',0,'Furniture',{bucket:'excluded',status:'reused'}),item('Toilet seat',0,'Bathroom',{bucket:'excluded',status:'returned'}),item('Curved shower rod',0,'Bathroom',{bucket:'excluded',status:'returned'})]}
].map(t=>({...t,attachmentIds:[],items:t.items.map(item=>({...item,setupClass:item.setupClass||inferSetupClass(item)}))}))}
$('#seedBtn').onclick=()=>{state.transactions=state.transactions.filter(t=>!t.sampleKey);state.transactions.push(...canonicalTransactions(state.settings));state.datasetVersion=1;save()};
function annotateSetupCards(){const root=$('#setupTransactions');if(!root)return;root.querySelectorAll('.item-row').forEach(row=>{const name=row.querySelector('strong')?.textContent,meta=row.querySelector('.meta'),setupClass=inferSetupClass({name});if(meta&&setupClass!=='none'&&!meta.textContent.includes(setupClassLabels[setupClass]))meta.textContent+=` · ${setupClassLabels[setupClass]}`})}
const renderWithClarifiedBenchmark=render;render=()=>{renderWithClarifiedBenchmark();$('#budgetCopy').textContent=`of ${money(state.budget)} lifetime Move-In Essentials target`;$('#benchmarkDifferenceLabel').textContent='actual housing headroom vs Josh this month';$('#annualSavings').nextElementSibling.textContent='known run-rate × 12; internet recorded; electric/water not yet recorded';setTimeout(annotateSetupCards,0)};
upsertLeaseTransaction();localStorage.setItem(DB_KEY,JSON.stringify(state));render();
