const DB_KEY='fiftyA-ledger-v1';
const DEFAULT_SETTINGS={rent50a:965,joshRent:1450,joshAdjustments:[{label:'Cleaning fee',amount:250},{label:'Final week / Sunday move-out charge',amount:514}],joshStayDays:69,moveInDate:'2026-08-21',proratedRent:321.60,adminFee:150,depositAmount:800,depositStatus:'held',depositRefunded:0};
const BUCKETS=['housing_recurring','utilities','housing_one_time','groceries','refundable_deposit','excluded'];
const ATTACHMENT_DB='50a-ledger',ATTACHMENT_STORE='attachments';
let state=load();
const $=s=>document.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
let editingTransactionId=null,pendingFiles=[],pendingPreviewUrls=[],existingAttachmentIds=[],removedAttachmentIds=[],activePreviewUrl=null,activeAttachmentId=null;
function openAttachmentDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(ATTACHMENT_DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(ATTACHMENT_STORE)){const store=db.createObjectStore(ATTACHMENT_STORE,{keyPath:'id'});store.createIndex('transactionId','transactionId')}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function attachmentPut(attachment){const db=await openAttachmentDb();return new Promise((resolve,reject)=>{const tx=db.transaction(ATTACHMENT_STORE,'readwrite');tx.objectStore(ATTACHMENT_STORE).put(attachment);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function attachmentGet(id){const db=await openAttachmentDb();return new Promise((resolve,reject)=>{const tx=db.transaction(ATTACHMENT_STORE,'readonly');const request=tx.objectStore(ATTACHMENT_STORE).get(id);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close()})}
async function attachmentList(ids=[]){return Promise.all(ids.map(attachmentGet))}
async function attachmentDelete(id){const db=await openAttachmentDb();return new Promise((resolve,reject)=>{const tx=db.transaction(ATTACHMENT_STORE,'readwrite');tx.objectStore(ATTACHMENT_STORE).delete(id);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
function normalizeSettings(settings={}){const saved={...settings};if(!Array.isArray(saved.joshAdjustments)){saved.joshAdjustments=[{label:'Cleaning fee',amount:Number(saved.joshCleaning??250)},{label:'Final week / Sunday move-out charge',amount:514}]}return{...DEFAULT_SETTINGS,...saved,joshAdjustments:saved.joshAdjustments.map((a,index)=>({label:a.label||DEFAULT_SETTINGS.joshAdjustments[index]?.label||`Adjustment ${index+1}`,amount:Number(a.amount||0)})),proratedRent:Number(saved.proratedRent??DEFAULT_SETTINGS.proratedRent),adminFee:Number(saved.adminFee??DEFAULT_SETTINGS.adminFee),depositAmount:Number(saved.depositAmount??DEFAULT_SETTINGS.depositAmount),depositRefunded:Number(saved.depositRefunded??DEFAULT_SETTINGS.depositRefunded)}}
function normalizeTransactions(transactions=[]){const normalized=transactions.map(t=>({...t,receipt:validImageSource(t.receipt)?t.receipt:null,attachmentIds:Array.isArray(t.attachmentIds)?t.attachmentIds.filter(Boolean):[],items:(t.items||[]).map(i=>({...i,bucket:i.bucket||inferBucket(i),depositStatus:i.depositStatus||'held',depositRefunded:Number(i.depositRefunded||0),moveIn:Boolean(i.moveIn),prorated:Boolean(i.prorated)}))}));const seen=new Set();return normalized.filter(t=>{if(!t.sampleKey)return true;if(seen.has(t.sampleKey))return false;seen.add(t.sampleKey);return true})}
function load(){const fallback={budget:400,settings:normalizeSettings(),transactions:[],condition:[]};try{const saved=JSON.parse(localStorage.getItem(DB_KEY));if(!saved)return fallback;saved.settings=normalizeSettings(saved.settings);saved.transactions=normalizeTransactions(saved.transactions);return{...fallback,...saved}}catch{return fallback}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(state));render()}
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const signedMoney=n=>`${Number(n||0)<0?'-':''}${money(Math.abs(Number(n||0)))}`;
const netItem=i=>i.status==='avoided'||i.status==='cancelled'?0:Number(i.amount||0)-Number(i.adjustment||0);
const depositReturned=i=>Math.min(Number(i.amount||0),Math.max(0,Number(i.depositRefunded||0)));
const depositExpense=i=>{if(i.depositStatus==='forfeited')return Number(i.amount||0);if(i.depositStatus==='partially_refunded')return Number(i.amount||0)-depositReturned(i);return 0};
const depositHeldAmount=i=>i.depositStatus==='held'||i.depositStatus==='partially_refunded'?Number(i.amount||0)-depositReturned(i):0;
const itemHousingCost=i=>i.bucket==='refundable_deposit'?depositExpense(i):netItem(i);
function moveInTotals(){let cash=0,housing=0,held=0;for(const t of state.transactions)for(const i of t.items)if(i.moveIn){if(i.status==='avoided'||i.status==='cancelled')continue;cash+=Number(i.amount||0);housing+=itemHousingCost(i);if(i.bucket==='refundable_deposit')held+=depositHeldAmount(i)}return{cash,housing,held}}
function setupTotals(){let gross=0,refunds=0;for(const t of state.transactions){if(t.systemKey==='50a_lease_move_in')continue;for(const i of t.items){if(i.status==='avoided'||i.status==='cancelled'||i.bucket!=='housing_one_time')continue;gross+=Number(i.amount||0);refunds+=Number(i.adjustment||0)}}return{gross,refunds,net:gross-refunds}}
function leaseTransaction(){return{id:crypto.randomUUID(),systemKey:'50a_lease_move_in',merchant:'50A Lease Move-In',date:state.settings.moveInDate,notes:'Lease move-in charges managed from Settings.',receipt:null,attachmentIds:[],items:[{name:'Pro-rated first rent',amount:String(state.settings.proratedRent),category:'Other',bucket:'housing_recurring',prorated:true,moveIn:true,status:'kept',adjustment:'0'},{name:'Administrative fee',amount:String(state.settings.adminFee),category:'Other',bucket:'housing_one_time',moveIn:true,status:'kept',adjustment:'0'},{name:'Security deposit',amount:String(state.settings.depositAmount),category:'Other',bucket:'refundable_deposit',depositStatus:state.settings.depositStatus,depositRefunded:String(state.settings.depositRefunded),moveIn:true,status:'kept',adjustment:'0'}]}}
function upsertLeaseTransaction(){const next=leaseTransaction(),existing=state.transactions.find(t=>t.systemKey==='50a_lease_move_in');if(existing){next.id=existing.id;next.attachmentIds=existing.attachmentIds||[];state.transactions=state.transactions.map(t=>t.systemKey==='50a_lease_move_in'?{...t,...next}:t)}else state.transactions.push(next)}
function inferBucket(i){const text=`${i.name||''} ${i.category||''}`.toLowerCase();if(text.includes('grocer')||text.includes('food')||text.includes('drink'))return'groceries';if(text.includes('electric')||text.includes('water')||text.includes('sewer')||text.includes('utility'))return'utilities';if(text.includes('rent')||i.category==='Internet')return'housing_recurring';if(i.status==='avoided'||i.status==='cancelled')return'excluded';if(['Kitchen','Bathroom','Furniture','Cleaning','Security'].includes(i.category))return'housing_one_time';return'excluded'}
function currentMonthItems(){const month=new Date().toISOString().slice(0,7);return state.transactions.filter(t=>String(t.date||'').slice(0,7)===month).flatMap(t=>t.items)}
function benchmarkTotals(){const sums={housing_recurring:0,housing_one_time:0,utilities:0,groceries:0},recurringExtras=0;for(const i of currentMonthItems()){const bucket=BUCKETS.includes(i.bucket)?i.bucket:inferBucket(i);const isMonthlyRent=bucket==='housing_recurring'&&!i.prorated&&String(i.name||'').toLowerCase().includes('rent');if(bucket==='housing_recurring'){if(!isMonthlyRent)sums.housing_recurring+=itemHousingCost(i);if(!i.prorated&&!isMonthlyRent)recurringExtras+=itemHousingCost(i)}else if(bucket==='refundable_deposit'){sums.housing_one_time+=depositExpense(i)}else if(bucket in sums)sums[bucket]+=itemHousingCost(i)}sums.housing_recurring+=Number(state.settings.rent50a||0);const housing=sums.housing_recurring+sums.housing_one_time+sums.utilities;const recurringRunRate=Number(state.settings.rent50a||0)+recurringExtras+sums.utilities;const adjustmentTotal=state.settings.joshAdjustments.reduce((sum,adjustment)=>sum+Number(adjustment.amount||0),0);const benchmark=Number(state.settings.joshRent||0)+adjustmentTotal/(Math.max(1,Number(state.settings.joshStayDays||1))/30.4375);const monthlySavings=benchmark-recurringRunRate;const difference=benchmark-housing;const dates=state.transactions.map(t=>t.date).filter(Boolean).sort();const months=new Set(state.transactions.map(t=>String(t.date||'').slice(0,7)).filter(Boolean));const first=dates[0]?new Date(`${dates[0]}T00:00:00`):new Date();const monthsSinceMoveIn=Math.max(1,(new Date().getFullYear()-first.getFullYear())*12+new Date().getMonth()-first.getMonth()+1);return{...sums,housing,recurringRunRate,adjustmentTotal,benchmark,difference,monthlySavings,monthsSinceMoveIn,cumulative:months.size>1?monthlySavings*monthsSinceMoveIn:null,annual:monthlySavings*12}}
function totals(){let gross=0,refunds=0,avoided=0;for(const t of state.transactions){for(const i of t.items){if(i.status==='avoided'||i.status==='cancelled'){avoided+=Number(i.amount||0);continue}gross+=Number(i.amount||0);refunds+=Number(i.adjustment||0)}}return{gross,refunds,avoided,net:gross-refunds}}
function syncDepositSettingControl(){const status=$('#depositStatusInput').value;const enabled=status==='partially_refunded'||status==='refunded';$('#depositRefundedInput').disabled=!enabled;$('#depositRefundedSettingLabel').classList.toggle('line-field-hidden',!enabled)}
function render(){const t=totals(),setup=setupTotals(),moveIn=moveInTotals();$('#netSpend').textContent=money(setup.net);$('#grossSpend').textContent=money(t.gross);$('#refunds').textContent=money(t.refunds);$('#avoided').textContent=money(t.avoided);$('#budgetCopy').textContent=`of ${money(state.budget)} setup target`;$('#budgetBar').style.width=Math.min(100,(setup.net/state.budget)*100||0)+'%';$('#moveInCashOutflow').textContent=money(moveIn.cash);$('#moveInHousingCost').textContent=money(moveIn.housing);$('#depositHeld').textContent=money(moveIn.held);$('#budgetInput').value=state.budget;$('#rent50aInput').value=state.settings.rent50a;$('#joshRentInput').value=state.settings.joshRent;$('#joshCleaningInput').value=state.settings.joshAdjustments[0]?.amount||0;$('#joshMoveOutInput').value=state.settings.joshAdjustments[1]?.amount||0;$('#joshDaysInput').value=state.settings.joshStayDays;$('#moveInDateInput').value=state.settings.moveInDate;$('#proratedRentInput').value=state.settings.proratedRent;$('#adminFeeInput').value=state.settings.adminFee;$('#depositAmountInput').value=state.settings.depositAmount;$('#depositStatusInput').value=state.settings.depositStatus;$('#depositRefundedInput').value=state.settings.depositRefunded;syncDepositSettingControl();$('#seedBtn').textContent=['sample_50a_monthly_housing','sample_walmart_setup','sample_amazon_setup','sample_groceries'].every(key=>state.transactions.some(t=>t.sampleKey===key))?'Demo data loaded':'Load demo data';renderBenchmark();renderTransactions();renderCondition()}
function validImageSource(source){return typeof source==='string'&&source.trim()&&/^(data:image\/|blob:|https?:\/\/|\/|\.\.?\/)/i.test(source.trim())}
function renderBenchmark(){const b=benchmarkTotals();$('#housingTotal').textContent=money(b.housing);$('#joshBenchmark').textContent=money(b.benchmark);$('#recurringHousing').textContent=money(b.recurringRunRate);$('#oneTimeHousing').textContent=money(b.housing_one_time);$('#utilities').textContent=money(b.utilities);$('#groceries').textContent=money(b.groceries);$('#benchmarkDifference').textContent=signedMoney(b.difference);$('#benchmarkDifference').className=b.difference>=0?'positive':'negative';$('#benchmarkDifferenceLabel').textContent=b.difference>=0?'saved / headroom this month':'over benchmark this month';$('#benchmarkSummary').textContent=b.difference>=0?`50A is ${money(b.difference)} below Josh's effective monthly cost.`:`50A is ${money(Math.abs(b.difference))} above Josh's effective monthly cost.`;$('#joshFormula').textContent=`${money(state.settings.joshRent)} rent + ${state.settings.joshAdjustments.map(a=>`${money(a.amount)} ${a.label.toLowerCase()}`).join(' + ')} ÷ ${state.settings.joshStayDays} days × 30.4375`;$('#monthlySavings').textContent=signedMoney(b.monthlySavings);$('#cumulativeSavings').textContent=b.cumulative===null?'Available after additional months are recorded':signedMoney(b.cumulative);$('#annualSavings').textContent=signedMoney(b.annual)}
async function renderTransactions(){const root=$('#transactions');root.querySelectorAll('[data-preview-url]').forEach(image=>URL.revokeObjectURL(image.dataset.previewUrl));if(!state.transactions.length){root.className='cards empty-state';root.textContent='No transactions yet.';return}root.className='cards';root.innerHTML='';[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).forEach(async t=>{const card=document.createElement('article');card.className='transaction-card';const txTotal=t.items.reduce((s,i)=>s+netItem(i),0);const ids=t.attachmentIds||[];const managed=t.systemKey==='50a_lease_move_in';card.innerHTML=`<div class="transaction-top"><div><h3>${esc(t.merchant)}</h3><div class="meta">${esc(t.date)} · net ${money(txTotal)}${ids.length?` · ${ids.length} screenshot${ids.length===1?'':'s'}`:''}</div></div><div class="transaction-actions">${managed?'<small class="managed-note">Managed in Settings</small>':`<button type="button" class="ghost compact" data-edit-id="${esc(t.id)}">Edit</button>`}${t.receipt?`<img class="receipt-thumb legacy-receipt" src="${t.receipt}" alt="Legacy receipt screenshot">`:''}</div></div>${t.items.map(i=>`<div class="item-row"><div><strong>${esc(i.name)}</strong><span class="badge ${esc(i.status)}">${esc(i.status)}</span><div class="meta">${esc(i.category)} · ${esc(i.bucket||inferBucket(i))}${i.bucket==='refundable_deposit'?` · ${esc(i.depositStatus||'held')}${depositReturned(i)?` · returned ${money(depositReturned(i))}`:''}`:''}${i.prorated?' · prorated / one period':''}${i.moveIn?' · move-in':''}${i.adjustment?` · refund ${money(i.adjustment)}`:''}</div></div><strong class="money">${i.status==='avoided'||i.status==='cancelled'?'avoided '+money(i.amount):money(netItem(i))}</strong></div>`).join('')}${t.notes?`<div class="meta">${esc(t.notes)}</div>`:''}<div class="attachment-gallery" data-attachment-gallery="${esc(t.id)}"></div>`;root.append(card);if(ids.length){const gallery=card.querySelector('[data-attachment-gallery]');const attachments=await attachmentList(ids);attachments.filter(Boolean).forEach(attachment=>{const image=document.createElement('img');image.className='attachment-thumb';image.alt=attachment.fileName;image.title=attachment.fileName;image.src=URL.createObjectURL(attachment.blob);image.dataset.previewUrl=image.src;image.dataset.attachmentId=attachment.id;gallery.append(image)})}})}
function renderCondition(){for(const phase of ['move-in','move-out']){const root=$(phase==='move-in'?'#moveInGallery':'#moveOutGallery');const pics=state.condition.filter(x=>x.phase===phase);if(!pics.length){root.className='gallery empty-state';root.textContent=`No ${phase} photos yet.`;continue}root.className='gallery';root.innerHTML=pics.map(p=>`<article class="gallery-card"><img src="${p.data}" alt="${esc(p.room)}"><div><strong>${esc(p.room)}</strong><small>${esc(p.date)}</small>${p.notes?`<small>${esc(p.notes)}</small>`:''}</div></article>`).join('')}}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
const txDialog=$('#transactionDialog'),txForm=$('#transactionForm'),screenshotInput=$('#screenshotInput');
function clearPreviewUrls(){pendingPreviewUrls.forEach(url=>URL.revokeObjectURL(url));pendingPreviewUrls=[]}
function resetAttachmentDraft(){clearPreviewUrls();pendingFiles=[];existingAttachmentIds=[];removedAttachmentIds=[];$('#attachmentPreview').innerHTML=''}
function dismissTransactionDialog(){resetAttachmentDraft();editingTransactionId=null;txDialog.close()}
function renderAttachmentDraft(){const root=$('#attachmentPreview');root.innerHTML='';pendingFiles.forEach((file,index)=>{const wrapper=document.createElement('div');wrapper.className='draft-attachment';const image=document.createElement('img');image.src=pendingPreviewUrls[index];image.alt=file.name;const remove=document.createElement('button');remove.type='button';remove.className='icon-btn';remove.textContent='×';remove.setAttribute('aria-label',`Remove ${file.name}`);remove.onclick=()=>{pendingFiles.splice(index,1);pendingPreviewUrls.splice(index,1);URL.revokeObjectURL(image.src);renderAttachmentDraft()};wrapper.append(image,remove);root.append(wrapper)});existingAttachmentIds.forEach(id=>{const wrapper=document.createElement('div');wrapper.className='draft-attachment existing-attachment';wrapper.dataset.attachmentId=id;const image=document.createElement('img');image.alt='Existing screenshot';attachmentGet(id).then(attachment=>{if(attachment){image.src=URL.createObjectURL(attachment.blob);image.dataset.previewUrl=image.src}});const remove=document.createElement('button');remove.type='button';remove.className='icon-btn';remove.textContent='×';remove.setAttribute('aria-label','Remove existing screenshot');remove.onclick=()=>{removedAttachmentIds.push(id);existingAttachmentIds=existingAttachmentIds.filter(existingId=>existingId!==id);renderAttachmentDraft()};wrapper.append(image,remove);root.append(wrapper)})}
function openNewTransaction(){editingTransactionId=null;txForm.reset();resetAttachmentDraft();$('#lineItems').innerHTML='';addLine();txForm.date.value=new Date().toISOString().slice(0,10);txDialog.querySelector('.eyebrow').textContent='NEW PURCHASE';txDialog.querySelector('h2').textContent='Add transaction';txDialog.querySelector('[value="default"]').textContent='Save transaction';txDialog.showModal()}
$('#addTransactionBtn').onclick=openNewTransaction;$('#addLineBtn').onclick=()=>addLine();function syncLineItemControls(row){const bucket=row.querySelector('[data-field="bucket"]')?.value;const deposit=bucket==='refundable_deposit';row.querySelector('[data-field="depositStatus"]')?.classList.toggle('line-field-hidden',!deposit);row.querySelector('[data-field="depositRefunded"]')?.classList.toggle('line-field-hidden',!deposit);row.querySelector('[data-field="adjustment"]')?.classList.toggle('line-field-hidden',deposit);row.querySelector('[data-field="period"]')?.classList.toggle('line-field-hidden',bucket!=='housing_recurring');row.querySelector('[data-field="timing"]')?.classList.toggle('line-field-hidden',bucket!=='housing_recurring'&&bucket!=='housing_one_time'&&bucket!=='refundable_deposit'&&bucket!=='utilities')}
function addLine(item={}){const node=$('#lineItemTemplate').content.cloneNode(true);$$('[data-field]',node).forEach(input=>{const field=input.dataset.field;const value=field==='period'?(item.prorated?'prorated':'monthly'):field==='timing'?(item.moveIn?'move_in':'regular'):item[field]??(field==='status'?'kept':field==='bucket'?'housing_one_time':field==='depositStatus'?'held':field==='depositRefunded'?'0':'');input.value=value});const row=node.querySelector('.line-item');row.querySelector('[data-field="bucket"]').addEventListener('change',()=>syncLineItemControls(row));row.querySelector('.remove-line').onclick=e=>e.target.closest('.line-item').remove();$('#lineItems').append(node);syncLineItemControls($('#lineItems .line-item:last-child'))}
function collectItems(){return $$('#lineItems .line-item').map(row=>{const item=Object.fromEntries($$('[data-field]',row).map(el=>[el.dataset.field,el.value]));item.prorated=item.period==='prorated';item.moveIn=item.timing==='move_in';delete item.period;delete item.timing;return item}).filter(item=>item.name)}
screenshotInput.onchange=()=>{const files=[...screenshotInput.files].filter(file=>/^image\/(jpeg|png|webp)$/.test(file.type));pendingFiles.push(...files);pendingPreviewUrls.push(...files.map(file=>URL.createObjectURL(file)));renderAttachmentDraft();screenshotInput.value=''};
async function openEditTransaction(id){const transaction=state.transactions.find(item=>item.id===id);if(!transaction)return;editingTransactionId=id;txForm.reset();resetAttachmentDraft();txForm.merchant.value=transaction.merchant;txForm.date.value=transaction.date;txForm.notes.value=transaction.notes||'';existingAttachmentIds=[...(transaction.attachmentIds||[])];$('#lineItems').innerHTML='';transaction.items.forEach(item=>addLine(item));renderAttachmentDraft();txDialog.querySelector('.eyebrow').textContent='EDIT TRANSACTION';txDialog.querySelector('h2').textContent='Edit transaction';txDialog.querySelector('[value="default"]').textContent='Save changes';txDialog.showModal()}
txForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(txForm),items=collectItems();if(!items.length)return alert('Add at least one line item.');const id=editingTransactionId||crypto.randomUUID();const previous=state.transactions.find(transaction=>transaction.id===id);const attachmentIds=[...existingAttachmentIds];for(const file of pendingFiles){const attachmentId=crypto.randomUUID();await attachmentPut({id:attachmentId,transactionId:id,fileName:file.name,mimeType:file.type,createdAt:new Date().toISOString(),blob:file});attachmentIds.push(attachmentId)}for(const attachmentId of removedAttachmentIds)await attachmentDelete(attachmentId);const next={id,merchant:fd.get('merchant'),date:fd.get('date'),notes:fd.get('notes'),items,attachmentIds};if(previous){state.transactions=state.transactions.map(transaction=>transaction.id===id?{...transaction,...next}:transaction)}else state.transactions.push(next);save();resetAttachmentDraft();txDialog.close()});
txDialog.addEventListener('close',()=>{resetAttachmentDraft();editingTransactionId=null});
txDialog.addEventListener('cancel',event=>{event.preventDefault();dismissTransactionDialog()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&txDialog.open){event.preventDefault();dismissTransactionDialog()}});
$$('[data-dialog-dismiss="transactionDialog"]').forEach(button=>button.onclick=dismissTransactionDialog);
$('#transactions').addEventListener('click',async event=>{const settingsButton=event.target.closest('[data-open-settings]');if(settingsButton){$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));$('.tab[data-tab="settings"]').classList.add('active');$('#settings').classList.add('active');return}const edit=event.target.closest('[data-edit-id]');if(edit){openEditTransaction(edit.dataset.editId);return}const image=event.target.closest('.attachment-thumb,.legacy-receipt');if(image){const source=image.dataset.previewUrl||image.src;if(!validImageSource(source))return;const dialog=$('#imagePreviewDialog'),preview=$('#imagePreview');activePreviewUrl=null;activeAttachmentId=image.dataset.attachmentId||null;preview.src=source;dialog.hidden=false;dialog.showModal()}});
function clearImagePreview(){const dialog=$('#imagePreviewDialog'),preview=$('#imagePreview');if(activePreviewUrl&&activePreviewUrl!==preview.src)URL.revokeObjectURL(activePreviewUrl);activePreviewUrl=null;activeAttachmentId=null;preview.removeAttribute('src');dialog.hidden=true}
function closeImagePreview(){const dialog=$('#imagePreviewDialog');clearImagePreview();if(dialog.open)dialog.close()}
$('#closeImagePreviewBtn').onclick=closeImagePreview;$('#imagePreviewDialog').addEventListener('close',clearImagePreview);
$('#imagePreviewDialog').addEventListener('cancel',event=>{event.preventDefault();closeImagePreview()});
const condDialog=$('#conditionDialog'),condForm=$('#conditionForm');$('#addConditionBtn').onclick=()=>{condForm.reset();condDialog.showModal()};$$('[data-dialog-dismiss="conditionDialog"]').forEach(button=>button.onclick=()=>condDialog.close());condDialog.addEventListener('cancel',event=>{event.preventDefault();condDialog.close()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&condDialog.open){event.preventDefault();condDialog.close()}});condForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(condForm),files=fd.getAll('photos').filter(f=>f.size);for(const f of files)state.condition.push({id:crypto.randomUUID(),phase:fd.get('phase'),room:fd.get('room'),notes:fd.get('notes'),date:new Date().toISOString().slice(0,10),data:await fileData(f)});save();condDialog.close()});
function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
const settingInputs={rent50a:$('#rent50aInput'),joshRent:$('#joshRentInput'),joshCleaning:$('#joshCleaningInput'),joshMoveOut:$('#joshMoveOutInput'),joshStayDays:$('#joshDaysInput')},leaseInputs={moveInDate:$('#moveInDateInput'),proratedRent:$('#proratedRentInput'),adminFee:$('#adminFeeInput'),depositAmount:$('#depositAmountInput'),depositStatus:$('#depositStatusInput'),depositRefunded:$('#depositRefundedInput')};function syncSettingsFromInputs(){state.settings.rent50a=Number(settingInputs.rent50a.value||0);state.settings.joshRent=Number(settingInputs.joshRent.value||0);state.settings.joshAdjustments=[{label:'Cleaning fee',amount:Number(settingInputs.joshCleaning.value||0)},{label:'Final week / Sunday move-out charge',amount:Number(settingInputs.joshMoveOut.value||0)}];state.settings.joshStayDays=Number(settingInputs.joshStayDays.value||0);state.settings.moveInDate=leaseInputs.moveInDate.value||DEFAULT_SETTINGS.moveInDate;state.settings.proratedRent=Number(leaseInputs.proratedRent.value||0);state.settings.adminFee=Number(leaseInputs.adminFee.value||0);state.settings.depositAmount=Number(leaseInputs.depositAmount.value||0);state.settings.depositStatus=leaseInputs.depositStatus.value;state.settings.depositRefunded=Number(leaseInputs.depositRefunded.value||0)}Object.values(settingInputs).forEach(input=>input.addEventListener('input',()=>{syncSettingsFromInputs();renderBenchmark()}));leaseInputs.depositStatus.addEventListener('change',syncDepositSettingControl);$('#saveSettingsBtn').onclick=()=>{state.budget=Number($('#budgetInput').value||0);syncSettingsFromInputs();upsertLeaseTransaction();localStorage.setItem(DB_KEY,JSON.stringify(state));render()};$('#clearBtn').onclick=()=>{if(confirm('Delete all local 50A Ledger data?')){state={budget:400,settings:normalizeSettings(),transactions:[],condition:[]};save()}};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='50a-ledger-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{state=JSON.parse(await f.text());state.settings=normalizeSettings(state.settings);state.transactions=normalizeTransactions(state.transactions);save()}catch{alert('Invalid backup file')}};
const demoTransactions=()=>{const date=state.settings.moveInDate;return[{id:crypto.randomUUID(),sampleKey:'sample_50a_monthly_housing',merchant:'50A Monthly Housing',date,notes:'Sample recurring housing costs',receipt:null,items:[{name:'50A rent',amount:'965.00',category:'Other',bucket:'housing_recurring',status:'kept',adjustment:'0'},{name:'Electric',amount:'80.00',category:'Utilities',bucket:'utilities',status:'kept',adjustment:'0'}]},{id:crypto.randomUUID(),sampleKey:'sample_walmart_setup',merchant:'Walmart',date,notes:'Sample move-in setup and refund',receipt:null,items:[{name:'Curved shower rod',amount:'37.78',category:'Bathroom',bucket:'housing_one_time',status:'returned',adjustment:'37.78'},{name:'Soft-close toilet seat',amount:'19.94',category:'Bathroom',bucket:'housing_one_time',status:'kept',adjustment:'0'},{name:'Dinnerware + flatware',amount:'26.12',category:'Kitchen',bucket:'housing_one_time',status:'kept',adjustment:'0'},{name:'Waterdrop filtration system',amount:'66.99',category:'Kitchen',bucket:'housing_one_time',status:'kept',adjustment:'0'}]},{id:crypto.randomUUID(),sampleKey:'sample_amazon_setup',merchant:'Amazon',date,notes:'Purchase Police replacements',receipt:null,items:[{name:'TEECK replacement rod',amount:'12.79',category:'Bathroom',bucket:'housing_one_time',status:'kept',adjustment:'0'},{name:'AquaDance handheld shower head',amount:'17.99',category:'Bathroom',bucket:'housing_one_time',status:'kept',adjustment:'0'},{name:'19-piece knife set',amount:'25.84',category:'Kitchen',bucket:'excluded',status:'avoided',adjustment:'0'},{name:'Toaster',amount:'15.00',category:'Kitchen',bucket:'excluded',status:'avoided',adjustment:'0'}]},{id:crypto.randomUUID(),sampleKey:'sample_groceries',merchant:'Walmart groceries',date,notes:'Tracked separately from housing',receipt:null,items:[{name:'Groceries',amount:'65.00',category:'Groceries',bucket:'groceries',status:'kept',adjustment:'0'}]}]};$('#seedBtn').onclick=()=>{const existingKeys=new Set(state.transactions.map(t=>t.sampleKey));const additions=demoTransactions().filter(t=>!existingKeys.has(t.sampleKey));if(!additions.length){render();return}state.transactions.push(...additions.map(t=>({...t,attachmentIds:[]})));save()};
upsertLeaseTransaction();localStorage.setItem(DB_KEY,JSON.stringify(state));render();
