/* Pure vehicle/fuel rules shared by UI, cloud mapping and portable validation. */
(function(root){
 const fail=m=>{throw Error(m)};
 function scaled(value,places,label,optional=false){if(optional&&(value===null||value===undefined||value===''))return null;const text=String(value);if(!/^\d+(?:\.\d+)?$/.test(text))fail(`${label}: enter a nonnegative decimal`);const [whole,part='']=text.split('.');if(part.length>places)fail(`${label}: use at most ${places} decimal places`);const n=Number(whole)*10**places+Number(part.padEnd(places,'0'));if(!Number.isSafeInteger(n)||n>=10**12)fail(`${label}: out of range`);return n;}
 const roundedDivide=(a,b)=>Number((BigInt(a)+BigInt(b)/2n)/BigInt(b));
 const decimal=(n,p)=>n===null?null:(n/10**p).toFixed(p);
 function day(date){if(date.startsWith('0000')||!/^\d{4}-\d\d-\d\d$/.test(date)||!Number.isFinite(Date.parse(date+'T00:00:00Z'))||new Date(date+'T00:00:00Z').toISOString().slice(0,10)!==date)fail('Invalid fill date');return Date.parse(date+'T00:00:00Z')/86400000;}
 const days=(a,b)=>day(b)-day(a);
 function amounts(input,derive=true){const cents=scaled(input.totalCost,2,'Cost');if(cents<=0)fail('Cost must be greater than zero');let gallons=scaled(input.gallons,3,'Gallons',true),price=scaled(input.pricePerGallon,3,'Price per gallon',true);if(gallons===0||price===0)fail('Gallons and price must be positive when supplied');if(derive){if(gallons===null&&price!==null)gallons=roundedDivide(BigInt(cents)*10000n,price);if(price===null&&gallons!==null)price=roundedDivide(BigInt(cents)*10000n,gallons);}
 // Half-cent receipt rounding plus rounding of two 3-decimal fuel quantities; minimum 2 cents.
 if(gallons!==null&&price!==null){const tolerance=Math.max(2,Math.ceil((gallons+price)/20000+.5));if(Math.abs(roundedDivide(BigInt(gallons)*BigInt(price),10000)-cents)>tolerance)fail('Cost, gallons and price per gallon do not reconcile');}
 if(gallons===0||price===0)fail('Derived quantity is too small');return {totalCost:decimal(cents,2),gallons:decimal(gallons,3),pricePerGallon:decimal(price,3)};}
 const ordered=events=>[...events].sort((a,b)=>a.fillDate.localeCompare(b.fillDate)||(Number(a.odometer===null)-Number(b.odometer===null))||(Number(a.odometer)-Number(b.odometer))||a.id.localeCompare(b.id));
 function fuelCents(tx){return tx.items.filter(i=>i.bucket==='automotive').reduce((sum,i)=>sum+(['avoided','cancelled','reused'].includes(i.status)?0:Math.round(Number(i.amount)*100)-Math.round(Number(i.adjustment||0)*100)),0);}
 function validate(state){const vehicles=state.vehicles??[],events=state.fuelEvents??[];if(!Array.isArray(vehicles)||!Array.isArray(events))fail('Invalid Automotive collections');const ids=new Set(),owners=new Set();
 for(const v of vehicles){if(!v||typeof v.id!=='string'||!v.id||ids.has(v.id))fail('Duplicate/invalid vehicle ID');ids.add(v.id);if(typeof v.nickname!=='string'||!v.nickname.trim()||v.nickname.length>120)fail('Vehicle nickname required (120 characters maximum)');if(typeof v.active!=='boolean')fail('Vehicle active flag required');if(v.year!==null&&(!Number.isInteger(v.year)||v.year<1886||v.year>2200))fail('Invalid vehicle year');for(const k of ['make','model'])if(v[k]!==null&&(typeof v[k]!=='string'||v[k].length>120))fail('Invalid vehicle '+k);if(v.ownerId)owners.add(v.ownerId);}
 if(owners.size>1)fail('Vehicle ownership mismatch');const eventIds=new Set(),linked=new Set();
 for(const e of events){if(!e||typeof e.id!=='string'||!e.id||eventIds.has(e.id))fail('Duplicate/invalid fuel ID');eventIds.add(e.id);for(const k of ['gallons','pricePerGallon','odometer','station','notes','transactionId'])if(!Object.hasOwn(e,k))fail('Missing fuel field '+k);const v=vehicles.find(v=>v.id===e.vehicleId);if(!v)fail('Dangling fuel vehicle');if((e.ownerId??null)!==(v.ownerId??null))fail('Fuel vehicle ownership mismatch');day(e.fillDate);amounts(e,false);scaled(e.odometer,1,'Odometer',true);if(typeof e.fullTank!=='boolean')fail('Full tank flag required');for(const k of ['station','notes'])if(e[k]!==null&&typeof e[k]!=='string')fail('Invalid fuel '+k);
 if(e.transactionId){const tx=(state.transactions||[]).find(t=>t.id===e.transactionId);if(!tx)fail('Dangling fuel transaction');if(linked.has(tx.id))fail('Transaction already linked to a fuel event');linked.add(tx.id);if(fuelCents(tx)!==scaled(e.totalCost,2,'Cost'))fail('Fuel cost must match linked transaction automotive spending');}
 }
 for(const v of vehicles){let last=null;for(const e of ordered(events.filter(e=>e.vehicleId===v.id))){const odo=scaled(e.odometer,1,'Odometer',true);if(odo!==null){if(last!==null&&odo<last)fail('Odometer cannot decrease');last=odo;}}}return true;
 }
 function metrics(events,vehicleId,today,month=today.slice(0,7)){day(today);const all=ordered(events.filter(e=>e.vehicleId===vehicleId&&e.fillDate<=today)),last=all.at(-1),intervals=all.slice(1).map((e,i)=>{const prior=all[i],duration=days(prior.fillDate,e.fillDate),distance=e.odometer!==null&&prior.odometer!==null?Number(e.odometer)-Number(prior.odometer):null,eligible=all.filter(x=>x.fillDate===e.fillDate||x.fillDate===prior.fillDate).length===2&&duration>0&&distance>0&&e.fullTank&&prior.fullTank&&Number(e.gallons)>0;return {eventId:e.id,priorEventId:prior.id,days:duration,distance,mpg:eligible?distance/Number(e.gallons):null,costPerMile:eligible?Number(e.totalCost)/distance:null,costPerDay:duration>0?Number(prior.totalCost)/duration:null};});const cents=all.reduce((s,e)=>s+scaled(e.totalCost,2,'Cost'),0),selected=all.filter(e=>e.fillDate.startsWith(month));return {last,age:last?days(last.fillDate,today):null,currentTankAge:last?.fullTank?days(last.fillDate,today):null,previous:intervals.at(-1)??null,averageDays:intervals.length?intervals.reduce((s,i)=>s+i.days,0)/intervals.length:null,longestDays:intervals.length?Math.max(...intervals.map(i=>i.days)):null,intervals,periodSpend:selected.reduce((s,e)=>s+scaled(e.totalCost,2,'Cost'),0)/100,periodCount:selected.length,totalSpend:cents/100,averageCost:all.length?cents/100/all.length:null};}
 function saveVehicle(state,input,uuid=()=>crypto.randomUUID()){const next=structuredClone(state),now=new Date().toISOString(),old=(next.vehicles||[]).find(v=>v.id===input.id),v={...input,id:old?.id||uuid(),createdAt:old?.createdAt||now,updatedAt:now};next.vehicles=[...(next.vehicles||[]).filter(v=>v.id!==input.id),v];next.fuelEvents??=[];validate(next);return next;}
 function saveFuel(state,input,recordExpense=false,uuid=()=>crypto.randomUUID()){const next=structuredClone(state),now=new Date().toISOString(),old=(next.fuelEvents||[]).find(e=>e.id===input.id),vehicle=(next.vehicles||[]).find(v=>v.id===input.vehicleId);if(!vehicle||!vehicle.active&&!old)fail('Choose an active vehicle');const e={...input,...amounts(input),id:old?.id||uuid(),createdAt:old?.createdAt||now,updatedAt:now};if(recordExpense){if(e.transactionId)fail('Choose either an existing expense or create one');const tx={id:uuid(),merchant:e.station?.trim()||'Fuel',date:e.fillDate,notes:'',receipt:null,attachmentIds:[],items:[{name:'Fuel',amount:e.totalCost,category:'Automotive',bucket:'automotive',setupClass:'none',status:'kept',adjustment:'0'}]};next.transactions.push(tx);e.transactionId=tx.id;}next.fuelEvents=[...(next.fuelEvents||[]).filter(f=>f.id!==input.id),e];validate(next);return next;}
 const api={scaled,decimal,day,days,amounts,ordered,fuelCents,validate,metrics,saveVehicle,saveFuel};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.AutomotiveUtils=api;
})(globalThis);
