/* Automotive edits use the existing ledger queue and atomic RPC, never a second financial path. */
(async()=>{
 if(!window.LedgerApp)await new Promise(resolve=>window.addEventListener('ledger-ready',resolve,{once:true}));
 const U=AutomotiveUtils,app=LedgerApp,$=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n),today=()=>localDateKey(new Date());
 const canEdit=()=>window.CloudLedger?.active()&&!document.body.classList.contains('cloud-locked');
 const own=()=>JSON.parse(localStorage.getItem('50a-data-mode')||'{}').owner||null;
 const makeDialog=(id,title,contents)=>{const d=document.createElement('dialog');d.id=id;d.innerHTML=`<form class="dialog-form"><h2>${title}</h2>${contents}<p role="alert" data-error></p><div class="dialog-actions"><button type="button" class="ghost" data-cancel>Cancel</button><button class="accent" type="submit">Save</button></div></form>`;document.body.append(d);d.querySelector('[data-cancel]').onclick=()=>d.close();return d;};
 const vehicleDialog=makeDialog('vehicleDialog','Vehicle',`<label>Nickname<input name="nickname" required maxlength="120"></label><details><summary>Vehicle details</summary><label>Year<input name="year" type="number" min="1886" max="2200" step="1"></label><label>Make<input name="make" maxlength="120"></label><label>Model<input name="model" maxlength="120"></label></details><label class="auto-check"><input name="active" type="checkbox" checked> Active vehicle</label>`);
 const fuelDialog=makeDialog('fuelDialog','Log fill-up',`<label>Vehicle<select name="vehicleId" required></select></label><div class="form-grid"><label>Fill date<input name="fillDate" type="date" required></label><label>Total fuel cost ($)<input name="totalCost" type="number" min="0.01" step="0.01" inputmode="decimal" required></label></div><label class="auto-check"><input name="fullTank" type="checkbox" checked> Full tank</label><label class="auto-check"><input name="recordExpense" type="checkbox"> Also record this as an expense</label><p class="meta">Fuel history alone does not add to ledger expenses. A linked transaction is counted once.</p><details><summary>Optional fuel details &amp; transaction link</summary><label>Gallons<input name="gallons" type="number" min="0.001" step="0.001" inputmode="decimal"></label><label>Price per gallon ($)<input name="pricePerGallon" type="number" min="0.001" step="0.001" inputmode="decimal"></label><p data-derived role="status"></p><label>Odometer (miles)<input name="odometer" type="number" min="0" step="0.1" inputmode="decimal"></label><label>Station<input name="station"></label><label>Notes<textarea name="notes"></textarea></label><label>Link existing fuel expense<select name="transactionId"></select></label><p class="meta">Cost must match the transaction’s automotive subtotal. To change a linked cost, unlink and save first, edit the expense, then relink. Deleting a fuel event keeps its expense.</p></details><button type="button" class="danger" data-delete hidden>Delete fuel event</button>`);
 let vehicleId=null,eventId=null,editVersion=null;
 const value=(form,name)=>form.elements.namedItem(name),err=d=>d.querySelector('[data-error]');
 const vehicleForm=vehicleDialog.querySelector('form'),fuelForm=fuelDialog.querySelector('form');
 const text=(root,tag,content,cls)=>{const e=document.createElement(tag);e.textContent=content;if(cls)e.className=cls;root.append(e);return e;};
 const button=(root,label,fn)=>{const b=text(root,'button',label,'ghost compact');b.type='button';b.onclick=fn;return b;};
 function checkEdit(){if(!canEdit())throw Error('Sign in to the cloud ledger first.');if(JSON.stringify(app.get())!==editVersion)throw Error('Ledger changed. Cancel and reopen this form.');}
 function openVehicle(id){if(!canEdit())return;vehicleId=id||null;const data=app.get(),v=(data.vehicles||[]).find(v=>v.id===id);editVersion=JSON.stringify(data);vehicleForm.reset();err(vehicleDialog).textContent='';for(const key of ['nickname','year','make','model'])value(vehicleForm,key).value=v?.[key]??'';value(vehicleForm,'active').checked=v?.active??true;vehicleDialog.showModal();}
 vehicleForm.onsubmit=e=>{e.preventDefault();try{checkEdit();const next=U.saveVehicle(app.get(),{id:vehicleId,ownerId:own(),nickname:value(vehicleForm,'nickname').value.trim(),year:value(vehicleForm,'year').value?Number(value(vehicleForm,'year').value):null,make:value(vehicleForm,'make').value.trim()||null,model:value(vehicleForm,'model').value.trim()||null,active:value(vehicleForm,'active').checked});app.commit(next);$('#autoVehicle').value=vehicleId||next.vehicles.at(-1).id;render();vehicleDialog.close();}catch(error){err(vehicleDialog).textContent=error.message}};
 function openFuel(id){if(!canEdit())return;const data=app.get(),event=(data.fuelEvents||[]).find(e=>e.id===id);eventId=id||null;editVersion=JSON.stringify(data);fuelForm.reset();err(fuelDialog).textContent='';fuelDialog.querySelector('h2').textContent=id?'Edit fill-up':'Log fill-up';fuelDialog.querySelector('[data-delete]').hidden=!id;
 const vehicles=(data.vehicles||[]).filter(v=>v.active||v.id===event?.vehicleId);value(fuelForm,'vehicleId').replaceChildren(...vehicles.map(v=>new Option(v.nickname,v.id)));value(fuelForm,'vehicleId').value=event?.vehicleId||($('#autoVehicle').value!=='all'?$('#autoVehicle').value:vehicles[0]?.id)||'';
 for(const k of ['fillDate','totalCost','gallons','pricePerGallon','odometer','station','notes'])value(fuelForm,k).value=event?.[k]??(k==='fillDate'?today():'');value(fuelForm,'fullTank').checked=event?.fullTank??true;
 const used=new Set((data.fuelEvents||[]).filter(e=>e.id!==id).map(e=>e.transactionId));const txs=data.transactions.filter(t=>!used.has(t.id)&&U.fuelCents(t)>0&&!t.systemKey);value(fuelForm,'transactionId').replaceChildren(new Option('No linked transaction',''),...txs.map(t=>new Option(`${t.date} · ${t.merchant} · ${money(U.fuelCents(t)/100)}`,t.id)));value(fuelForm,'transactionId').value=event?.transactionId||'';updateLink();derive();fuelDialog.showModal();}
 function updateLink(){const linked=!!value(fuelForm,'transactionId').value;value(fuelForm,'recordExpense').disabled=linked;if(linked)value(fuelForm,'recordExpense').checked=false;}
 value(fuelForm,'transactionId').onchange=()=>{updateLink();const t=app.get().transactions.find(t=>t.id===value(fuelForm,'transactionId').value);if(t&&!value(fuelForm,'totalCost').value)value(fuelForm,'totalCost').value=(U.fuelCents(t)/100).toFixed(2);derive()};
 function derive(){const out=fuelDialog.querySelector('[data-derived]');try{const a=U.amounts({totalCost:value(fuelForm,'totalCost').value,gallons:value(fuelForm,'gallons').value,pricePerGallon:value(fuelForm,'pricePerGallon').value});out.textContent=`${a.gallons??'Unknown'} gallons · ${a.pricePerGallon?'$'+a.pricePerGallon:'Unknown price'}/gallon. Derived values are applied on Save.`;}catch(e){out.textContent=e.message}}
 for(const k of ['totalCost','gallons','pricePerGallon'])value(fuelForm,k).addEventListener('input',derive);
 fuelForm.onsubmit=e=>{e.preventDefault();try{checkEdit();const input={id:eventId,ownerId:own(),vehicleId:value(fuelForm,'vehicleId').value,fullTank:value(fuelForm,'fullTank').checked};for(const k of ['fillDate','totalCost','gallons','pricePerGallon','odometer','station','notes','transactionId'])input[k]=value(fuelForm,k).value||null;app.commit(U.saveFuel(app.get(),input,value(fuelForm,'recordExpense').checked));$('#autoVehicle').value=input.vehicleId;render();fuelDialog.close();}catch(error){err(fuelDialog).textContent=error.message}};
 fuelDialog.querySelector('[data-delete]').onclick=()=>{try{checkEdit();if(!confirm('Delete this fuel event? Any linked financial transaction and receipt will remain.'))return;const next=app.get();next.fuelEvents=next.fuelEvents.filter(e=>e.id!==eventId);app.commit(next);fuelDialog.close();}catch(error){err(fuelDialog).textContent=error.message}};
 function render(){const data=app.get(),vehicles=data.vehicles||[],events=data.fuelEvents||[],selector=$('#autoVehicle'),prior=selector.value;selector.replaceChildren(new Option('All vehicles','all'),...vehicles.map(v=>new Option(v.nickname+(v.active?'':' (inactive)'),v.id)));selector.value=vehicles.some(v=>v.id===prior)||prior==='all'?prior:(vehicles.find(v=>v.active)?.id||'all');const selected=selector.value,v=vehicles.find(v=>v.id===selected),month=$('#autoMonth').value||today().slice(0,7),list=events.filter(e=>selected==='all'||e.vehicleId===selected),m=selected==='all'?null:U.metrics(events,selected,today(),month),root=$('#autoMetrics');root.replaceChildren();
 const metric=(label,content)=>{const card=text(root,'div','', 'metric');text(card,'span',label);text(card,'strong',content)};
 const spending=list.filter(e=>e.fillDate.startsWith(month)&&e.fillDate<=today()).reduce((sum,e)=>sum+U.scaled(e.totalCost,2,'Cost'),0)/100;metric('Fuel history · selected month',money(spending));metric('Events · selected month',String(list.filter(e=>e.fillDate.startsWith(month)&&e.fillDate<=today()).length));
 if(m){metric(m.last?.fullTank?'Current tank age':'Days since fuel event',m.age===null?'—':`${m.age} days`);metric('Last fill-up',m.last?`${m.last.fillDate} · ${money(Number(m.last.totalCost))}`:'No fill-ups yet');if(m.last)text(root,'p',`${m.last.fullTank?'Full tank':'Partial fill'} · ${m.last.gallons??'—'} gal · ${m.last.pricePerGallon?'$'+m.last.pricePerGallon:'—'}/gal · Odometer ${m.last.odometer??'—'}`,'meta');const p=m.previous;$('#autoPace').textContent=`Days between events — previous: ${p?.days??'—'} · average: ${m.averageDays?.toFixed(1)??'—'} · longest: ${m.longestDays??'—'}. ${m.age!==null&&p?`Current age is ${Math.abs(m.age-p.days)} days ${m.age>=p.days?'longer':'shorter'} than the last completed interval (still in progress).`:''} Average fill: ${m.averageCost===null?'—':money(m.averageCost)}. Latest distance: ${p?.distance??'—'} miles · MPG: ${p?.mpg?.toFixed(1)??'not enough consecutive full-fill data'} · cost/mile: ${p?.costPerMile==null?'—':money(p.costPerMile)} · purchase cost/day: ${p?.costPerDay==null?'—':money(p.costPerDay)}.`;}
 else $('#autoPace').textContent='Choose a vehicle for tank age, intervals, mileage and MPG. Fuel history totals are operational summaries, not additional ledger expenses.';
 $('#autoStatus').textContent=!canEdit()?'Sign in and use cloud mode to add or edit Automotive records.':!vehicles.length?'Add your first vehicle, then log a fill-up.':'Unlinked fuel events appear here only. Linked expenses count once in the ledger.';
 $('#addVehicleBtn').disabled=!canEdit();$('#editVehicleBtn').disabled=!canEdit()||!v;$('#logFuelBtn').disabled=!canEdit()||!vehicles.some(v=>v.active)||(v&&!v.active);
 const history=$('#fuelHistory');history.replaceChildren();for(const e of U.ordered(list).reverse()){const card=text(history,'article','', 'transaction-card');text(card,'h3',`${e.fillDate} · ${money(Number(e.totalCost))}`);text(card,'p',`${vehicles.find(v=>v.id===e.vehicleId)?.nickname||'Vehicle'} · ${e.fullTank?'Full tank':'Partial fill'} · ${e.gallons??'—'} gal · ${e.pricePerGallon?'$'+e.pricePerGallon:'—'}/gal · Odometer ${e.odometer??'—'}`,'meta');button(card,'Edit fill-up',()=>openFuel(e.id)).disabled=!canEdit();if(e.transactionId)button(card,'View linked transaction / receipt',()=>app.openTransaction(e.transactionId));if(e.station||e.notes){const d=document.createElement('details');text(d,'summary','Details');text(d,'p',[e.station,e.notes].filter(Boolean).join(' · '));card.append(d);}}if(!list.length)text(history,'p','No fuel events yet.','meta');
 }
 $('#autoMonth').value=today().slice(0,7);$('#autoVehicle').onchange=render;$('#autoMonth').onchange=render;$('#addVehicleBtn').onclick=()=>openVehicle();$('#editVehicleBtn').onclick=()=>openVehicle($('#autoVehicle').value);$('#logFuelBtn').onclick=()=>openFuel();window.addEventListener('ledger-rendered',render);window.addEventListener('focus',render);setInterval(()=>{if(!document.querySelector('dialog[open]'))render()},60000);render();
})();
