/* Housing Coverage uses the existing ledger commit, queue and refresh lifecycle. */
(function start(){
 if(!window.LedgerApp){window.addEventListener('ledger-ready',start,{once:true});return}
 const app=window.LedgerApp,H=HousingUtils,$=s=>document.querySelector(s),money=c=>(c/100).toLocaleString('en-US',{style:'currency',currency:'USD'}),today=()=>localDateKey(new Date());
 const editable=()=>window.CloudLedger?.active()&&!document.body.classList.contains('cloud-locked');
 const el=(root,tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;root.append(n);return n};
 const button=(root,label,fn,write=true)=>{const b=el(root,'button',label,'ghost');b.type='button';b.onclick=fn;b.disabled=write&&!editable();return b};
 const dialog=el(document.body,'dialog');dialog.id='housingDialog';dialog.className='housing-dialog';const form=el(dialog,'form','','dialog-form');
 let selectedMonth=H.localMonth(),original,submitAction;
 const input=(root,label,name,type='text',value='',required=true)=>{const l=el(root,'label',label),i=el(l,'input');Object.assign(i,{name,type,required});i.value=value;if(type==='number'){i.step='0.01';i.min='0';i.inputMode='decimal'}return i};
 const select=(root,label,name,options,value)=>{const l=el(root,'label',label),i=el(l,'select');i.name=name;for(const [id,name]of options)i.add(new Option(name,id));i.value=value??options[0]?.[0]??'';return i};
 const check=(root,label,name,value)=>{const l=el(root,'label',label),i=el(l,'input');i.type='checkbox';i.name=name;i.checked=value;return i};
 const f=name=>form.elements.namedItem(name),num=name=>H.money(f(name).value),optional=name=>f(name).value===''?null:num(name);
 function open(title,draw,action){if(!editable())return;original=JSON.stringify(app.get());form.replaceChildren();el(form,'h2',title);draw(H.data(app.get()));el(form,'p','','meta').dataset.preview='';const error=el(form,'p');error.role='alert';error.dataset.error='';button(form,'Check cloud compatibility',async()=>{try{error.textContent=await window.CloudLedger.checkCompatibility()==='compatible'?'Cloud support verified. Review and press Save.':'Cloud update required. Your form is preserved.'}catch{error.textContent='Connect and sign in, then check again.'}},false);const actions=el(form,'div','','actions');button(actions,'Cancel',()=>dialog.close(),false);const save=el(actions,'button','Save','accent');save.type='submit';submitAction=action;dialog.showModal();}
 form.onsubmit=event=>{event.preventDefault();try{if(!editable())throw Error('Sign in to the cloud ledger first.');if(original!==JSON.stringify(app.get()))throw Error('Ledger changed. Cancel and reopen this form.');app.commit(submitAction(app.get()));dialog.close()}catch(e){form.querySelector('[data-error]').textContent=e.message}};
 function source(id){const row=H.data(app.get()).income_sources.find(r=>r.id===id);open(row?'Edit income source':'Add income source',()=>{input(form,'Name','name','text',row?.name??'Publix');select(form,'Type','source_type',[['employment','Employment'],['other','Other']],row?.source_type);input(form,'Default hourly rate ($; optional)','hourly_rate_cents','number',row?.hourly_rate_cents==null?(row?'':'16.00'):(row.hourly_rate_cents/100).toFixed(2),false);input(form,'Typical shift hours (optional)','typical_shift_hundredths','number',row?.typical_shift_hundredths==null?'':row.typical_shift_hundredths/100,false);check(form,'Active','active',row?.active??true);el(form,'p','Changing the default rate does not change saved shifts. Inactive sources retain their history.','meta')},s=>H.put(s,'income_sources',{id:row?.id,name:f('name').value.trim(),source_type:f('source_type').value,active:f('active').checked,hourly_rate_cents:optional('hourly_rate_cents'),typical_shift_hundredths:optional('typical_shift_hundredths')}))}
 function chooseSource(d,row){return select(form,'Income source','income_source_id',d.income_sources.filter(r=>r.active||r.id===row?.income_source_id).map(r=>[r.id,r.name]),row?.income_source_id||H.target(app.get(),selectedMonth).config?.income_source_id)}
 function removeControl(table,row){if(row)button(form,'Delete record',()=>{try{if(original!==JSON.stringify(app.get()))throw Error('Ledger changed. Cancel and reopen this form.');if(!confirm('Delete this income record? Coverage will be recalculated.'))return;const next=app.get();next.housingFinance[table]=next.housingFinance[table].filter(r=>r.id!==row.id);app.commit(next);dialog.close()}catch(e){form.querySelector('[data-error]').textContent=e.message}})}
 function shift(id){const row=H.data(app.get()).work_sessions.find(r=>r.id===id);open(row?'Edit work hours':'Log work hours',d=>{const selector=chooseSource(d,row);input(form,'Work date','work_date','date',row?.work_date||today());input(form,'Hours','hours','number',row?row.hours_hundredths/100:'');input(form,'Hourly rate ($)','rate','number',row?row.hourly_rate_cents/100:(d.income_sources.find(r=>r.id===selector.value)?.hourly_rate_cents??1600)/100);input(form,'Notes (optional)','notes','text',row?.notes||'',false);el(form,'p','Estimated gross, before deductions. Saved shifts retain their original rate.','meta');selector.onchange=()=>{f('rate').value=(d.income_sources.find(r=>r.id===selector.value)?.hourly_rate_cents??0)/100;preview()};for(const n of ['hours','rate'])f(n).oninput=()=>preview();removeControl('work_sessions',row)},s=>H.put(s,'work_sessions',{id:row?.id,income_source_id:f('income_source_id').value,work_date:f('work_date').value,hours_hundredths:num('hours'),hourly_rate_cents:num('rate'),notes:f('notes').value}));function preview(){try{form.querySelector('[data-preview]').textContent='Estimated gross: '+money(H.gross({hours_hundredths:num('hours'),hourly_rate_cents:num('rate')}))}catch{form.querySelector('[data-preview]').textContent='Enter hours and rate to see estimated gross.'}}preview()}
 function paycheck(id){const row=H.data(app.get()).paychecks.find(r=>r.id===id);open(row?'Edit actual paycheck':'Add actual paycheck',d=>{chooseSource(d,row);input(form,'Pay date','pay_date','date',row?.pay_date||today());input(form,'Period start (optional)','period_start','date',row?.period_start||'',false);input(form,'Period end (optional)','period_end','date',row?.period_end||'',false);input(form,'Gross pay ($; optional)','gross_cents','number',row?.gross_cents==null?'':row.gross_cents/100,false);input(form,'Actual net pay ($)','net_cents','number',row?row.net_cents/100:'');input(form,'Notes (optional)','notes','text',row?.notes||'',false);el(form,'p','Earned-month policy: actual net replaces ALL shift estimates in the confirmed period. Net is spread evenly across calendar days; remaining cents go to earliest days. A paycheck without a period is saved as unreconciled and excluded from coverage. Same-source periods cannot overlap.','meta');for(const name of ['income_source_id','period_start','period_end','net_cents'])f(name).oninput=()=>preview();removeControl('paychecks',row)},s=>H.put(s,'paychecks',{id:row?.id,income_source_id:f('income_source_id').value,pay_date:f('pay_date').value,period_start:f('period_start').value||null,period_end:f('period_end').value||null,gross_cents:optional('gross_cents'),net_cents:num('net_cents'),notes:f('notes').value}));function preview(){const start=f('period_start').value,end=f('period_end').value;const shifts=H.data(app.get()).work_sessions.filter(w=>w.income_source_id===f('income_source_id').value&&w.work_date>=start&&w.work_date<=end);form.querySelector('[data-preview]').textContent=start&&end?`${shifts.length} saved shifts · ${money(shifts.reduce((n,w)=>n+H.gross(w),0))} estimated gross replaced by this paycheck's actual net. Work history remains.`:'Unreconciled: enter both period dates to include actual net in coverage.'}preview()}
 function goal(id){const row=H.data(app.get()).financial_goals.find(r=>r.id===id);open(row?'Edit financial goal':'Add financial goal',()=>{input(form,'Goal name','name','text',row?.name||'');select(form,'Goal type','goal_type',[['debt','Debt payoff'],['investment','Investment'],['other','Other']],row?.goal_type);input(form,'Target ($)','target_cents','number',row?row.target_cents/100:'');check(form,'Active','active',row?.active??true);check(form,'Completed','completed',row?.completed??false);el(form,'p','Surplus is available toward this goal. This feature does not record payments, reduce debt, or move money.','meta')},s=>H.put(s,'financial_goals',{id:row?.id,name:f('name').value.trim(),goal_type:f('goal_type').value,target_cents:num('target_cents'),active:f('active').checked,completed:f('completed').checked}))}
 function configuration(){open('Coverage source and next goal',d=>{input(form,'Effective month','effective_month','month',selectedMonth);const c=H.latest(d.coverage_settings,selectedMonth);select(form,'Coverage income source','income_source_id',[['','No source'],...d.income_sources.map(r=>[r.id,r.name+(r.active?'':' (inactive)')])],c?.income_source_id||'');select(form,'Next goal','goal_id',[['','No goal'],...d.financial_goals.filter(g=>g.active&&!g.completed||g.id===c?.goal_id).map(r=>[r.id,r.name])],c?.goal_id||'');el(form,'p','This choice applies until the next configuration month. Selecting an existing month corrects that choice. Historical earnings remain after a source is deactivated.','meta')},s=>{const d=H.data(s),m=f('effective_month').value;if(m<d.coverage_settings.map(r=>r.effective_month).sort()[0])throw Error('Configuration cannot predate the confirmed baseline.');return H.put(s,'coverage_settings',{id:d.coverage_settings.find(r=>r.effective_month===m)?.id,effective_month:m,income_source_id:f('income_source_id').value||null,goal_id:f('goal_id').value||null})})}
 function baseline(){open('Establish Housing Coverage baseline',()=>{input(form,'Starting month','effective_month','month',selectedMonth);el(form,'p','Confirm every current Monthly bill. Choose which bills count and confirm their amount and active state for this starting month. Earlier months stay “Housing target not established.” Nothing is selected automatically.','meta');for(const [i,b]of app.get().recurringCharges.entries()){const group=el(form,'fieldset');el(group,'legend',b.name);input(group,'Baseline amount ($)','amount'+i,'number',b.amount);check(group,'Active in baseline','active'+i,b.active);check(group,'Counts toward Housing Coverage','included'+i,false)}check(form,'I confirm these Monthly bills as the baseline beginning the selected month.','confirmed',false)},s=>{if(!f('confirmed').checked)throw Error('Confirm the starting month and bills first.');return H.baseline(s,f('effective_month').value,s.recurringCharges.map((b,i)=>({id:b.id,amount:f('amount'+i).value,active:f('active'+i).checked,included:f('included'+i).checked})))})}
 function render(){const s=app.get(),d=H.data(s),c=H.coverage(s,selectedMonth),root=$('#housingCoverageCard');root.replaceChildren();el(root,'p','FREEDOM METER','eyebrow');el(root,'h2',`${c.source?.name?c.source.name+' ':''}Housing Coverage`);const picker=input(root,'Coverage month','coverageMonth','month',selectedMonth);picker.onchange=()=>{if(picker.value){selectedMonth=picker.value;render()}};
 el(root,'p','Earned-month view · analytical allocation, not a payment record.','meta');
 if(!c.target.established){el(root,'h3','Housing target not established');el(root,'p','Choose a confirmed baseline to begin. Earlier months have no inferred target.');if(!d.coverage_settings.length)button(root,'Establish Housing Coverage baseline',baseline)}
 else{el(root,'h3',c.target.cents===0?'Housing target established at $0':c.percent===100?'Housing covered — 100%':`${c.percent.toFixed(1)}% covered`);if(c.target.cents>0){const progress=el(root,'progress');progress.max=100;progress.value=c.percent;progress.setAttribute('aria-label','Housing coverage');progress.style.width='100%'}const grid=el(root,'div','','benchmark-grid housing-grid');for(const [label,value]of [['Housing target',c.target.cents],[c.earnings.label,c.earnings.total],['Remaining',c.remaining],['Surplus',c.surplus],['Income freed from housing',c.freed]]){const card=el(grid,'div','','benchmark-metric');el(card,'span',label);el(card,'strong',money(value))}const explanation=el(root,'details');el(explanation,'summary','Calculation and allocation details');el(explanation,'p',`${money(c.earnings.actual)} actual net + ${money(c.earnings.estimated)} unmatched estimated gross. ${money(c.earnings.superseded)} of shift estimates superseded; saved hours remain. ${c.earnings.unreconciled} paycheck(s) without confirmed periods excluded.`, 'meta');if(c.hours!==null&&c.remaining>0)el(root,'p',`Approx. ${c.hours.toFixed(1)} work hours${c.shifts!==null?' / '+c.shifts.toFixed(1)+' typical shifts':''} remaining at the current gross hourly rate; take-home pay may require more hours.`);el(explanation,'p',`${money(c.freed)} of housing is covered analytically, reducing what other income needs to cover by the same amount. This does not track transfers or bill payments.`,'meta');el(root,'p',c.goal?`${money(c.available)} available toward ${c.goal.name} (target ${money(c.goal.target_cents)}). No debt payment or balance reduction is recorded.`:'No active next goal selected. Surplus remains available.');if(!c.source)el(root,'p','Choose an income source to calculate coverage.');else if(!c.source.active)el(root,'p','Selected source is inactive. Historical records still contribute.');button(root,'Choose source / goal',configuration)}
 button(root,'Log work hours',()=>shift()).disabled=!editable()||!d.income_sources.some(r=>r.active);
 const income=$('#housingIncome');income.replaceChildren();el(income,'h2','Income & goals');el(income,'p',editable()?'Income records use the same cloud queue and refresh as the ledger.':'Sign in and use cloud mode to add or edit income records.');const actions=el(income,'div','','actions');button(actions,'Add income source',()=>source());button(actions,'Log work hours',()=>shift()).disabled=!editable()||!d.income_sources.some(r=>r.active);button(actions,'Add actual paycheck',()=>paycheck()).disabled=!editable()||!d.income_sources.some(r=>r.active);button(actions,'Add financial goal',()=>goal());if(d.coverage_settings.length)button(actions,'Choose source / goal',configuration);else button(actions,'Establish Housing Coverage baseline',baseline);
 for(const [title,rows,edit,describe]of [['Income sources',d.income_sources,source,r=>`${r.name} · ${r.active?'Active':'Inactive'} · ${r.hourly_rate_cents===null?'No hourly rate':money(r.hourly_rate_cents)+'/hr'}`],['Work hours',d.work_sessions,shift,r=>`${r.work_date} · ${d.income_sources.find(x=>x.id===r.income_source_id)?.name} · ${r.hours_hundredths/100} hours · ${money(H.gross(r))} estimated gross`],['Actual paychecks',d.paychecks,paycheck,r=>`${r.pay_date} · ${money(r.net_cents)} net · ${r.period_start?r.period_start+' through '+r.period_end:'Unreconciled — excluded'}`],['Financial goals',d.financial_goals,goal,r=>`${r.name} · ${money(r.target_cents)} target · ${r.completed?'Completed':r.active?'Active':'Inactive'}`]]){const list=el(income,'details');el(list,'summary',`${title} (${rows.length})`);for(const r of [...rows].reverse()){const card=el(list,'article','','transaction-card');el(card,'p',describe(r));button(card,'Edit',()=>edit(r.id))}}
 const history=el(income,'details');el(history,'summary','Monthly coverage history');for(const c of H.history(s)){const row=el(history,'article','','transaction-card');el(row,'p',`${c.month} · ${c.target.cents===0?'$0 target':c.percent.toFixed(1)+'% covered'} · ${money(c.earnings.total)} / ${money(c.target.cents)} · ${money(c.surplus)} surplus · ${c.earnings.label}`);button(row,'View month',()=>{selectedMonth=c.month;render();$('[data-tab="overview"]').click()},false)}
 }
 window.addEventListener('ledger-rendered',render);window.addEventListener('focus',render);render();
})();
