import test from 'node:test';import assert from 'node:assert/strict';
import {createHandler,identity,uuidV5,VOICE_CONTRACT} from '../server/alexa-water.mjs';
const owner='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',now=Date.parse('2026-09-29T12:00:00Z');
const env={FIFTY_A_VOICE_OWNER_ID:owner,FIFTY_A_VOICE_TOKEN:'t'.repeat(43),SUPABASE_URL:'https://test.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'synthetic-test-only'};
const body={request_id:'amzn1.echo-api.request.synthetic',request_timestamp:'2026-09-29T12:00:00Z'};
function fixture({environment=env,rpc,admin}={}){
 const calls=[];const client={auth:{admin:{getUserById:admin||(async()=>({data:{user:{id:owner,email_confirmed_at:'2026-01-01'}}}))}},rpc:async(name,args)=>{calls.push({name,args});if(rpc)return rpc(name,args);return {data:name==='ledger_capabilities'?VOICE_CONTRACT:{replayed:false}}}};
 const handler=createHandler({env:environment,now:()=>now,clientFactory:()=>client});
 return {calls,async send(b=body,headers={},method='POST'){let result;const res={setHeader(){},end(s){result={status:this.statusCode,...JSON.parse(s)}}};await handler({method,body:b,headers:{authorization:`Bearer ${env.FIFTY_A_VOICE_TOKEN}`,'content-type':'application/json',...headers}},res);return result}};
}
test('UUIDv5 matches RFC vector and distinct fixed event/operation identities',()=>{
 assert.equal(uuidV5('6ba7b810-9dad-11d1-80b4-00c04fd430c8','www.widgets.com'),'21f7f8de-8051-5b89-8680-0195ef798b6a');
 const a=identity(body,now);assert.deepEqual(identity({...body,request_timestamp:'2026-09-29T12:00:00.000Z'},now),a);assert.notEqual(a.event,a.operation);assert.notEqual(identity({...body,request_id:'another'},now).event,a.event);
});
test('successful endpoint writes only narrow arguments, forced server owner',async()=>{const f=fixture();assert.equal((await f.send()).ok,true);assert.deepEqual(f.calls.map(c=>c.name),['ledger_capabilities','alexa_log_water']);assert.deepEqual(f.calls[1].args,{p_owner:owner,p_event:identity(body,now).event,p_operation:identity(body,now).operation,p_completed_at:'2026-09-29T12:00:00.000Z'})});
for(const authorization of [undefined,'Bearer wrong'])test(`denies ${authorization?'wrong':'missing'} voice token with zero RPC`,async()=>{const f=fixture();assert.equal((await f.send(body,{authorization})).status,401);assert.equal(f.calls.length,0)});
for(const key of Object.keys(env))test(`missing ${key} fails closed`,async()=>{const f=fixture({environment:{...env,[key]:''}});assert.equal((await f.send()).status,503);assert.equal(f.calls.length,0)});
for(const [key,value]of Object.entries({owner_id:owner,gallons:20,legacy:true,domain:'transactions',table:'water_events',action:'delete',sql:'drop table',revision:'x',event_id:owner,operation_id:owner}))test(`rejects extra ${key} before RPC`,async()=>{const f=fixture();assert.equal((await f.send({...body,[key]:value})).status,400);assert.equal(f.calls.length,0)});
for(const bad of [{request_timestamp:body.request_timestamp},{...body,request_id:'../water'}, {...body,request_id:''},{request_id:body.request_id},{...body,request_timestamp:'2026-02-30T00:00:00Z'},{...body,request_timestamp:'2026-09-29T13:00:00Z'},{...body,request_timestamp:'1900-01-01T00:00:00Z'},{...body,request_timestamp:'bad'}])test(`invalid identity ${JSON.stringify(bad)}`,async()=>{const f=fixture();assert.equal((await f.send(bad)).status,400);assert.equal(f.calls.length,0)});
test('malformed JSON, oversized bodies, wrong content type and method rejected',async()=>{const f=fixture();assert.equal((await f.send('{')).status,400);assert.equal((await f.send('x'.repeat(1025))).status,413);assert.equal((await f.send(body,{'content-type':'text/plain'})).status,415);assert.equal((await f.send(body,{},'GET')).status,405);assert.equal(f.calls.length,0)});
test('nonexistent, mismatched, unconfirmed and banned owners denied',async()=>{for(const user of [null,{id:'other'},{id:owner},{id:owner,email_confirmed_at:'yes',banned_until:'2099-01-01'}]){const f=fixture({admin:async()=>({data:{user}})});assert.equal((await f.send()).status,503);assert.equal(f.calls.length,0)}});
test('old capability or missing RPC blocks writes',async()=>{for(const data of [null,{...VOICE_CONTRACT,features:[]},{...VOICE_CONTRACT,domains:[]}]){const f=fixture({rpc:async()=>({data})});assert.equal((await f.send()).error,'backend_incompatible');assert.equal(f.calls.length,1)}});
test('stale revision retries same intent once, then fails bounded',async()=>{for(const failForever of [false,true]){let writes=0;const f=fixture({rpc:async(name)=>name==='ledger_capabilities'?{data:VOICE_CONTRACT}:++writes===1||failForever?{error:{code:'40001'}}:{data:{replayed:false}}});assert.equal((await f.send()).status,failForever?502:200);assert.equal(writes,2);assert.deepEqual(f.calls[1].args,f.calls[2].args)}});
test('commit plus lost acknowledgement replays exactly one logical event',async()=>{const store=new Set();let lost=true;const f=fixture({rpc:async(name,args)=>{if(name==='ledger_capabilities')return {data:VOICE_CONTRACT};const replayed=store.has(args.p_operation);store.add(args.p_operation);if(lost){lost=false;throw new Error('private backend error')}return {data:{replayed}}}});assert.equal((await f.send()).error,'unconfirmed');assert.equal((await f.send()).duplicate,true);assert.equal(store.size,1)});
test('rate limited, invalid identity, backend missing and timeout replies sanitized',async()=>{for(const [code,status]of [['P0429',429],['22023',409],['42883',503],['XX000',502]]){const f=fixture({rpc:async(name)=>name==='ledger_capabilities'?{data:VOICE_CONTRACT}:{error:{code,message:'secret detail'}}});const r=await f.send();assert.equal(r.status,status);assert(!JSON.stringify(r).includes('secret'))}const f=fixture({admin:async()=>{throw new DOMException('secret','TimeoutError')}});assert.equal((await f.send()).error,'unconfirmed')});
test('public config never exports voice owner/token or privileged key',async()=>{
 const {publicConfig}=await import('../scripts/public-config.mjs');
 const output=JSON.stringify(publicConfig({...env,SUPABASE_PUBLISHABLE_KEY:'sb_publishable_synthetic'}));
 for(const secret of [env.FIFTY_A_VOICE_TOKEN,env.FIFTY_A_VOICE_OWNER_ID,env.SUPABASE_SERVICE_ROLE_KEY,'FIFTY_A_VOICE'])assert(!output.includes(secret));
});
