import {test} from 'node:test';import assert from 'node:assert/strict';
import {Compatibility,CURRENT_CONTRACT,DOMAIN_VERSIONS,contractKey,classify,missing} from '../cloud/contract.mjs';
import {DeviceLedger} from '../cloud/device.mjs';import {baselineFixture} from './cloud-fixture.mjs';import {fromCloud} from '../cloud/ledger-model.mjs';import Auto from '../automotive-utils.js';import {checkSnapshot} from '../scripts/check-cloud-contract.mjs';
const store=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}};
const legacy={contract_version:1,domains:CURRENT_CONTRACT.domains.filter(d=>DOMAIN_VERSIONS[d]===1),features:['tax_bucket','multi_property_photos'],read_versions:[1]};
const change=d=>({[d]:{put:[],remove:['id']}});
function setup(){const storage=store();let backend=CURRENT_CONTRACT,error;const args={storage,project:'https://project.supabase.co',owner:'owner',probe:async()=>{if(error)throw error;return backend}};return {args,c:new Compatibility(args),backend:c=>backend=c,error:e=>error=e};}
test('unknown fails closed; compatible verifies; legacy permits compatible domains only',async()=>{const {c,backend}=setup();assert.throws(()=>c.assert(change('vehicles')),/Cloud update/);await c.check();c.assert(change('vehicles'));backend(legacy);await c.check();assert.equal(c.state,'incompatible');assert.throws(()=>c.assert(change('vehicles')),/Cloud update/);for(const d of legacy.domains)c.assert(change(d));assert.throws(()=>c.assert({transaction_items:{put:[{bucket:'automotive'}],remove:[]}}));});
test('offline uses verified contract; new contract/account/project never inherits permission',async()=>{const {c,args,error}=setup();await c.check();error(Error('offline'));await c.check();assert.equal(c.state,'unknown');c.assert(change('fuel_events'));const reloaded=new Compatibility(args);reloaded.assert(change('vehicles'));for(const override of [{owner:'other'},{project:'https://other.supabase.co'}])assert.throws(()=>new Compatibility({...args,...override}).assert(change('vehicles')));const key=contractKey(args.project,args.owner),saved=JSON.parse(args.storage.getItem(key));saved.applicationContract=1;saved.contract=legacy;args.storage.setItem(key,JSON.stringify(saved));const upgraded=new Compatibility(args);assert.throws(()=>upgraded.assert(change('vehicles')));upgraded.assert(change('water_events'));assert.throws(()=>c.assert(change('future_v3_domain')));});
test('explicit incompatibility revokes persisted grants, unlike transient loss; auth distinct',async()=>{const {c,args,error}=setup();await c.check();error({code:'PGRST202'});await c.check();assert.throws(()=>c.assert(change('vehicles')));assert.throws(()=>new Compatibility(args).assert(change('vehicles')));error({code:'42501'});await c.check();assert.equal(c.state,'auth');});
test('schema, revision, authentication, validation and server errors are distinct',()=>{for(const code of ['42P01','42883','PGRST202','PGRST205'])assert.equal(classify({code}),'BACKEND_INCOMPATIBLE');assert.equal(classify({code:'P0001',message:'Unsupported domain'}),'BACKEND_INCOMPATIBLE');assert.equal(classify({code:'40001'}),'REVISION_CONFLICT');assert.equal(classify({code:'42501'}),'AUTH_ERROR');assert.equal(classify({code:'23514'}),'VALIDATION_ERROR');assert.equal(classify({code:'XX000'}),'SERVER_ERROR');assert.equal(classify(Error('offline')),'OFFLINE');});
test('exact Ram failure is blocked before queue/draft mutation; upgrade admits one intent',async()=>{const {c,backend}=setup();backend(legacy);await c.check();const snap=await baselineFixture(),owner=snap.owner;snap.state=fromCloud(snap,owner);const storage=store(),repo={assertCompatible:x=>c.assert(x)};const d=new DeviceLedger({storage,repo,owner});d.unlock(owner);d.persist({confirmed:snap,draft:snap.state,draftRows:snap.rows,queue:[]});const next=Auto.saveVehicle(d.view(),{ownerId:owner,nickname:'Ram',year:2019,make:'Ram',model:'1500 Classic',active:true});const before=JSON.stringify(d.data);assert.throws(()=>d.capture(next),/Cloud update/);assert.equal(JSON.stringify(d.data),before);backend(CURRENT_CONTRACT);await c.check();d.capture(next);assert.equal(d.data.queue.length,1);assert.equal(d.data.queue[0].changes.vehicles.put[0].year,2019);});
test('execution-time schema rejection preserves intent without generic conflict or retry',async()=>{const {c}=setup();await c.check();const snap=await baselineFixture(),owner=snap.owner;snap.state=fromCloud(snap,owner);let calls=0;const repo={assertCompatible:x=>c.assert(x),loadLedger:async()=>snap,apply:async()=>{calls++;throw {code:'PGRST202'}}};const d=new DeviceLedger({storage:store(),repo,owner});d.unlock(owner);d.persist({confirmed:snap,draft:snap.state,draftRows:snap.rows,queue:[]});const next=structuredClone(snap.state);next.budget++;d.capture(next);await d.refresh();assert.equal(d.data.queue[0].error,'BACKEND_INCOMPATIBLE');assert.match(d.status,/Cloud update/);await d.refresh();assert.equal(calls,1);assert.throws(()=>d.capture(next),/Cloud update/);assert.equal(d.data.queue.length,1);});
test('preflight rejects missing migrations and capabilities then passes exact complete history',()=>{const files=['20260928000100_automotive_fuel.sql','20260928000200_cloud_capabilities.sql'];const s={migrations:['20260928000100'],capabilities:legacy};assert.deepEqual(checkSnapshot(s,files).pendingMigrations,['20260928000200_cloud_capabilities.sql']);assert.equal(checkSnapshot(s,files).ok,false);s.migrations.push('20260928000200');s.capabilities=CURRENT_CONTRACT;assert.equal(checkSnapshot(s,files).ok,true);assert.deepEqual(missing(CURRENT_CONTRACT),[]);});
test('Check again refreshes unchanged business revision without replacing draft; real remote edits stop rebase',async()=>{const {c}=setup();await c.check();const snap=await baselineFixture(),owner=snap.owner;snap.state=fromCloud(snap,owner);let remote=structuredClone(snap);remote.revision='schema-upgrade';const d=new DeviceLedger({storage:store(),owner,repo:{checkCompatibility:()=>c.check(),loadLedger:async()=>remote,assertCompatible:x=>c.assert(x)}});d.unlock(owner);d.persist({confirmed:snap,draft:snap.state,draftRows:snap.rows,queue:[]});const draft=JSON.stringify(d.view());await d.checkCompatibility();assert.equal(d.data.confirmed.revision,'schema-upgrade');assert.equal(JSON.stringify(d.view()),draft);remote=structuredClone(remote);remote.rows.transactions[0].merchant='Concurrent edit';await assert.rejects(()=>d.checkCompatibility(),/Ledger changed/);assert.equal(JSON.stringify(d.view()),draft);assert.equal(d.data.queue.length,0);});
test('migration checker command exits nonzero for missing Automotive and passes complete synthetic history',async()=>{const {mkdtemp,writeFile,rm,readdir}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{spawnSync}=await import('node:child_process');const dir=await mkdtemp(join(tmpdir(),'contract-check-'));try{const file=join(dir,'hosted.json'),files=await readdir('supabase/migrations'),versions=files.filter(f=>f.endsWith('.sql')).map(f=>f.split('_')[0]);await writeFile(file,JSON.stringify({capabilities:CURRENT_CONTRACT,migrations:versions.filter(v=>v!=='20260928000100')}));let result=spawnSync(process.execPath,['scripts/check-cloud-contract.mjs','--migrations'],{env:{...process.env,CLOUD_CHECK_FIXTURE:file},encoding:'utf8'});assert.equal(result.status,1);assert.match(result.stdout,/20260928000100_automotive_fuel.sql/);await writeFile(file,JSON.stringify({capabilities:CURRENT_CONTRACT,migrations:versions}));result=spawnSync(process.execPath,['scripts/check-cloud-contract.mjs'],{env:{...process.env,CLOUD_CHECK_FIXTURE:file},encoding:'utf8'});assert.equal(result.status,0,result.stderr);}finally{await rm(dir,{recursive:true,force:true})}});
