import {test} from 'node:test';
import assert from 'node:assert/strict';
import Backup from '../backup-utils.js';
import {fixture} from './backup-fixture.cjs';
import {mapSource,hash} from '../scripts/migration/model.mjs';
import {fromCloud,toCloud,diff,validateCloud,metrics} from '../cloud/ledger-model.mjs';
import {DeviceLedger,MODE,cacheKey} from '../cloud/device.mjs';
import {repository} from '../cloud/repository.mjs';
const owner='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',stamp='2026-09-01T12:00:00.000Z';
export async function cloudFixture(){const f=fixture();f.state.condition=[];for(const t of f.state.transactions){t.attachmentIds=[];t.receipt=null;}const b=await Backup.create(f.state,()=>null);const {rows}=mapSource(b,owner,hash(JSON.stringify(b)));for(const list of Object.values(rows))for(const r of list)Object.assign(r,{created_at:stamp,updated_at:stamp});const snap={rows,revision:'v1'};snap.state=await validateCloud(snap,owner);return {snap,b,owner};}
function store(){const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};}
async function device(){const {snap}=await cloudFixture(),storage=store();let current=structuredClone(snap),applied=new Map(),fail=null,calls=0;const repo={loadLedger:async()=>structuredClone(current),apply:async op=>{calls++;if(fail)throw fail;if(applied.has(op.id))return applied.get(op.id);assert.equal(op.revision,current.revision);for(const [t,c] of Object.entries(op.changes)){current.rows[t]=current.rows[t].filter(r=>!c.remove.includes(r.id??r.owner_id));for(const r of c.put){const idx=current.rows[t].findIndex(x=>(x.id??x.owner_id)===(r.id??r.owner_id));const next={...r,created_at:stamp,updated_at:stamp};if(idx<0)current.rows[t].push(next);else current.rows[t][idx]=next;}}current.revision='v'+(applied.size+2);current.state=await validateCloud(current,owner);const ack={revision:current.revision};applied.set(op.id,ack);return ack;}};const d=new DeviceLedger({storage,repo,owner});d.unlock(owner);d.persist({owner,confirmed:snap,draft:snap.state,draftRows:snap.rows,queue:[],lastRefresh:stamp});return {d,storage,repo,fail:e=>fail=e,current:()=>current,calls:()=>calls};}
test('cloud reconstruction preserves finances, source meanings and exports valid v3',async()=>{const {snap,b}=await cloudFixture();const runtime=fromCloud(snap,owner);assert.equal(metrics(runtime).all,253);assert.equal(metrics(runtime).runRate,1119);assert.equal(metrics(runtime).water,2);const backup=await Backup.create(runtime,()=>null);await Backup.validate(backup);assert.deepEqual(diff(snap.rows,toCloud(runtime,owner,snap.rows)),{});await assert.rejects(()=>validateCloud(snap,owner,true),/reconciliation/);assert.equal(b.state.transactions.length,runtime.transactions.length);});
test('owner mismatch and malformed relations rejected',async()=>{const {snap}=await cloudFixture();assert.throws(()=>fromCloud(snap,'bbbbbbbb-bbbb-4bbb-abbb-bbbbbbbbbbbb'),/owner/);snap.rows.transaction_items[0].transaction_id='missing';assert.throws(()=>fromCloud(snap,owner),/Dangling/);});
test('queue survives reload, replays in order and recomputes cache from cloud',async()=>{const {d,storage,repo,current}=await device();let s=structuredClone(d.view());s.settings.waterdropPayback.waterdropCompletions.push({id:crypto.randomUUID(),completedAt:stamp,gallon:3,legacy:false});s.settings.waterdropPayback.gallonsLogged=3;d.capture(s);s=structuredClone(s);s.settings.joshRent=1500;d.capture(s);const reloaded=new DeviceLedger({storage,repo,owner});assert.equal(reloaded.view(),null);reloaded.unlock(owner);assert.equal(reloaded.data.queue.length,2);await reloaded.refresh();assert.equal(reloaded.data.queue.length,0);assert.equal(current().rows.water_events.length,3);assert.equal(reloaded.view().settings.joshRent,1500);});
test('failed replay retains intent; conflict fetches remote without replacing pending intent',async()=>{const {d,fail}=await device();const s=structuredClone(d.view());s.budget=450;d.capture(s);const id=d.data.queue[0].id;fail(Error('offline'));await d.refresh();assert.equal(d.data.queue[0].id,id);assert.equal(d.view().budget,450);fail({code:'40001'});await d.refresh();assert.equal(d.data.queue[0].error,'conflict');assert.equal(d.view().budget,450);assert.throws(()=>d.capture(s),/conflict/);await assert.rejects(()=>d.backup(),/pending/);});
test('sign-out and account isolation hide cache and block mutations; rollback preserves original and recovery',async()=>{const {d,storage}=await device();storage.setItem('fiftyA-ledger-v1','original');storage.setItem(MODE,JSON.stringify({mode:'cloud',owner}));d.lock();assert.equal(d.view(),null);assert.throws(()=>d.capture({}),/locked/);assert.throws(()=>d.unlock('other'),/mismatch/);d.unlock(owner);d.rollback();assert.equal(storage.getItem('fiftyA-ledger-v1'),'original');assert.ok(storage.getItem(cacheKey(owner)));assert.equal(JSON.parse(storage.getItem(MODE)).mode,'local');});
test('activation failure preserves mode and local data',async()=>{const {d,storage}=await device();storage.setItem('fiftyA-ledger-v1','original');d.repo.loadLedger=async()=>{throw Error('Baseline mismatch')};await assert.rejects(()=>d.activate(d.view(),()=>null,()=>{}));assert.equal(storage.getItem(MODE),null);assert.equal(storage.getItem('fiftyA-ledger-v1'),'original');});
test('repository domain operations map stable CRUD intent including variable/fixed semantics',async()=>{const {snap}=await cloudFixture();const r=repository({},owner);const linked=snap.state.transactions.find(t=>t.recurringChargeId);const t={...linked,items:[{...linked.items[0],amount:75}],oneTimeAmount:0};const op=r.updateTransaction(snap,t,{updateMonthlyEstimate:true});assert.equal(op.changes.recurring_charges.put[0].amount,75);assert.equal(op.changes.transaction_items.put[0].amount,75);assert.equal(r.deactivateRecurringCharge(snap,snap.state.recurringCharges[0].id).changes.recurring_charges.put[0].active,false);assert.equal(r.updateBenchmarkAdjustments(snap,[{label:'Synthetic',amount:1}]).changes.benchmark_adjustments.put.length,1);assert.equal(r.undoWaterEvent(snap,snap.state.settings.waterdropPayback.waterdropCompletions[1].id).changes.water_events.remove.length,1);});

test('explicit conflict resolution archives local intent without overwriting cloud',async()=>{const {d,fail}=await device();const s=structuredClone(d.view());s.budget=777;d.capture(s);fail({code:'40001'});await d.refresh();await d.useRemote();assert.equal(d.data.queue.length,0);assert.equal(d.data.archivedIntents[0].operations.length,1);assert.equal(d.view().budget,400);});

test('lost acknowledgement replays the same UUID without duplicating the event',async()=>{const {d,repo,current}=await device();const s=structuredClone(d.view()),w=s.settings.waterdropPayback;w.waterdropCompletions.push({id:crypto.randomUUID(),gallon:3,completedAt:stamp,legacy:false});w.gallonsLogged=3;d.capture(s);const apply=repo.apply;let first=true;repo.apply=async op=>{const result=await apply(op);if(first){first=false;throw Error('Connection lost after commit')}return result};await d.refresh();assert.equal(d.data.queue.length,1);assert.equal(current().rows.water_events.length,3);await d.refresh();assert.equal(d.data.queue.length,0);assert.equal(current().rows.water_events.length,3);});

test('item-only edits include the parent for atomic payment validation',async()=>{const {snap}=await cloudFixture();const next=structuredClone(snap.state);next.transactions[0].items[0].amount=19;const changes=diff(snap.rows,toCloud(next,owner,snap.rows));assert.equal(changes.transactions.put[0].id,next.transactions[0].id);});
