import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Evidence,journalKey,prepareImage,LIMIT} from '../cloud/evidence.mjs';
import {baselineFixture} from './cloud-fixture.mjs';
import {fromCloud} from '../cloud/ledger-model.mjs';
import Backup from '../backup-utils.js';
async function setup(){
 const snapshot=await baselineFixture(),owner=snapshot.owner;snapshot.state=fromCloud(snapshot,owner);let cloud=structuredClone(snapshot),fail={},allowed=true;const files=new Map(),store=new Map(),receipts=new Map();
 const client={auth:{getUser:async()=>({data:{user:{id:owner}}})},storage:{from:()=>({upload:async(path,blob)=>{if(fail.upload)return {error:Error()};files.set(path,blob);return {};},download:async path=>({data:fail.download?null:files.get(path)}),remove:async paths=>{if(fail.cleanup)return {error:Error()};paths.forEach(p=>files.delete(p));return {};}})}};
 const repo={loadLedger:async()=>structuredClone(cloud),apply:async op=>{if(receipts.has(op.id))return receipts.get(op.id);if(fail.rpc)throw {code:'23514'};if(fail.unknown)throw Error('network');for(const [table,c]of Object.entries(op.changes)){cloud.rows[table]=cloud.rows[table].filter(r=>!c.remove.includes(r.id));for(const r of c.put){cloud.rows[table]=cloud.rows[table].filter(x=>x.id!==r.id);cloud.rows[table].push({...r,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});}}cloud.state=fromCloud(cloud,owner);cloud.revision=crypto.randomUUID();receipts.set(op.id,{revision:cloud.revision});if(fail.ack)throw Error('Lost acknowledgement');return receipts.get(op.id);}};
 const evidence=new Evidence({client,repo,owner,storage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},allowed:()=>allowed,online:()=>!fail.offline,compress:async f=>f});
 const blob=new Blob([Buffer.from('UklGRhIAAABXRUJQVlA4TAYAAAAvAAAAAA==','base64')],{type:'image/webp'});
 const file={file:blob,parentType:'transaction',parentId:cloud.state.transactions[0].id};
 return {evidence,client,repo,files,fail,store,owner,blob,file,snapshot,cloud:()=>cloud,lock:()=>allowed=false};
}
test('cloud evidence mapping, multi-image save, byte-complete backup and parent deletion cleanup',async()=>{const x=await setup();const {snapshot}=await x.evidence.save(x.snapshot,x.snapshot.state,[x.file,x.file]);assert.equal(snapshot.rows.attachments.length,2);assert.equal(x.files.size,2);const backup=await Backup.create(snapshot.state,id=>x.evidence.get(snapshot.rows.attachments.find(a=>a.id===id)));assert.equal(backup.attachments.length,2);await Backup.validate(backup);const next=structuredClone(snapshot.state);next.transactions=next.transactions.filter(t=>t.id!==x.file.parentId);await x.evidence.save(snapshot,next);assert.equal(x.files.size,0);assert.equal(x.cloud().rows.attachments.length,0);assert.equal(x.evidence.pending(),null);});
for(const failure of ['upload','download','rpc'])test(`${failure} failure compensates new objects and retains prior data`,async()=>{const x=await setup();x.fail[failure]=true;await assert.rejects(()=>x.evidence.save(x.snapshot,x.snapshot.state,[x.file]));assert.equal(x.files.size,0);assert.equal(x.cloud().rows.attachments.length,0);assert.equal(x.evidence.pending(),null);});
test('cleanup failure is durable and recoverable',async()=>{const x=await setup();x.fail.rpc=true;x.fail.cleanup=true;await assert.rejects(()=>x.evidence.save(x.snapshot,x.snapshot.state,[x.file]));assert.ok(x.evidence.pending());assert.equal(x.files.size,1);x.fail.cleanup=false;await x.evidence.resolve();assert.equal(x.files.size,0);assert.equal(x.evidence.pending(),null);});
test('lost acknowledgement retries same operation without duplicate or deleting committed bytes',async()=>{const x=await setup();x.fail.ack=true;await assert.rejects(()=>x.evidence.save(x.snapshot,x.snapshot.state,[x.file]),/unconfirmed/);assert.equal(x.files.size,1);await x.evidence.resolve();assert.equal(x.cloud().rows.attachments.length,1);assert.equal(x.files.size,1);});
test('replacement failure retains old good evidence; deletion failure retains metadata and bytes',async()=>{const x=await setup();const {snapshot}=await x.evidence.save(x.snapshot,x.snapshot.state,[x.file]);const next=structuredClone(snapshot.state);next.transactions.find(t=>t.id===x.file.parentId).attachmentIds=[];x.fail.rpc=true;await assert.rejects(()=>x.evidence.save(snapshot,next,[x.file]));assert.equal(x.files.size,1);assert.equal(x.cloud().rows.attachments[0].id,snapshot.rows.attachments[0].id);await assert.rejects(()=>x.evidence.save(snapshot,next));assert.equal(x.files.size,1);});
test('committed deletion with failed Storage cleanup remains visible as pending recovery',async()=>{const x=await setup();const {snapshot}=await x.evidence.save(x.snapshot,x.snapshot.state,[x.file]);const next=structuredClone(snapshot.state);next.transactions.find(t=>t.id===x.file.parentId).attachmentIds=[];x.fail.cleanup=true;const result=await x.evidence.save(snapshot,next);assert.ok(result.warning);assert.equal(x.cloud().rows.attachments.length,0);assert.equal(x.files.size,1);x.fail.cleanup=false;await x.evidence.resolve();assert.equal(x.files.size,0);});
test('offline and locked accounts cannot upload or view; missing object fails backup',async()=>{const x=await setup();x.fail.offline=true;await assert.rejects(()=>x.evidence.save(x.snapshot,x.snapshot.state,[x.file]));assert.equal(x.files.size,0);x.fail.offline=false;const {snapshot}=await x.evidence.save(x.snapshot,x.snapshot.state,[x.file]);x.files.clear();await assert.rejects(()=>Backup.create(snapshot.state,id=>x.evidence.get(snapshot.rows.attachments.find(a=>a.id===id))));x.lock();await assert.rejects(()=>x.evidence.get(snapshot.rows.attachments[0]));assert.equal(x.store.has(journalKey(x.owner)),false);});
test('unsupported and oversized input rejected before decoding',async()=>{await assert.rejects(()=>prepareImage(new Blob(['x'],{type:'text/plain'})));await assert.rejects(()=>prepareImage({type:'image/png',size:LIMIT+1}));});

for(const count of [0,1,4])test(`property with ${count} images preserves one parent and deletes every object`,async()=>{
 const x=await setup(),state=structuredClone(x.snapshot.state),id=crypto.randomUUID();state.condition.push({id,room:'Kitchen',phase:'move-in',date:'2026-09-01',notes:'Multiline\nnotes',attachmentIds:[]});
 const files=Array.from({length:count},()=>({file:x.blob,parentType:'condition',parentId:id}));
 const {snapshot}=await x.evidence.save(x.snapshot,state,files);assert.equal(snapshot.state.condition.length,1);assert.equal(snapshot.state.condition[0].attachmentIds.length,count);assert.equal(x.files.size,count);
 assert.deepEqual(snapshot.rows.attachments.map(a=>a.property_position),Array.from({length:count},(_,i)=>i));
 const backup=await Backup.create(snapshot.state,id=>x.evidence.get(snapshot.rows.attachments.find(a=>a.id===id)));const valid=await Backup.validate(backup);assert.equal(valid.decoded.size,count);assert.deepEqual(Backup.runtimeState(backup,'roundtrip').condition,snapshot.state.condition);
 if(count){const first=snapshot.rows.attachments[0];x.files.delete(first.storage_path);await assert.rejects(()=>Backup.create(snapshot.state,id=>x.evidence.get(snapshot.rows.attachments.find(a=>a.id===id))));x.files.set(first.storage_path,x.blob)}
 const next=structuredClone(snapshot.state);next.condition=[];await x.evidence.save(snapshot,next);assert.equal(x.files.size,0);assert.equal(x.cloud().rows.attachments.length,0);
});
test('multi-photo mixed edit compensates partial upload and rejected finalize, then recovers failed selected cleanup',async()=>{
 const x=await setup(),id=crypto.randomUUID(),state=structuredClone(x.snapshot.state);state.condition.push({id,room:'Kitchen',phase:'move-in',date:'2026-09-01',notes:'Original',attachmentIds:[]});const f={file:x.blob,parentType:'condition',parentId:id};
 const {snapshot}=await x.evidence.save(x.snapshot,state,[f,f,f]);const oldRows=structuredClone(snapshot.rows.attachments),next=structuredClone(snapshot.state);next.condition[0].attachmentIds.splice(1,1);next.condition[0].notes='Edited';
 // Evidence holds the returned bucket; inject an nth-upload failure there.
 const upload=x.evidence.bucket.upload;let n=0;x.evidence.bucket.upload=async(...args)=>++n===2?{error:Error('second failed')}:upload(...args);
 await assert.rejects(()=>x.evidence.save(snapshot,next,[f,f]));assert.deepEqual(x.cloud().rows.attachments,oldRows);assert.equal(x.files.size,3);
 x.evidence.bucket.upload=upload;x.fail.rpc=true;await assert.rejects(()=>x.evidence.save(snapshot,next,[f,f]));assert.deepEqual(x.cloud().rows.attachments,oldRows);assert.equal(x.files.size,3);
 x.fail.rpc=false;x.fail.cleanup=true;const result=await x.evidence.save(snapshot,next,[f,f]);assert.ok(result.warning);assert.equal(result.snapshot.rows.attachments.length,4);assert.equal(x.files.size,5);assert.ok(x.evidence.pending());x.fail.cleanup=false;await x.evidence.resolve();assert.equal(x.files.size,4);assert.equal(x.evidence.pending(),null);assert.deepEqual(x.cloud().state.condition[0].attachmentIds.slice(0,2),[oldRows[0].id,oldRows[2].id]);
});
