import {test} from 'node:test';
import assert from 'node:assert/strict';
import Backup from '../backup-utils.js';
import {fixture} from './backup-fixture.cjs';
import {hash,verifySource,mapSource,destinationState,reconcile,financials,counts,money,schemaSignature} from '../scripts/migration/model.mjs';
export const owner='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa';
export async function synthetic(){const f=fixture();f.state.condition=[];for(const t of f.state.transactions){t.attachmentIds=[];t.receipt=null;}f.state.transactions[0].items[0].adjustment='';const b=await Backup.create(f.state,()=>null);const bytes=Buffer.from(JSON.stringify(b));return {b,bytes,authorized:{sha256:hash(bytes),bytes:bytes.length,state:b.integrity.stateSha256,manifest:b.integrity.manifestSha256}};}
test('certified gate refuses wrong raw hash and validates v3 independently',async()=>{const {b,bytes,authorized}=await synthetic();await verifySource(bytes,authorized);await assert.rejects(()=>verifySource(Buffer.concat([bytes,Buffer.from(' ')]),authorized),/SHA/);b.state.budget++;const bad=Buffer.from(JSON.stringify(b));await assert.rejects(()=>verifySource(bad,{...authorized,sha256:hash(bad),bytes:bad.length}),/hash mismatch/);});
test('deterministic mapping, references, numeric semantics and no evidence',async()=>{const {b,authorized}=await synthetic();const a=mapSource(b,owner,authorized.sha256),again=mapSource(b,owner,authorized.sha256);assert.deepEqual(a,again);assert.equal(a.rows.transactions[0].recurring_charge_id,a.rows.recurring_charges[1].id);assert.equal(a.rows.transaction_items[0].transaction_id,a.rows.transactions[0].id);assert.equal(a.rows.transaction_items[0].adjustment,0);assert.equal(a.rows.transactions[0].one_time_amount,30);assert.equal(a.rows.water_events[1].completed_at,null);assert.equal(a.rows.attachments.length,0);assert.equal(a.rows.property_condition.length,0);assert.equal(financials(a.rows).allPeriodExpenses,253);assert.equal(financials(a.rows).recurringRunRate,1119);assert.equal(financials(a.rows).annualSavings,7828.56);});
test('initial nonempty refusal; exact retry is no-op; partial/changed destination refuses',async()=>{const {b,authorized}=await synthetic();const {rows}=mapSource(b,owner,authorized.sha256);const empty=Object.fromEntries(Object.keys(rows).map(t=>[t,[]]));assert.equal(destinationState(empty,rows,false),'empty');assert.throws(()=>destinationState(rows,rows,false),/Nonempty/);assert.equal(destinationState(rows,rows,true),'already-applied');const partial=structuredClone(rows);partial.transactions.pop();assert.throws(()=>destinationState(partial,rows,true));const changed=structuredClone(rows);changed.transaction_items[0].amount++;assert.throws(()=>destinationState(changed,rows,true),/projection/);});
test('independent reconciliation detects count, relationship, settings, event and money drift',async()=>{const {b,authorized}=await synthetic();const {rows}=mapSource(b,owner,authorized.sha256);assert.deepEqual(reconcile(rows,structuredClone(rows),owner).counts,counts(rows));for(const mutate of [r=>r.transaction_items.pop(),r=>r.transaction_items[0].transaction_id='invalid',r=>r.user_settings[0].setup_budget++,r=>r.water_events[0].gallons++,r=>r.transaction_items[0].amount++]){const changed=structuredClone(rows);mutate(changed);assert.throws(()=>reconcile(rows,changed,owner));}});
test('mapping refuses numeric rounding and date-only event precision loss',async()=>{assert.throws(()=>money(1.234));assert.throws(()=>money(Infinity));const {b,authorized}=await synthetic();b.state.settings.waterdropPayback.waterdropCompletions[0].completedAt='2026-09-01';assert.throws(()=>mapSource(b,owner,authorized.sha256),/precision/);});

test("schema comparison ignores catalog collation order but detects changed definitions",()=>{const a={constraints:[{definition:"A"},{definition:"B"}]};assert.equal(schemaSignature(a),schemaSignature({constraints:[...a.constraints].reverse()}));assert.notEqual(schemaSignature(a),schemaSignature({constraints:[{definition:"changed"}]}));});
