import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import sharp from 'sharp';
import {createDraftHandler,DRAFT_BYTES,REQUEST_BYTES} from '../server/receipt-ocr-draft.mjs';
import {receiptResponse} from './receipt-fixture.mjs';
const owner='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa';
const png=await sharp({create:{width:4,height:3,channels:3,background:'white'}}).png().toBuffer();
const image=(data=png,type='image/png')=>new Blob([data],{type});
function fixture(options={}){
 let calls=0,last,clock=0;
 const handler=createDraftHandler({env:{SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_synthetic'},now:()=>clock,makeSupabase:()=>({auth:{getUser:async()=>({data:{user:options.invalid?null:{id:owner,is_anonymous:options.anonymous}}})}}),analyze:async images=>{calls++;last=images;if(options.error)throw options.error;await options.wait?.();return receiptResponse;}});
 return {get calls(){return calls},get last(){return last},advance:()=>clock+=60001,async run({files=[image()],extra,headers={},method='POST',raw}={}){const form=new FormData();files.forEach(file=>form.append('images',file,'synthetic'));if(extra)form.append(...extra);const request=new Request('https://preview.vercel.app',{method:'POST',body:form});const bytes=raw||Buffer.from(await request.arrayBuffer());const req=Readable.from([bytes]);Object.assign(req,{method,headers:{host:'preview.vercel.app',origin:'https://preview.vercel.app',authorization:'Bearer synthetic','content-type':request.headers.get('content-type'),...headers}});let output;const res={headers:{},setHeader(k,v){this.headers[k]=v},end(v){output=JSON.parse(v)}};await handler(req,res);return {status:res.statusCode,body:output,headers:res.headers};}};
}
test('draft authenticates, fully decodes ordered image bytes, calls shared analysis once; no database/storage capability needed',async()=>{const f=fixture(),jpeg=await sharp(png).jpeg().toBuffer(),r=await f.run({files:[image(jpeg,'image/jpeg'),image()]});assert.equal(r.status,200);assert.deepEqual(r.body,receiptResponse);assert.equal(f.calls,1);assert.equal(f.last[0].image_url,'data:image/jpeg;base64,'+jpeg.toString('base64'));assert.equal(f.last[1].image_url,'data:image/png;base64,'+png.toString('base64'));assert.match(r.headers['Cache-Control'],/no-store/);assert(!('Access-Control-Allow-Origin'in r.headers));});
for(const [name,options,input,status] of [
 ['invalid session',{invalid:true},{},401],['anonymous identity',{anonymous:true},{},401],['no bearer',{}, {headers:{authorization:''}},401],['cross origin',{}, {headers:{origin:'https://elsewhere.test'}},403],['missing origin',{}, {headers:{origin:''}},403],['insecure hosted origin',{}, {headers:{origin:'http://preview.vercel.app'}},403],['GET',{}, {method:'GET'},405],['wrong request MIME',{}, {headers:{'content-type':'application/json'}},415],['bounded declared body',{}, {headers:{'content-length':String(REQUEST_BYTES+1)}},413],['bounded actual stream',{}, {raw:Buffer.alloc(REQUEST_BYTES+1)},413],['malformed multipart',{}, {raw:Buffer.from('invalid')},400],['zero files',{}, {files:[]},400],['five files',{}, {files:Array(5).fill(image())},400],['owner input',{}, {extra:['owner_id',owner]},400],['URL input',{}, {extra:['url','https://elsewhere.test']},400],['model input',{}, {extra:['model','anything']},400],['unsupported MIME',{}, {files:[image(png,'application/pdf')]},415],['spoofed MIME',{}, {files:[image(png,'image/jpeg')]},415],['corrupt image',{}, {files:[image(Buffer.from('corrupt'))]},415],['truncated image',{}, {files:[image(png.subarray(0,30))]},415],['empty image',{}, {files:[image(Buffer.alloc(0))]},413],['large image',{}, {files:[image(Buffer.alloc(DRAFT_BYTES+1))]},413],['combined limit',{}, {files:[image(Buffer.concat([png,Buffer.alloc(DRAFT_BYTES/2)])),image(Buffer.alloc(DRAFT_BYTES/2))]},413]
])test('draft rejects '+name+' before provider',async()=>{const f=fixture(options),r=await f.run(input);assert.equal(r.status,status);assert.equal(f.calls,0);assert(!JSON.stringify(r.body).includes(owner));});
test('draft rejects dimension bombs before provider',async()=>{const f=fixture(),large=await sharp({create:{width:1601,height:1,channels:3,background:'white'}}).png().toBuffer();assert.equal((await f.run({files:[image(large)]})).status,415);assert.equal(f.calls,0)});
test('draft per-user rate and concurrency guards are bounded; expiry permits explicit retry',async()=>{let finish,entered;const start=new Promise(r=>entered=r),f=fixture({wait:()=>{entered();return new Promise(r=>finish=r)}});const first=f.run();await start;assert.equal((await f.run()).status,429);finish();assert.equal((await first).status,200);const g=fixture();for(let i=0;i<3;i++)assert.equal((await g.run()).status,200);assert.equal((await g.run()).status,429);g.advance();assert.equal((await g.run()).status,200)});
test('draft provider failures are sanitized, no automatic retry',async()=>{const f=fixture({error:{status:500,message:'private provider content'}}),r=await f.run();assert.equal(r.status,502);assert.equal(f.calls,1);assert(!JSON.stringify(r).includes('private provider content'))});
