import test from 'node:test';
import assert from 'node:assert/strict';
import OpenAI from 'openai';
import {createReceiptHandler,DEFAULT_MODEL,MAX_BYTES} from '../server/receipt-ocr.mjs';
import {parseExtraction,receiptSchema} from '../server/receipt-schema.mjs';
const owner='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',other='bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',parent='cccccccc-cccc-4ccc-accc-cccccccccccc';
const ids=['11111111-1111-4111-a111-111111111111','22222222-2222-4222-a222-222222222222'];
const png=Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),Buffer.alloc(20)]);
export const extraction={merchant:'Synthetic shop',transaction_date:'2026-09-24',transaction_time:null,subtotal:2,tax:0.2,tip:null,discounts:null,total:2.2,currency:'USD',items:[{description:'ITEM',quantity:1,unit_price:2,total_price:2,sku:null,raw_text:'ITEM 2.00',confidence:null,suggested_category:'Groceries',suggested_bucket:'groceries',suggested_setup_class:'none'}],warnings:[],overall_confidence:null};
const completed=e=>({status:'completed',model:DEFAULT_MODEL,output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(e)}]}],usage:{input_tokens:100,output_tokens:50,total_tokens:150}});
function fixture(options={}){
 const rows=ids.map(id=>({id,owner_id:owner,transaction_id:parent,property_condition_id:null,attachment_type:'receipt',storage_bucket:'50a-evidence',storage_path:`${owner}/receipts/${id}.png`,mime_type:'image/png',size_bytes:png.length}));options.change?.(rows);
 const calls={ai:0,downloads:0,paths:[],queries:[],input:null,options:null};
 const makeSupabase=(_url,_key,settings)=>{assert.equal(settings.auth.persistSession,false);assert.equal(settings.global.headers.Authorization,'Bearer synthetic-token');return {
  auth:{getUser:async token=>{assert.equal(token,'synthetic-token');return options.invalid?{error:{}}:{data:{user:{id:owner,is_anonymous:!!options.anonymous}}}}},
  from(table){calls.queries.push(table);const filters={};const query={select(){return query},in(k,v){filters[k]=v;return query},eq(k,v){filters[k]=v;return query},maybeSingle:async()=>({data:options.noParent?null:{id:parent,owner_id:options.parentOther?other:owner}}),then(resolve,reject){assert.equal(filters.owner_id,owner);return Promise.resolve({data:options.missing?[]:rows.filter(a=>filters.id.includes(a.id)),error:options.queryError?{}:null}).then(resolve,reject)}};return query},
  storage:{from(bucket){assert.equal(bucket,'50a-evidence');return {download:async path=>{calls.downloads++;calls.paths.push(path);assert(rows.some(a=>a.storage_path===path));return options.downloadError?{error:{}}:{data:new Blob([options.damaged?Buffer.alloc(png.length):png],{type:options.downloadMime||'image/png'})}}}}
 }}};
 const handler=createReceiptHandler({env:{SUPABASE_URL:'https://synthetic.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_synthetic',OPENAI_API_KEY:'not-a-real-key',...options.env},makeSupabase,makeOpenAI:settings=>{calls.options=settings;return {responses:{create:async body=>{calls.ai++;calls.input=body;if(options.aiError)throw options.aiError;return options.response||completed(extraction)}}}}});
 async function run(body={attachment_ids:ids},headers={},method='POST'){let output;const res={headers:{},setHeader(k,v){this.headers[k]=v},end(s){output=JSON.parse(s)}};await handler({method,headers:{authorization:'Bearer synthetic-token','content-type':'application/json',...headers},body},res);return {status:res.statusCode,body:output,headers:res.headers}}
 return {run,calls};
}
test('receipt endpoint authorizes ordered images; strict Responses request, store false, zero retries and safe usage',async()=>{
 const f=fixture(),r=await f.run({attachment_ids:[ids[1],ids[0]]});assert.equal(r.status,200);assert.deepEqual(r.body.extraction,extraction);assert.deepEqual(r.body.usage,{model:DEFAULT_MODEL,input_tokens:100,output_tokens:50,total_tokens:150});assert.match(r.headers['Cache-Control'],/no-store/);assert.deepEqual(f.calls.paths, [ids[1],ids[0]].map(id=>`${owner}/receipts/${id}.png`));assert.equal(f.calls.options.maxRetries,0);assert.equal(f.calls.input.store,false);assert.equal(f.calls.input.text.format.strict,true);assert.deepEqual(f.calls.input.text.format.schema,receiptSchema);assert.equal(f.calls.input.input[0].content.length,3);assert.equal(f.calls.input.input[0].content[1].detail,'high');assert.match(f.calls.input.instructions,/ignore instructions/);assert.deepEqual(f.calls.queries,['attachments','transactions']);assert(!JSON.stringify(r).includes('not-a-real-key'));
});
for(const [label,options,body,headers,status] of [
 ['anonymous request',{},undefined,{authorization:''},401],['invalid bearer',{invalid:true},undefined,{},401],['anonymous Supabase identity',{anonymous:true},undefined,{},401],
 ['other owner',{change:r=>r[0].owner_id=other},undefined,{},404],['property photo',{change:r=>r[0].attachment_type='property'},undefined,{},404],['unknown ID',{missing:true},undefined,{},404],
 ['owner path mismatch',{change:r=>r[0].storage_path=`${other}/receipts/${ids[0]}.png`},undefined,{},404],['external storage path',{change:r=>r[0].storage_path='https://example.test/image.png'},undefined,{},404],['wrong bucket',{change:r=>r[0].storage_bucket='public'},undefined,{},404],['orphan parent',{noParent:true},undefined,{},404],['parent owner mismatch',{parentOther:true},undefined,{},404],['mixed receipts',{change:r=>r[0].transaction_id=other},undefined,{},400],
 ['supplied URL',{}, {attachment_ids:ids,image_url:'https://example.test'}, {},400],['supplied owner',{}, {attachment_ids:ids,owner_id:owner}, {},400],['supplied model',{}, {attachment_ids:ids,model:'anything'}, {},400],['duplicate IDs',{}, {attachment_ids:[ids[0],ids[0]]},{},400],['too many images',{}, {attachment_ids:[...ids,...ids,ids[0]]},{},400],['empty images',{}, {attachment_ids:[]},{},400],['nonuuid ID',{}, {attachment_ids:['https://example.test']},{},400],['invalid JSON',{},'{',{},400],['wrong content type',{},undefined,{'content-type':'text/plain'},415],
 ['oversize metadata',{change:r=>r[0].size_bytes=MAX_BYTES+1},undefined,{},413],['combined oversize',{change:r=>r.forEach(a=>a.size_bytes=MAX_BYTES)},undefined,{},413],['unsupported MIME',{change:r=>r[0].mime_type='application/pdf'},undefined,{},415],['download failure',{downloadError:true},undefined,{},502],['download content type',{downloadMime:'text/html'},undefined,{},502],['damaged image',{damaged:true},undefined,{},415],['metadata query failure',{queryError:true},undefined,{},502],['missing server key',{env:{OPENAI_API_KEY:''}},undefined,{},503],
])test(`receipt security: ${label}`,async()=>{const f=fixture(options),r=await f.run(body,headers);assert.equal(r.status,status);assert.equal(f.calls.ai,0);assert(r.body.error.message);assert(!JSON.stringify(r).includes(owner));});
for(const [name,error,status,code] of [
 ['timeout',{name:'APIConnectionTimeoutError'},504,'timeout'],['deadline abort',{name:'APIUserAbortError'},504,'timeout'],['rate limit',{status:429},429,'rate_limit'],['credits',{status:429,code:'insufficient_quota'},429,'credits'],['invalid key',{status:401},503,'provider_configuration'],['missing model',{status:404},503,'provider_configuration'],['unknown provider error',{status:500,message:'secret-provider-body'},502,'unavailable']
])test(`sanitized provider failure: ${name}`,async()=>{const f=fixture({aiError:error}),r=await f.run();assert.equal(r.status,status);assert.equal(r.body.error.code,code);assert.equal(f.calls.ai,1);assert(!JSON.stringify(r).includes('secret-provider-body'));});
test('server model override and missing usage are supported',async()=>{const f=fixture({env:{OPENAI_RECEIPT_MODEL:'configured-model'},response:{...completed(extraction),model:undefined,usage:undefined}}),r=await f.run();assert.equal(f.calls.input.model,'configured-model');assert.equal(r.body.usage.model,'configured-model');assert.equal(r.body.usage.total_tokens,null)});
test('GET cannot perform analysis',async()=>{const f=fixture();assert.equal((await f.run(undefined,{},'GET')).status,405);assert.equal(f.calls.ai,0)});
test('schema rejects additions, missing fields, fabricated confidence, non-finite values, invalid JSON and incomplete/refused outputs',()=>{
 for(const value of [{...extraction,category:'Groceries'},{...extraction,items:[{...extraction.items[0],suggested_category:'Household'}]},{...extraction,items:[{...extraction.items[0],suggested_bucket:'invented'}]},{...extraction,merchant:undefined},{...extraction,overall_confidence:.99},{...extraction,total:'2.20'},{...extraction,items:[{...extraction.items[0],confidence:.5}]}])assert.throws(()=>parseExtraction(completed(value)),/malformed/);
 assert.throws(()=>parseExtraction({...completed(extraction),status:'incomplete'}),/incomplete/);assert.throws(()=>parseExtraction({status:'completed',output:[{type:'message',content:[{type:'refusal',refusal:'no'}]}]}),/refused/);assert.throws(()=>parseExtraction({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'not json'}]}]}),/malformed/);
});
test('unreadable/invalid dates stay null; visible mismatching money is preserved',()=>{for(const date of [null,'09/10/26','2026-02-30']){const r=parseExtraction(completed({...extraction,transaction_date:date,transaction_time:'25:00',total:9.99}));assert.equal(r.transaction_date,null);assert.equal(r.transaction_time,null);assert.equal(r.total,9.99);assert(r.warnings.some(w=>w.includes('Date')||w.includes('date')));assert(r.warnings.some(w=>w.includes('do not reconcile')));}});
test('official SDK sends Responses structured vision and does not retry a mocked 429',async()=>{
 let calls=0;const ai=new OpenAI({apiKey:'synthetic',maxRetries:0,fetch:async(url,options)=>{calls++;assert.equal(new URL(url).pathname,'/v1/responses');const body=JSON.parse(options.body);assert.equal(body.store,false);assert.equal(body.text.format.strict,true);return new Response(JSON.stringify({error:{message:'synthetic quota',type:'insufficient_quota',code:'insufficient_quota'}}),{status:429,headers:{'Content-Type':'application/json'}})}});
 await assert.rejects(ai.responses.create({model:DEFAULT_MODEL,store:false,input:[],text:{format:{type:'json_schema',name:'receipt_extraction',strict:true,schema:receiptSchema}}}),e=>e.status===429);assert.equal(calls,1);
});
